### ISSUE TITLE
[BUG] PipsPager doesn't show up on Android

### ISSUE THREAD

**Issue by pictos** [unoplatform/uno#10072]
### Current behavior

The `PipsPager` doesn't show up on Android but it works on Windows.

![image](https://user-images.githubusercontent.com/20712372/194165149-4689d27c-1d21-4565-bcb2-0bbfd5d8669f.png)

### Expected behavior

Everyone is happy because The dots appear on Android the place.

### How to reproduce it (as minimally and precisely as possible)

Run this code locally
- https://github.com/pictos/UnoRepros/tree/pj/pipsPager-Bug
and see that the Android has the issue.

### Workaround

None

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.3.5

### Relevant plugins

None

### Anything else we need to know?

No

**Comment by MartinZikmund** [comment]
Turns out the reason why this happens is that `PipsPager` is using a font icon glyph which was not available in the "old" icon font, but is now available in the updated one. The best fix for this is then to replace with the new version from https://github.com/unoplatform/uno.fonts/tree/master/webfonts/Uno%20Fluent%20Icons

**Comment by MartinZikmund** [comment]
Yes, as long as the new icon font is used, it is working correctly.
