### ISSUE TITLE
Storyboard animation is preventing a bounded prop to be changed until manually stopped

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#10110]
### Current behavior

When you start a storyboard animation the Completed event fires but the state of animation doesn't change and it blocks the property it bind to from changing until you manually call Stop on storyboard

```
        someStoryboard.Completed += Animation_Completed;

        private void Animation_Completed(object sender, object e)
        {
            System.Diagnostics.Debug.WriteLine($"Animation_Completed");
            if (someStoryboard.GetCurrentState() != ClockState.Stopped)
            {
                someStoryboard.Stop();
                System.Diagnostics.Debug.WriteLine($"Manual stop animation");
            }
        }
```

Results in "Animation_Completed", "Manual stop animation" in the debug output

### Expected behavior

Really stopped animation

### How to reproduce it (as minimally and precisely as possible)

1. Create storyboard animation
2. Run
3. Check out the state in the Completed event

### Workaround

Call Stop() on completed event

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Tested on 4.6.0-dev.576

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on GTK, But I think it's affected on all Uno platforms

**Comment by FrozDark** [comment]
Seems like it works the same way as in WinUI (state is not stopped at completed event). But in uno if I don't manually call Stop on storyboard I can not change the property of an element it references to it just blocks it from changing

**Comment by Xiaoy312** [comment]
It is normal that the `Storyboard::GetCurrentState()` is not `ClockState.Stopped` when `Timeline::Completed` occurs. Because by default the `Timeline::FillBehavior` is `HoldEnd`, which allow the animated value to "stay" after the animation is completed and the timeline will be in a `ClockState.Filling` state on completion.
This is exactly the behavior we are getting from windows, so there is nothing to change here.

Now onto the 2nd part:
\> When you start a storyboard animation the Completed event fires [...] **and it blocks the property it bind to from changing** [...]
Yes, this was an old issue in uno: 
#631 We cannot change the value of a DependencyProperty which has been animated
which was fixed recently.
