### ISSUE TITLE
[Gallery][All Platforms] In `NavigationView` menu item font color is not changing for Dark theme mode.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10137]
### Current behavior

https://user-images.githubusercontent.com/74563602/195927778-f7d1ccf2-f56c-4dcc-b913-e8782cdd330c.mp4

![Controls list](https://user-images.githubusercontent.com/74563602/195928661-f2092c8f-a9eb-4e74-b761-3f029c116ec5.png)

### Expected behavior

![Controls list correct](https://user-images.githubusercontent.com/74563602/195928983-ecc64119-31a8-4b5d-8786-c5f0fee2e8e7.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Click on the Light/Dark theme change toggle button.
3. Notice that the app is displaying in the Dark theme.
4. Go to the 'Theming' or 'UI Components' section.
5. Observe that the Control's name text in the font is displaying in black color and not changing as per the Dark theme mode.

### Affected platforms

WebAssembly, Android, Skia (GTK on Linux/macOS/Windows)

**Comment by jeromelaban** [comment]
@kazo0 @MartinZikmund Does it look familiar?

**Comment by TalhaQuddoos** [comment]
Hi @sakshi173 , I would like to work on this. Could you please assign this to me?

**Comment by MartinZikmund** [comment]
@jeromelaban I have noticed this before and reported https://github.com/unoplatform/uno/issues/10083 (will close as duplicate). It wasn't happening before, because we used the same foreground for both dark and light theme. Most likely the problem is somewhere between `ItemsRepeater` and `NavigationView`.

@TalhaQuddoos I have assigned the issue to you, but most likely it is issue in Uno itself (not in Uno Gallery) and fixing this one specifically may be quite complex as it may involve `ItemsRepeater`, `NavigationView` and `ResourceDictionary`. Because you are probably not familiar with Uno source too extensively yet, if you get stuck, it may be better to choose some more high-level issue first, as tackling this one may be very hard. Feel free to check out other issues from Hacktoberfest list https://github.com/orgs/unoplatform/projects/77

**Comment by agneszitte** [comment]
@sakshi173 if you can help test this bug please

**Comment by sakshi173** [comment]
Verified this issue is fixed, closing it.

**Comment by agneszitte** [comment]
Thanks @sakshi173 !
