### ISSUE TITLE
`When_xLoad_StaticResource` test is failing

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#10164]
### Current behavior

`When_xLoad_StaticResource` and is being disabled in https://github.com/unoplatform/uno/pull/10146

### Expected behavior

It should pass.

**Comment by artemious7** [comment]
This may be related.
I had a problem on a page that uses `x:Load` and has a `ListView` with `ItemTemplateSelector` set to a `StaticResource` which is declared on the same page. Randomly, on Android, the `ItemTemplateSelector` property or an attached property wasn't set after `x:Load` was changed. It only worked when setting the property inline instead of a `StaticResource`.
