### ISSUE TITLE
[Android] Combobox dropdown placement can be a bit misaligned vertically

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#10339]
### Current behavior

When the app is configured with a shell as a `UserControl` while also activating translucent, the `Combobox` dropdown always misaligned itself vertically

![Screenshot_20221104-105032](https://user-images.githubusercontent.com/17461593/200006121-9870327c-a9be-4858-8c78-51840af2ed43.jpg)

Shell.xaml
```
<UserControl x:Class="Comboboxplacement.Shell"
			 xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
			 xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
			 xmlns:local="using:Comboboxplacement">

	<Frame x:Name="NavigationFrame" />
</UserControl>
```

Android Style.xml
```
<?xml version="1.0" encoding="utf-8" ?>
<resources>
	<style name="AppTheme" parent="Theme.AppCompat.Light">

		<!-- This makes the status bar translucent and allows content to be drawn behind -->
		<item name="android:windowTranslucentStatus">true</item>
		
		<!-- This removes the ActionBar -->
		<item name="windowActionBar">false</item>
		<item name="android:windowActionBar">false</item>
		<item name="windowNoTitle">true</item>
		<item name="android:windowNoTitle">true</item>

	</style>
</resources>
```

### Expected behavior

![Screenshot_20221104-105052](https://user-images.githubusercontent.com/17461593/200006140-84fbeacc-636c-4720-b83f-e03f0ab8550b.jpg)

### How to reproduce it (as minimally and precisely as possible)

- Download this sample [Comboboxplacement.zip](https://github.com/unoplatform/uno/files/9939597/Comboboxplacement.zip)
- Deploy on android
- Click on `Combobox`

### Workaround

Setting `Uno.UI.FeatureConfiguration.Popup.UseNativePopup` to `true` fix the misalignment issue. Which, this bug was also happening before `UseNativePopup` was changed to `false` by default.

Which could also introduce this bug #9004 

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.7.0-dev.60

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.3.5

**Comment by jeromelaban** [comment]
## Note for contributor

The positioning of popups is likely not taking Window.VisibleBounds into account, as well as the keyboard position to determine the values.

**Comment by MartinZikmund** [comment]
I have checked the code, but it seems it is taking `VisibleBounds` into account correctly - or rather as the status bar is translucent, the visible bounds technically do include its area. And there is specifically a code that shifts the popup by the status bar height in such case. Now the question is what is the correct behavior. As marking the status bar translucent technically means that we want the view to "extend" under it, so popups do get arranged there and that seems to be correct, or not? @jeromelaban I see you added these lines, so maybe you remember what was the main reason: 

https://github.com/unoplatform/uno/blame/46b2708a536a7f37d83981650b2b4db7364128c7/src/Uno.UI/UI/Xaml/Controls/ComboBox/ComboBox.cs#L856-L862

What is incorrect is that the combo should probably open up down instead of center on top of the box - I need to investigate why it happens this way currently.

**Comment by jeromelaban** [comment]
@MartinZikmund I don't recall specifically what the reason was at that time, but it may also be a mix of Native vs XAML specific tests. At least, there's a UI test for it :) 

https://github.com/unoplatform/uno/blob/1950ce3a19f3c8f5c64bafd65138e37921c30093/src/SamplesApp/SamplesApp.UITests/Windows_UI_Xaml_Controls/ComboBoxTests/UnoSamples_Tests.ComboBoxTests.cs#L65

**Comment by jeromelaban** [comment]
Now with regards to displaying under the translucent bar, It would make sense for ComboBox popups to *not* extend under the bar?
