### ISSUE TITLE
TypeInitializer exception when instantiating an UI component in Unit test.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#10489]
### Current behavior

An unit test that uses an UI component (a CheckBox in the repro project) throws an exception when the component is instantiated:

System.TypeInitializationException: The type initializer for 'Microsoft.UI.Xaml.Controls.Primitives.ButtonBase' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.UI.Xaml.Controls.Control' threw an exception. ---> System.NotSupportedException: Ref assembly

### Expected behavior

No exception should be thrown.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project, compile it an execute the test.

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.6.19

### IDE

Visual Studio 2022

### IDE version

17.3.6

### Anything else we need to know?

The unit test is a copy from the first test method of Given_CheckBox.cs in the uno repository. It only changes Windows.UI.Xaml.Controls to Microsoft.UI.Xaml.Controls. 
If Uno.UI package is used instead of Uno.WinUI it does not throw an exception in instantiation but it does throw the following exception when setting the IsChecked property to true: System.NotSupportedException: Reference assembly
[TestsIssue.zip](https://github.com/unoplatform/uno/files/10043551/TestsIssue.zip)

**Comment by jeromelaban** [comment]
Thanks for the report. Unit testing is not meant to be used this way, make sure to follow [the documentation here](https://github.com/unoplatform/Uno.UITest).

**Comment by ADD-David-Antolin** [comment]
We don't want to do UI Testing in this case. We want to do Unit Testing of an UI component, the same way you do in [here](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Tests/Windows_UI_XAML_Controls/CheckBoxTests/Given_CheckBox.cs). 
That is the same class that we use in the attached repro project, with only the first test method. 
If you can do it we should be able to do it.
I downloaded the uno repository and removed all the clases of Uno.UI.Tests.csproj except to that one. The tests passed.
I changed the Uno.UI ProjectReference to the Uno.UI PackageReference and then the tests failed with the ref assembly exception. 
I think it is because the Uno.UI NuGet does not have the net461 target framework but the Uno.UI project does.

**Comment by jeromelaban** [comment]
Thanks. This particular case is only available internally in Uno.UI for testing, as it uses a mocked UI infrastructure that cannot run anywhere else.

The only possible way to run tests that use actual controls in apps is to run tests inside actual apps. At this time, we're working on getting [uno.ui.runtimetests.engine](https://github.com/unoplatform/uno.ui.runtimetests.engine) package available for all users, though at this time it's still rough around the edges.
