### ISSUE TITLE
[Skia] Support for Acrylic

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10828]
## What would you like to be added:

Add support for Acrylic in Skia targets

## Why is this needed:

Consistency

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by sakshi173** [comment]
@MartinZikmund could you please tell me what is that bug related to, As I am getting seeing this issue for Acrylic in Skia.
**Skia.GTk** , please let me know this bug is for this only or for something else.
![acrylic issue](https://user-images.githubusercontent.com/74563602/218546635-c432c509-b8ef-47cc-8569-b22bd5ce145e.png)
**WASM**
![acrylic correct](https://user-images.githubusercontent.com/74563602/218546733-14bf7e6a-9e7b-49a0-aac3-ab7c9345dac2.png)
