### ISSUE TITLE
Add support for `IconSourceElement`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#10838]
## What would you like to be added:

Ensure it has IconSource as ContentProperty

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by hawkerm** [comment]
I just had to switch to using `IconSourceElement` for `NavigationView` due to the wonkiness of how blending static and data driven menu items works... Filed this bug in WinUI about it as the error message wasn't useful: https://github.com/microsoft/microsoft-ui-xaml/issues/8056

Anyway, means now that my Icons don't work with WASM on Uno when I made sure they did before as non-source versions...

Thanks for opening this issue for tracking, at least I know it's a known issue now.

**Comment by jeromelaban** [comment]
@MartinZikmund I guess this will be fixed with https://github.com/unoplatform/uno/pull/10840 ?
