### ISSUE TITLE
Project name with "Android" leads to code generation error

### ISSUE THREAD

**Issue by FrancoisM** [unoplatform/uno#110]
a project `MyApp.Android` would not compile:

`error CS0234: The type or namespace name 'Views' does not exist in the namespace 'MyApp.Android'`

for file `BindableMetadata.g.cs` :

`bindableType.AddProperty("Touchables", typeof(global::System.Collections.Generic.IList<Android.Views.View>), GetTouchables);`

**Comment by TomekJurkowski** [comment]
Hello @FrancoisM, did you happen to resolve this somehow? I came across similar if not the same issue and I'm seriously struggling to understand why that's happening.

**Comment by Dissolute** [comment]
@TomekJurkowski This issue is a bug in the code generator which creates BindableMetadata.g.cs.

The bug is the missing global keyword in the generic parameter, ie it should read global::Android.Views.View. Without the keyword, it tries to resolve the type in the local namespace, ie it looks for MyApp.Android.Views.View.

The workaround is to use a different local namespace in your project, eg 'Droid' instead of 'Android.'

**Comment by TomekJurkowski** [comment]
@Dissolute thanks for your answer, this is exactly what I was afraid of. I actually thought about changing the namespace of my project not to include the "Android" word and tested it already - it works.

Unfortunately, however, it isn't a solution I can apply, as I have people using my library and changing th namespace would force them to update their projects as well - not the best user experience :/

Thanks anyway, though!

**Comment by ebariche** [comment]
This is fixed in master ! I added a test to avoid those in the future.

Thank you @FrancoisM for your report !
