### ISSUE TITLE
[Android] Gridview dynamic item width is not respected

### ISSUE THREAD

**Issue by Ouillyang** [unoplatform/uno#11055]
### Current behavior

The items are not respecting the ItemWidth property that we set in ItemsWrapGrid.

### Expected behavior

The items are respecting the ItemWidth property that we set in ItemsWrapGrid.

### How to reproduce it (as minimally and precisely as possible)

[GridViewColumns.zip](https://github.com/unoplatform/uno/files/10503538/GridViewColumns.zip)

Launch the app on either Android or iOS
Rotate device (There is a behavior that makes the items take up the whole screen)
You will see different results everytime you rotate

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.6.41

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

Version 17.3.4

**Comment by ajpinedam** [comment]
Hey @Ouillyang 

Thanks for the information provided. I will be working on this issue, and I have some questions.

The Expected Behaviour is:

"The items are respecting the ItemWidth property that we set in ItemsWrapGrid."

But the sample has a Custom Behaviour `GridViewVariableSizeBehavior` that after every `SizeChanged` is overriding the Items `ItemWidth` property.

I ran the sample attached (thanks for the Sample). If we remove the Behaviour, or we set the **ShouldResize** property to **False** `ShouldResize="False"`, I can see the ItemWidth being respected, which matches with what it's expected.

Please let me know if I missed something.

```xaml
<GridView ItemsSource="abcdefg"
            IsItemClickEnabled="True"
            SelectionMode="None"
            local:GridViewVariableSizeBehavior.ShouldResize="False">
    <GridView.ItemsPanel>
        <ItemsPanelTemplate>
            <ItemsWrapGrid MaximumRowsOrColumns="2"
                            ItemWidth="140"
                            ItemHeight="100"
                            Orientation="Horizontal" />
        </ItemsPanelTemplate>
 ...
</GridView>
```

### Video

https://user-images.githubusercontent.com/1900897/217087395-d03a16b6-c527-4a04-af89-76e6b85309fc.mp4

**Comment by Ouillyang** [comment]
Hello @ajpinedam 

Yeah the issue is that it's not respecting the `ItemWidth` that we set through the custom behavior. The intention of that behavior was to automatically resize to take the whole width of the screen whenever we rotate the screen or resize in UWP while respecting the `MaximumRowsOrColumns` property.

You can test on UWP by resizing the window, the items will adjust their `ItemWidth` correctly to the size of the screen.

On android, this does not happen when we rotate the screen, also when you press and hold on an item it will then resize correctly.

After testing again, it looks like it's working properly on iOS.

https://user-images.githubusercontent.com/16458217/217559465-1eedc894-65e0-4e34-9232-3291705a4acd.mp4


https://user-images.githubusercontent.com/16458217/217562027-f43f58f3-9bc0-4e8d-9cda-95bca9075843.MP4

**Comment by ajpinedam** [comment]
@Ouillyang we just merged the PR with the fix
