### ISSUE TITLE
[Gallery][Android/iOS/Wasm] NumberBox- For the 'Evaluates Expression' section arithmetic symbols(+,^,/) are missing on the display keypad.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11150]
### Current behavior

![Numberbox Android issue](https://user-images.githubusercontent.com/74563602/216176987-6fc0ca5b-4e1e-4a7f-aaf2-011d7ed65cb0.png)
![Numberbox iOS issue](https://user-images.githubusercontent.com/74563602/216177007-5a1a8552-0951-4466-acd8-b7f0e41f839c.png)

https://user-images.githubusercontent.com/74563602/216178077-79c45431-4de5-4f4d-a9a7-1427092fadc6.MP4

https://user-images.githubusercontent.com/74563602/216178099-dacd7749-1a51-4f0c-8a2e-892ee856f623.mp4

### Expected behavior

The Displayed keypad should show arithmetic symbols(+,^,/) 

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Click Burger Menu on the left top right.
Click "NumberBox" from the "UI Components" list.
Go to 'A Numberbox that evaluates expressions' Section.
Try to type the number with arithmetic symbols(+,^,/) for calculation
Observe that arithmetic symbols(+,^,/) are missing on the displayed keypad.

### Works on UWP/WinUI

None

### Affected platforms

Android, iOS

**Comment by Youssef1313** [comment]
That could be a bug with TextBox.InputScope. I'll take a look.

**Comment by Youssef1313** [comment]
That is an issue on Wasm also

**Comment by Youssef1313** [comment]
The problem here is that on Android, iOS, and Wasm, there is no keyboard of the desired behavior. Either we will need to make a fix specific to NumberBox to show the full keyboard (probably only when AcceptsExpression is true), or use less than ideal keyboards when TextBox's input scope is number.

Following is the behavior on Windows

![image](https://user-images.githubusercontent.com/31348972/216269459-9cf8e105-c212-452f-877f-9e58d88bf49d.png)

Note that the above behavior on Windows applies regardless of `AcceptsExpression`, but since we can't get the exact same keyboard for other platforms, we could use the full keyboard only when `AcceptsExpression` is true.
