### ISSUE TITLE
[Gallery][Android]Vibration- Phone is not vibrating when click on 'vibrate for 100ms' or 'vibrate for 1000ms' button.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11180]
### Current behavior

![android vibration issue](https://user-images.githubusercontent.com/74563602/216473106-aca20960-505e-4b3c-90f1-1582492bc7b7.png)

### Expected behavior

![iOS vibration correct](https://user-images.githubusercontent.com/74563602/216473124-e93fe070-5b5c-491c-bc6f-affc3dd84aac.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "Vibration" from the "Non UI Features" list.
4. Click 'vibrate for 100ms' or 'vibrate for 1000ms' button.
5. Notice that Phone is not vibrating.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by Youssef1313** [comment]
@sakshi173 Do you know if this issue is for the MonoAndroid build or the net6.0 build?

I suspect we are missing permissions here for net6.0 build:

https://github.com/unoplatform/Uno.Gallery/blob/0e6d474f11aab497f0d723f2528b2cd1fe51b1da/Uno.Gallery/Uno.Gallery.Mobile/Android/AndroidManifest.xml

But it is okay for the MonoAndroid project:

https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.Droid/Properties/AndroidManifest.xml

I think we should have a single `AndroidManifest.xml` and share the same permissions between both builds.
