### ISSUE TITLE
[Android] Project template does not build

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#11201]
### Current behavior

I wanted to try an Android build, downloaded the latest project template and created a solution [as per here](https://platform.uno/docs/articles/get-started-dotnet-new.html?tabs=windows) and got error below when building Android. Solution attached

Is that expected?

[Android.zip](https://github.com/unoplatform/uno/files/10611695/Android.zip)

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/216835582-63db0c51-9505-470e-b676-2395ec4ffd3c.png">

### Works on UWP/WinUI

None

### Environment

Other

### Affected platforms

Android

**Comment by Youssef1313** [comment]
@DierkDroth This is happening because you named the project `Android`, and so the generated namespace is called `Android`, so in the line `internal static Window MainWindow { get; private set; }`, `Window` is resolved to the namespace [`Android.Window`](https://learn.microsoft.com/en-us/dotnet/api/android.window?view=xamarin-android-sdk-13).

To resolve this, you can replace `Window` with `global::Microsoft.UI.Xaml.Window`.

In my opinion, it is not worth cluttering the template with fully qualified names, so I'm more with closing as by-design. But I'll let @jeromelaban decide.

The reason I prefer to close this by-design is that it is possible to always create such clashes. For example, if you named the project `Application`, now `Application` in `class App : Application` will get broken.

**Comment by DierkDroth** [comment]
Thanks for looking into @Youssef1313 

I will take it from there and will close the issue.
