### ISSUE TITLE
UWP could not creat envet

### ISSUE THREAD

**Issue by ZGHHGZ** [unoplatform/uno#11267]
### Current behavior

![image](https://user-images.githubusercontent.com/88225620/218032817-f8ded6ff-070a-48e1-85c3-e7500f9da088.png)
![image](https://user-images.githubusercontent.com/88225620/218033073-f7ac160b-cf86-4f02-90a2-d8fb1475181f.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.SourceGenerationTasks, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### Affected platforms

Windows

### IDE version

Visual  Studio 2022  17.5.0 Preview6.0

### Anything else we need to know?

I want creat event in UWP project

**Comment by Youssef1313** [comment]
Are you using a shared project?

**Comment by ZGHHGZ** [comment]
Yes

**Comment by ZGHHGZ** [comment]
When I double click UI in xaml desingner , visual studio tell me  that is error, it couldn't creat events, sometimes visual studio will breakdown when I double click。

**Comment by Youssef1313** [comment]
This is a problem on Visual Studio side. Not something that Uno controls. However, the new templates no longer use a shared project, so in the new templates you will be able to create the event normally.

**Comment by ZGHHGZ** [comment]
How can I use the new templates ？

**Comment by ZGHHGZ** [comment]
@Youssef1313  Is it the next version ？

**Comment by Youssef1313** [comment]
If you are creating a project from scratch, the latest `-dev` solution template packages should have the new project structure.

If you have an existing project, you probably need to manually migrate to the new structure.

@jeromelaban Do we have any documentation for moving from shared project to class lib?

**Comment by ZGHHGZ** [comment]
![image](https://user-images.githubusercontent.com/88225620/218083559-b9526da6-39da-4a4c-88fd-24dfe07f69ba.png)

**Comment by ZGHHGZ** [comment]
I couldn't find the latest -dev solution template packages . This is newest version(4.7.37) in Visual Studio 2022

**Comment by jeromelaban** [comment]
This is [indeed an issue](https://github.com/unoplatform/uno/issues/1348#issuecomment-520300471) on Visual Studio's side caused by Shared Projects that we cannot fix for UWP applications. It is resolved when building WinAppSDK applications, using our latest template.

If you want to stay on UWP, you may also try to create a cross-targeted library:
![image](https://user-images.githubusercontent.com/5839577/218092129-7050a4df-fc38-4ff8-916d-727debb5ba9c.png)
And move all the XAML files from the "shared project" to that new project, then reference it from the other heads.
