### ISSUE TITLE
Consider adding `System` as global namespace in templates

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#11759]
## What would you like to be added:

Add

```csharp
global using System;
```

In code or in .csproj to Uno app templates

## Why is this needed:

Currently Visual Studio sometimes tends to remove `using System` from files which don't use it. This OK until the user wants to `await` a `IAsyncAction`, which requires it. This often causes confusion for new users.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by Youssef1313** [comment]
We shouldn't include `global using System;` directly that way. Instead, we should just add `<ImplicitUsings>enable</ImplicitUsings>` to csproj, and the .NET SDK will include a bunch of global usings specified here:

https://github.com/dotnet/sdk/blob/3c9bbdac34172e57f23bb40d6f6ec27644ff89ff/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.Sdk.CSharp.props#L25-L34

**Comment by Youssef1313** [comment]
`ImplicitUsings` approach shouldn't be used because not only the .NET SDK uses this value, but also https://github.com/xamarin/xamarin-android/blob/main/src/Xamarin.Android.Build.Tasks/Microsoft.Android.Sdk/Sdk/AutoImport.props#L19-L23 which can easily cause type conflicts like https://github.com/unoplatform/uno.templates/issues/34

**Comment by MartinZikmund** [comment]
Found out the global using is already added in the new template, so closing this.
