### ISSUE TITLE
Referencing System.Reactive fails the build

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#11829]
I require System.Reactive v5.0.0 in my project, I added the nuget package in my "VewiModels" library and now I get this build error:

```
1>C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App available for the specified RuntimeIdentifier 'win10-arm'.
1>C:\Program Files\dotnet\sdk\7.0.200\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.FrameworkReferenceResolution.targets(448,5): error NETSDK1082: There was no runtime pack for Microsoft.WindowsDesktop.App available for the specified RuntimeIdentifier 'win10-arm-aot'.
```

I found that adding

```
<RuntimeIdentifiers>win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
```

**Comment by Youssef1313** [comment]
I wasn't able to reproduce. If there is a repro project, it would be good to start investigating.

**Comment by Youssef1313** [comment]
Note: This issue is only reproducible with `net5.0-windows10.0.19041` and later. I was using `18362` so that's why I couldn't reproduce earlier.

The problem with `System.Reactive` is that it has `Microsoft.WindowsDesktop.App` framework reference for `net5.0-windows10.0.19041`

The default runtime identifiers for WinUI are: https://github.com/microsoft/WindowsAppSDK/blob/ccc85853cd9d8305194ce0330ad384b5899752d7/dev/MRTCore/packaging/MrtCore.PriGen.targets#L122

and the supported runtime identifiers for `Microsoft.WindowsDesktop.App` are:

https://github.com/dotnet/installer/blob/0b8f0187eb580aede7dafcb5812e30884150d746/src/redist/targets/GenerateBundledVersions.targets#L271-L274

A possible workaround is to add `<DisableTransitiveFrameworkReferences>true</DisableTransitiveFrameworkReferences>` to csproj.

**Comment by igiona** [comment]
@Youssef1313 are you aware of a public issue at System.Reactive that can be tracked?
