### ISSUE TITLE
Uno Platform extension preventing VS Code tasks to run properly

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#12210]
### Current behavior

The new version of the Uno Platform extension is for some reason preventing the opening of the tasks. Also this breaks debug sessions that have nothing about XAML or Uno Platform stuff, what is very bad https://github.com/microsoft/vscode/issues/181844

With the uno platform extension enabled, opening the tasks to run does not work as expected:

https://user-images.githubusercontent.com/2633321/236973825-f6ef270d-1696-4557-80b3-8679e60ed03a.mp4

Disabling the uno platform extension, then the tasks are shown as expected:

https://user-images.githubusercontent.com/2633321/236973730-b70cef4b-da5e-4795-992d-e51999819e7a.mp4

### Expected behavior

The tasks list should be shown and not prevented to execute.

### How to reproduce it (as minimally and precisely as possible)

- Install the latest Uno Platform extension
- Open any workspace that has `.vscode/settings.json`
- Open the VS Code command pallet and execute the `Tasks: run tasks`

### Workaround

Rollback to Uno Platform `v0.8.1`

### Works on UWP/WinUI

None

### IDE

Visual Studio Code

### IDE version

1.78.0

### Relevant plugins

Uno Platform v0.9.4

**Comment by spouliot** [comment]
This does not seems to be a general issue

<img width="609" alt="Screenshot 2023-05-09 at 9 54 36 AM" src="https://github.com/unoplatform/uno/assets/260465/88da06eb-5857-43b0-ac4b-5970be8a0606">

since I get the list of tasks

<img width="604" alt="Screenshot 2023-05-09 at 9 59 59 AM" src="https://github.com/unoplatform/uno/assets/260465/b6a6c85c-f66e-4dab-ae14-e3c2329489fe">

I notice you're connected to WSL, right ? Does this also happens when you're not ?

Can you attach the logs from all (4) the `Uno Platform - *` outputs ?

**Comment by microhobby** [comment]
Hey @spouliot thanks for check this, but this was fixed from the VS Code side.
https://github.com/microsoft/vscode/issues/181844

**Comment by spouliot** [comment]
@microhobby it's a good, general fix for VSCode but if you still can provide some details I'd like to know/diagnose what happened with our extension - it definitively should not cause a timeout :) thanks!

**Comment by spouliot** [comment]
I have found the issue. It can also happen for debugging (non dotnet code) so VSCode fix is not a complete fix to the problem.
