### ISSUE TITLE
 [Overrides][PipsPager][Fluent] Overrides on the style of PipsPager do not work well

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#12496]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/90481654/336a77c4-eb4d-4b4e-bb80-69491f1b28a7)
![image](https://github.com/unoplatform/uno/assets/90481654/66cc528e-0a08-47af-9962-002d941dfdb2)
When overriding the style of the pipspager with static resources, as you can see in the first image, the selected pipspager has the correct colors while the other's didnt change. When you change the selection, none of the colors follow the override anymore. 

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/90481654/940a3618-f383-4a5e-bb2f-39c27d87146e)
It should be like on WinUI where the colors override are done, and stay overridden. 

### How to reproduce it (as minimally and precisely as possible)

Put that into the code 
```
<Page.Resources>
        <SolidColorBrush x:Key="PipsPagerSelectionIndicatorBackgroundSelected" Color="Red" />
        <SolidColorBrush x:Key="PipsPagerSelectionIndicatorForegroundSelected" Color="Pink" />
        <SolidColorBrush x:Key="PipsPagerSelectionIndicatorForeground" Color="Purple" />
        <SolidColorBrush x:Key="PipsPagerSelectionIndicatorBackground" Color="Blue" />

    </Page.Resources>


    <StackPanel HorizontalAlignment="Center"
				VerticalAlignment="Center">
        <PipsPager/>
    </StackPanel>
```
### Workaround

NA

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

For WASM
`<PackageReference Include="Uno.Wasm.Bootstrap" Version="8.0.0-dev.210" />`
`<PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.0-dev.210" />`
`<PackageReference Include="Uno.WinUI.WebAssembly" Version="4.10.0-dev.111" />`
`<PackageReference Include="Uno.WinUI.RemoteControl" Version="4.10.0-dev.111"/> `
`<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />`

On android: `<PackageReference Include="Uno.WinUI" Version="4.10.0-dev.111" />`

### Affected platforms

WebAssembly, Android, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

Version 17.6.0

### Anything else we need to know?

I will try on IOS later but it might take a while

**Comment by agneszitte** [comment]
(It is the same on iOS)
Still investigating

**Comment by agneszitte** [comment]
I made additional tests and I am still not able to find the root cause of the issue:
- Logic for the PipsPager control seems fine and following WinUI
- The proper resources are also present and following WinUI
- If I add in my sample page the same resources (same as the ones in [PipsPager.xaml](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/PipsPager/PipsPager.xaml) and [PipsPager_themeresources.xaml](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Microsoft/UI/Xaml/Controls/PipsPager/PipsPager_themeresources.xaml)), it is working correctly with the example overrides. 

See sample solution for the different tests
[PipsPagerOverride.zip (using latest packages **5.0.0-dev.1541**)](https://github.com/unoplatform/uno/files/12155759/PipsPagerOverride.zip)
