### ISSUE TITLE
[MPE][Wasm] Setting the `AutoPlay` property to false removes hides the MTC buttons

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#12535]
With this sample: https://playgroundcanary.z19.web.core.windows.net/#7486d066, setting the AutoPlay property to false sets the opacity of the MTC to 0, preventing the video from being played.

**Comment by Xiaoy312** [comment]
the key difference between having this bug manifesting and not, is the visual-state on MediaTransportControls:
- bugged: ControlPanelFadeIn|**Loading**||||NormalMode|PlayState|VolumeState|NonFullWindowState|RepeatNoneState
- working: ControlPanelFadeIn|**Normal**||||NormalMode|PlayState|VolumeState|NonFullWindowState|RepeatNoneState

`VisualState.MediaStates.Loading` is in charge of:
![image](https://github.com/unoplatform/uno/assets/2359550/d8328acc-6de2-4e80-a1fb-6700385000d2)
which is responsible for this issue

we got this state from `MediaPlaybackState.Opening`
^ we can possibly rule out the possibility of `PlaybackState` and its visual-state going out of sync, since everywhere when we `BindMediaPlayer()`, we do listen for on-changed and do a live update immediately (on [`dev/xygu/20230601/mtc-show-hide-behaviors`](https://github.com/unoplatform/uno/tree/dev/xygu/20230601/mtc-show-hide-behaviors) at least)
^ on skia, where this problem doesnt occur, the playback state is `Paused`

**Comment by BrianDT** [comment]
I believe this also occurs on iOS and on Android the transport controls are removed.
On iOS
![IMG_0001](https://github.com/unoplatform/uno/assets/4189260/c7b02e36-f6cf-4b6d-9bba-87f8da647c3a)

On Android
![IMG_0001](https://github.com/unoplatform/uno/assets/4189260/af1bd86d-ca69-4d17-9342-1e21beb93727)
