### ISSUE TITLE
[iOS, Android] DrawerControl.DrawerContent isn't set on mobile but works on win

### ISSUE THREAD

**Issue by Lee31416** [unoplatform/uno#12624]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/72167772/489c515a-1df1-4750-b5a6-9de02165d2a7)

On mobile we can see the overlay but the drawer content is nowhere to be found

### Expected behavior

![image](https://github.com/unoplatform/uno/assets/72167772/aee3995b-16a8-4b27-810f-a08e0ac9c94a)

On windows we can see that the drawer content is there 

### How to reproduce it (as minimally and precisely as possible)

1. Download the sample 
[SampleDrawerEdgeSwipe.zip](https://github.com/unoplatform/uno/files/11749761/SampleDrawerEdgeSwipe.zip)
2. Deploy the sample on windows 
3. Swipe with the mouse or click on the button to open the pane
4. Deploy on either ios or android
5. Swipe or click the button to open the pane and see that the content isn't there

### Workaround

None found

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

4.8.15

### Affected platforms

Android, iOS

### IDE

Visual Studio 2019

### IDE version

17.6.2

### Anything else we need to know?

Before we used a drawer control but we had issues with it so we switched to a split view but the native splitview doesn't have gestures so we took the DrawerSplitViewStylestyle and that's when the bug appeared. So maybe the combination of a drawer control inside a splitview is causing this issue.

**Comment by Xiaoy312** [comment]
The very same problem can also be produced with `XamlReader.Load`, hints that the problem is how we handles `{TemplateBinding}` or `{Binding RelativeSource={RelativeSource TemplatedParent}}`. However, it is impossible to trace-back under which control-template it was define under, as we can't just blindly navigate up by n-levels.
We will have to do as the linked issue suggested, to inject the relevant context/templated-parent during the xaml-source-generation or XamlReader-loading.
