### ISSUE TITLE
[Gallery][Wasm/Android/iOS]MediaPlayerElement , CompactOverlayButton is not similar to windows.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12650]
### Current behavior

![CompactButton](https://github.com/unoplatform/uno/assets/74563602/fef9ca3a-f903-4301-853b-7883de063d88)

### Expected behavior

Compact Overlay button should be similar to windows.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the fourth sample:
5. "MediaPlayerElement sample using customizable options"
6. Check AreTransportControlsEnabled and IsCompact and uncheck all the other options
7. Observe that IsCompact Overlay button is different from Windows.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by nguyeenvy** [comment]
This button image is actually a glyph icon in the code : Glyph="&#xE8B9;". I think, depending on the platform, this glyph icon translates into different button images.

In the [figma](https://www.figma.com/file/trM3i5qUPmFBcnxWXXmnuF/branch/LXYP010W9oJANcAFpbDbef/Uno-Platform-Material-Toolkit?type=design&node-id=418-11559&mode=design&t=tDrOFqRd1nZmqc5o-0) design, there isn't an icon vector for the CompactOverlayButton. 

Is there a way for the figma to have the other button's vectors so that all the glyph icons can simply be replaced with an svg path? @NVLudwig 

Any comments @Marc-Antoine-Soucy ?

**Comment by NVLudwig** [comment]
I think I see a path forward here. One question is this a toggle where one icon is replaced by another when checked or unchecked? @nguyeenvy

**Comment by nguyeenvy** [comment]
@NVLudwig No, this is not a toggle. The icon remains the same whether it is checked or unchecked.

**Comment by MartinZikmund** [comment]
The visual discrepancies are caused by the fact that the Windows app is running on Windows 10 and hence it uses the old Segoe MDL2 Assets, which have different iconography and sharp edges. This is how MPE Transport Controls look on Windows 11:

<img width="604" alt="image" src="https://github.com/unoplatform/uno/assets/1075116/40582071-56f4-420e-b776-ef04f46b7717">

<img width="561" alt="image" src="https://github.com/unoplatform/uno/assets/1075116/26630e47-01e3-4476-b916-774bcf6c16e4">

So this is technically not an issue and I think it can be closed. @agneszitte @nguyeenvy @NVLudwig

**Comment by jeromelaban** [comment]
Let's close then.
