### ISSUE TITLE
[All platforms] [Chip] UniformGridLayout inconsistent spacing between Chips and content is truncated

### ISSUE THREAD

**Issue by rajamatt** [unoplatform/uno#12820]
### Current behavior

When using the ItemsRepeater with a UniformGridLayout and the ItemTemplate being a Chip, the spacing between Chips is not always the same.

Also, sometimes the Content of the Chip is truncated, even before selecting the Chip. When selecting a Chip, the cut off gets even worse.

Here is a minimal sample repro app with three cases:

1) ItemsRepeater with UniformGridLayout (weird chips)
2) ItemsRepeater with StackLayout (chips work fine)
3) Chips without ItemsRepeater (chips work fine)

[SampleChipApp.zip](https://github.com/unoplatform/uno/files/12147483/SampleChipApp.zip)

![chips_repro_app](https://github.com/unoplatform/uno/assets/70542961/5e626baf-ac65-403f-8993-d8423dc5b601)

### Expected behavior

The Chips in an ItemsRepeater with UniformGridLayout should all have the same spacing between them & not have their content be truncated (if the content size is reasonable of course).

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.Extensions => 3.0.0-dev.1939
Uno.WinUI => 5.0.0-dev.1230
Uno.Toolkit => 4.0.0-dev.27

Microsoft.WindowsAppSDK =>  1.2.230313.1
Microsoft.Windows.SDK.BuildTools => 10.0.25387-preview

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows), Windows

### IDE

Visual Studio 2022

**Comment by rajamatt** [comment]
@agneszitte It seems like the issue is with the UniformGridLayout, since it works fine with a StackLayout. So not sure if this is fixable in uno. What do you think? 

I'm currently looking for workarounds for this issue (obviously some naïve stuff like setting a MinWidth on the Chip, but I can check for better solutions than that)

**Comment by agneszitte** [comment]
@Xiaoy312, @kazo0, @MartinZikmund, @carldebilly, @dr1rrb, @Youssef1313 
Does this issue ring a bell to you?

**Comment by dr1rrb** [comment]
Nope never saw that 😕

**Comment by agneszitte** [comment]
(cc @jeromelaban for triage and priority)

**Comment by rajamatt** [comment]
@dr1rrb I did forget it, here you go! Replaced it in the issue as well

[SampleChipApp.zip](https://github.com/unoplatform/uno/files/12147493/SampleChipApp.zip)

**Comment by dr1rrb** [comment]
@rajamatt Unfortunately I won't be able to fix this issue. Since it's the same behavior as Windows, Uno's behavior is considered as correct, especially since I think that the `UniformGridLayout` is not the right layout for what you are trying to achieve.

The `UniformGridLayout` has been designed to render large number of items (UI virtualized) which are expected to all have the same size (uniform grid). ROUGHLY In order to render a large amount of items, on first measure it tries to determine the right size for items and will then use it for all items. Doing this it's able to determine the position of any item/index so while scrolling it is able to render only few items instead of measuring each item.

The right layout seems to be [`ColumnMajorUniformToLargestGridLayout`](https://learn.microsoft.com/en-us/windows/winui/api/microsoft.ui.xaml.controls.primitives.columnmajoruniformtolargestgridlayout?view=winui-2.8) (which is not virtualizing). Unfortunately when I tried it in your sample it was not working even on Windows but anyway it has not been ported in uno yet https://github.com/unoplatform/uno/issues/12996.

Regarding your sample, I think that you have 3 options:
1. Keep the `UniformGridLayout` and try to find a compromise:
First on your `Chip`  set the `HorizontalAlignment="Stretch"` (this is why you have strange spacing between items), then on the layout either:
    * Set `ItemsStretch="Fill"` and valid a `MaximumRowsOrColumns`
    * Set the `MinItemWidth`
2. Import (and fix?) the `ColumnMajorUniformToLargestGridLayout` (https://github.com/unoplatform/uno/issues/12996)
3. Implement your own `Layout` (it does not have to be virtualizing as I think that you have a limited amount of chips - basically this would be a lighter version of the `ColumnMajorUniformToLargestGridLayout` specialized for you case)
4. Use a simple `ItemsControl` with a `WrapPanel` (not virtualizing neither)

**Comment by agneszitte** [comment]
cc @kazo0 , @Xiaoy312
