### ISSUE TITLE
problems with RowVirtualization in DataGrid

### ISSUE THREAD

**Issue by c-npolyak** [unoplatform/uno#12895]
### Current behavior

There is a problem with scrolling a DataGrid. If virtualization is on (default) the rows are being repeated both in Desktop and WASM WinUI version. Can someone help? I need to keep the virtualization. 
Here is a sample:
![image](https://github.com/unoplatform/uno/assets/127349248/37d89825-4506-4696-bc5a-cb60c9458aa1)
if I scroll down, the Utilities row will re-appear below (though it was not there):
![image](https://github.com/unoplatform/uno/assets/127349248/0ed1f4ed-7c93-4bf6-9034-a9b3dbcf6e0e)

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment]
Thanks for the report. It looks like the issue is present on both platforms making it a generic issue, not an Uno Platform issue, and this component is officially maintained by the Community Toolkit team. It would be best to report the issue with a repro sample to the [Community Toolkit repository](https://github.com/CommunityToolkit/WindowsCommunityToolkit).
