### ISSUE TITLE
SymbolIcon still doesn't work on Android and is clipped on WebASM

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#1332]
## Current behavior
The SymbolIcon does not Show correctly on Android as stated in #273.

## Expected behavior
The SymbolIcon renders exactly as it does with UWP.

## How to reproduce it (as minimally and precisely as possible)
Simply create a new Uno-App with the VS-templates and add the following line to the MainPage.xaml after the TextBlock with "Hello World" in it:

```<SymbolIcon Symbol="Add"/>```

This renders the SymbolIcon with the "missing Image" as seen int #273.

## Environment
Windows

Nuget Package: v1.45

Package Version(s): VS-PlugIn v1.45.0.1862

Affected platform(s):
- [?] iOS
- [X] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [X] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
howdy @TopperDEL, I can confirm on Android that this has regressed. `SymbolIcon` works fine on iOS but is cropped on WASM when using the latest -dev package aka master. It should be relatively to resolve so let's ear mark this one as `help wanted`. 

Would you be interested in sending in a PR? I'm more than happy to pair-program with first time contributors via skype/zoom/hangouts and walk people through the codebase.

<details>
<summary>screenshots</summary>

# android - api27

![image](https://user-images.githubusercontent.com/127353/62261040-5ef85c00-b457-11e9-85f8-1465cd646a1f.png)

# ios

![image](https://user-images.githubusercontent.com/127353/62261017-4be58c00-b457-11e9-96ba-ddd8c440a316.png)

# wasm

![image](https://user-images.githubusercontent.com/127353/62261098-80f1de80-b457-11e9-99a7-d95a8823251c.png)


</details>

# next steps
- resolve defect on Android and WASM
- add more `SymbolIcon` scenarios to `SamplesApp` so that screenshot regression testing catches this in the future
- enable automated UI testing for these scenarios

# related files in the codebase
- https://github.com/unoplatform/uno/commit/45deceda5e541b454b1755cd8ddbb226796fc202
- https://github.com/unoplatform/uno/tree/master/src/Uno.UI/UI/Xaml/Controls/SymbolIcon

**Comment by jeromelaban** [comment]
The Wasm issue may be related to #693, where fonts are measured incorrectly as they are loaded lazily by the browser. For Android, this may be related to the missing Symbol font in the default template.

**Comment by TopperDEL** [comment]
Sorry, did not get any GitHub notifications - therefore my late Reply. Need to check my spam-Folder. :)

Thank you for your offer to help me with a first PR on this one @ghuntley! Unfortunately I don't know where I can cut the time off, currently. I'm happy when I just can concentrate a Little bit on my private Project, though I would really love to help you out here (and learn from you!).

For this case I have to reject, then, and feel very sorry About it!

**Comment by ghuntley** [comment]
nps, open-offer if your situation changes or to anyone else.

**Comment by pkar70** [comment]
I looked throu source, and although I'm not expert in this code, maybe problem is:

https://github.com/unoplatform/uno/blob/master/src/Uno.UI/FeatureConfiguration.cs
line 203
#if !ANDROID
shouldn't it be:
#if !__ANDROID__ 
?

**Comment by TopperDEL** [comment]
On Android it is working now as expected - so from my Point of view this one can be closed.
