### ISSUE TITLE
[Skia][ToggleSwitch] Shadows/Material/Fluent ToggleSwitch with animation issues

### ISSUE THREAD

**Issue by eriklimakc** [unoplatform/uno#13354]
### Current behavior

It's a bit harder to reproduce the issue on Fluent ToggleSwitch, but you can see it in the video below:

1st - With Neumorphic style
2nd - Material
3rd - Fluent

https://github.com/unoplatform/uno/assets/114886335/4c0fe06a-baf6-4d86-a72d-f2e192695fb1

### How to reproduce it (as minimally and precisely as possible)

Repro Uno App with latest Uno dev packages -> [ToggleSwitches Repro.zip](https://github.com/unoplatform/uno/files/12410224/ToggleSwitches.Repro.zip)

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.WinUI 5.0.0-dev.2147

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by agneszitte** [comment]
fyi @jeromelaban, @Youssef1313

**Comment by Youssef1313** [comment]
This feels like a race condition introduced by https://github.com/unoplatform/uno/pull/13324, but I don't see why https://github.com/unoplatform/uno/pull/13324 is wrong. I mean, it feels like https://github.com/unoplatform/uno/pull/13324 reveals an animation problem?

So here is what I think is happening.
The Storyboard has multiple children animations. The first one is `RepositionThemeAnimation`.

When the storyboard runs, it will set `_runningChildren` to zero, and then gradually start every children, and increment `_runningChildren` after each child run.

https://github.com/unoplatform/uno/blob/80a5d5d5c6c90876c707305789df6806aff00584/src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs#L117-L130

The problem with that is, if the first animation completed very fast, it will raise that it has completed, then we get here:

https://github.com/unoplatform/uno/blob/80a5d5d5c6c90876c707305789df6806aff00584/src/Uno.UI/UI/Xaml/Media/Animation/Storyboard.cs#L335

And then, `_runningChildren` is zero because we decremented, and the storyboard thinks it has completed. But it hasn't actually yet started its other children.

I we shouldn't be setting `_runningChildren` to zero and increment one by one. Instead, we should set it to the children count.

**Comment by agneszitte** [comment]
@eriklimakc, @kazo0 I think we can remove the workaround in place for this issue since now it is now fixed in Uno
