### ISSUE TITLE
Samples Only Run in Edge

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#1337]
I can only run samples, and any Uno Wasm apps in Edge. 

Note: I am opening the html file directly - not serving it up on local host. Is this an issue?

Edge example:
![image](https://user-images.githubusercontent.com/16697547/62429238-87ca6b00-b74f-11e9-8c7f-b6d5038fb5f8.png)

Chrome example (after waiting a while)
![image](https://user-images.githubusercontent.com/16697547/62429242-97e24a80-b74f-11e9-863f-dad74c4771e9.png)

Firefox example (after waiting a while):
![image](https://user-images.githubusercontent.com/16697547/62429245-b0eafb80-b74f-11e9-930c-afcebd5818cd.png)

## On which page?

Camera app

## What's wrong?

Gets stuck on loading page

## Any feedback?

This problem occurs with any Uno wasm app. If you follow [these instructions](https://github.com/MelbourneDeveloper/RestClient.Net#in-browser-wasm-support-with-uno-platform---new) you can see the same issue.

If I need to serve this up on localhost, please let me know. Is this a security hole in Edge?

**Comment by davidjohnoliver** [comment]
Hi Christian, 'security hole' might be too strong but essentially yes, this is because Edge is more permissive than the other browsers.

If you look at the console output when you try to load the html directly in Chrome, you can see that you're getting CORS errors trying to cross-load the `mono.wasm` runtime as a local file:
![image](https://user-images.githubusercontent.com/8270914/62586487-e694ff00-b88b-11e9-9fde-c5fcb8353b7b.png)

The fix is indeed to serve on localhost. This is as easy as hitting Ctrl+F5 from Visual Studio with the WASM sample active (assuming you have [the right VS workloads](https://platform.uno/docs/articles/get-started.html) installed).
