### ISSUE TITLE
Implement `UseLayoutRounding`

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13380]
### Current behavior

```csharp
    public class MyFrameworkElement : FrameworkElement
    {
        protected override Size MeasureOverride(Size availableSize)
        {
            return new Size(16.1, 17.5);
        }
    }
```

```xml
<local:MyFrameworkElement x:Name="myfe" />
```

On loaded, check myfe.DesiredSize, on Windows it's (16, 18). This doesn't match Uno.

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
This is because Windows applies layout rounding, while we don't on any platform _except_ for partially on Skia - https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.uielement.uselayoutrounding?view=winrt-22621 . 

Implementing this across all targets properly would align us much better with Windows and especially in case of Skia we definitely should apply it uniformly, as failing to do so causes weird issues like the dancing scrollbars on popups and `TextBox`

**Comment by Youssef1313** [comment]
Oh, so it's not a simple rounding as I thought as we need to handle the property changes too. There might also be other complications.

**Comment by MartinZikmund** [comment]
@Youssef1313 Yes indeed. And probably the `UseLayoutRounding` property is also inherited, so if you set it to false on a parent, it also applies to children (although that is just my guess now)

**Comment by Youssef1313** [comment]
Also a note when implementing this, I think `TextBlock`s should ceil its measurements.

On Windows, the text measurements are **always** integers per my testing. But that is not the case on the other platforms we have.

**Comment by Youssef1313** [comment]
Duplicate of #12082
