### ISSUE TITLE
[iOS] `PersonPicture` does not load the picture when the source is delayed

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#13543]
### Current behavior

![image](https://github.com/unoplatform/uno/assets/90481654/f4e9086d-32db-4af6-addf-a59d9a636ade)
The image becomes gray after the source is set. 

### Expected behavior

Just like on windows, the image should load properly
![image](https://github.com/unoplatform/uno/assets/90481654/4ac0d6b1-8e47-4dfc-8eba-531c942a9f06)

### How to reproduce it (as minimally and precisely as possible)

In the xaml:

```
<PersonPicture ProfilePicture="{Binding ImagePath}"
			 Height="100"
			 Width="100"
			 HorizontalAlignment="Center"
			 VerticalAlignment="Center" />
```

In the codeBehind:
```
public MainPage()
{
	this.InitializeComponent();
	_ = SetImagePathWithDelay();
}

public string ImagePath { get; } = "ms-appx:///BasicApp/Assets/james_bondi.png";

private async Task SetImagePathWithDelay()
{
	await Task.Delay(1000);
	DataContext = this;
}
```

[BasicApp.zip](https://github.com/unoplatform/uno/files/12542519/BasicApp.zip)

### Workaround

You can use an Images with a border or grid around it to have a similar final result as the PersonPicture. 

### Works on UWP/WinUI

None

### NuGet package version(s)

```
<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.32" />
<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.2437" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageReference Include="Uno.Extensions.Logging.OSLog" Version="1.6.0" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.2437" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.2437" Condition="'$(Configuration)'=='Debug'" />
```

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.6.5

### Anything else we need to know?

It looks the same as if you put the source as null.

**Comment by agneszitte** [comment]
@jeromelaban, @MartinZikmund we need to review the priority of this issue please (archived at the moment), not able to restore it right now on my side

**Comment by agneszitte** [comment]
@Marc-Antoine-Soucy can you quickly re-test your sample app with latest packages to let us know if it is still happening please

**Comment by Marc-Antoine-Soucy** [comment]
I just tested the sample app and the issue still happens.

**Comment by kazo0** [comment]
@Youssef1313 should this be fixed? We seem to still be experiencing it here: https://github.com/unoplatform/uno.chefs/pull/960

**Comment by Youssef1313** [comment]
Not sure about this one as it seems iOS-specific. cc @ajpinedam

**Comment by ajpinedam** [comment]
Thanks @Youssef1313 i will check it out.

**Comment by ajpinedam** [comment]
The issue is related to how we apply the background to a Shape in iOS.

For Context: PersonPicture uses a Shape, and the Photo/Image is applied as the background (Fill) of this Shape.

For desktop targets, for example, we set the Brush as it is, and the Brush is responsible for rendering the associated image (ImageBrush). We can see that here: [Shape.Skia.cs#L60](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Shapes/Shape.skia.cs#L60)

For iOS, the process is a bit different. We use ImageBrush and open the associated image to create a Layer on the Shape. This means that for iOS, we need the image to be opened and available when we create this Layer. 

Continuing on iOS, when we change the VisualState to `Photo` on the PersonPicture control right after we had set the `Fill` property we don't get enough time (ms) for the Image to be available when we get here: [Shape.iOSmacOS.cs#L86](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs#L86) making this validation to fail and the `PersonPicture.Shape` defaulting to `fillColor = Colors.Transparent;`

Still on iOS, the validation fails on this method: `TryCreateImageBrushLayers()` which is also in the [Shape.iOSmacOS.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Shapes/Shape.iOSmacOS.cs#L164) file 

This method looks like this:

```csharp
private bool TryCreateImageBrushLayers(ImageBrush imageBrush, CAShapeLayer fillMask, out CALayer imageContainerLayer)
{
	if (imageBrush.ImageSource == null 
	      || !imageBrush.ImageSource.TryOpenSync(out var imageData)
              || imageData.Kind != ImageDataKind.NativeImage)
	{
		imageContainerLayer = default;
		return false;
	}
	
	// More code below here but not relevant 
 }
```

The failing condition is: `ImageSource.TryOpenAsyn()` , which will return the already loaded image

```csharp
internal bool TryOpenSync(out ImageData image)
{
	if (_imageData.HasData)
	{
		image = _imageData;
		return true;
	}
	if (IsSourceReady && TryOpenSourceSync(null, null, out image)) 
	{
		return true;
	}

	image = default;
	return false;
}
```

Note: That line `if (IsSourceReady && TryOpenSourceSync(null, null, out image)) ` does nothing there, so we should probably just remove it. `IsSourceReady` is always false, and `TryOpenSourceSync()` has no implementation.


So here we could try re-opening the Image using the `Open` method of the `ImageSource` but since we had already requested that image, I understood the best choice was  "waiting".

That's why the proposed solution on PR https://github.com/unoplatform/uno/pull/18587 was only for iOS to listen to the image loaded from the PersonPicture. Once that image is available, we continue with the process.

cc: @jeromelaban  @Youssef1313 @MartinZikmund, your thoughts and input are appreciated.

**Comment by MartinZikmund** [comment]
The open/load area of `ImageSource` needs a significant refactoring overall, as the readability is very hard, taking into account each platform does things completely differently. That being said, we should probably find a way to adjust this at the `ImageSource` level itself...
