### ISSUE TITLE
SetVirtualHostNameToFolderMapping not implemented for iOS and Android for WebView2

### ISSUE THREAD

**Issue by GabrielChouinardLetourneau** [unoplatform/uno#13605]
### What would you like to be added

At the moment, `SetVirtualHostNameToFolderMapping` is not implemented for Android and iOS for `WebView2` as seen in the screenshots here. It comes from `CoreWebView2` to be more precise.

![image](https://github.com/unoplatform/uno/assets/37672082/5c81f919-ebb8-4b58-bd54-9e9c61b42fed)

![image](https://github.com/unoplatform/uno/assets/37672082/47d5d368-f0a0-4cc7-ac36-6773562cf523)

### Why is this needed

We need it for the resolution of the URL of a local file (index.html) and the subsequent navigations to the `css`, `js` and font files inside the `HTML` file.

### For which platform

Android, iOS

### Anything else we need to know?

@Guidemarcus

**Comment by MartinZikmund** [comment]
For the issue with larger resource rendering the reason is most likely the use of `window.chrome.webview.postMessage` - this is a Windows `WebView2`-specific API. This means when JS encounters it, it fails completely and nothing is rendered. Sending messages from JS needs to be implemented in platform-specific way - see https://platform.uno/docs/articles/controls/WebView.html#javascript-to-c-communication . I will continue working on a rudimentary support for the folder-based rendering. The JS to C# communication will need to be adjusted this way in both cases though.

**Comment by jeromelaban** [comment]
Implemented in https://github.com/unoplatform/uno/pull/13656
