### ISSUE TITLE
[Gallery-5X][Skia.Gtk]Image-sample page is fully blank, and the description for Image is overlapping with header name.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13642]
### Current behavior

![Skia Image issue](https://github.com/unoplatform/uno/assets/74563602/8f5a690f-7a84-4647-a09c-daa7a0cf5047)

### Expected behavior

![Skia Image correct](https://github.com/unoplatform/uno/assets/74563602/56d728bf-1421-4b30-87bd-104fc0c7bd3d)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Image" from the "UI Component" list.
4. Notice that sample page is fully blank, and the description for Image is overlapping with header name.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by ramezgerges** [comment]
This seems to be a problem with loading assemblies. The svg image throws an exception, which breaks the layout cycle for the rest of the sample.
![image](https://github.com/unoplatform/uno/assets/66218781/f1724ec4-eac8-416e-ba29-9d2b51d6ba68)

**Comment by Youssef1313** [comment]
The problem here is that we are declaring `Svg.Skia` as a dependency of `Uno.WinUI.Svg` only for `netX.0-android`, `netX.0-ios`, and `netX.0-maccatalyst`.

We don't declare the dependency for `netX.0` because that will cause it to be pulled unnecessarily for Wasm.

The cleanest way to fix this will be when `netX.0-browser` is supported.

For now, it's required that Skia projects add the package manually. The interesting issue here is that the build should actually fail due to this target:

https://github.com/unoplatform/uno/blob/bbdbefbcf3618610a4eb80e014f2ddca96f97c8d/src/AddIns/Uno.UI.Svg/buildTransitive/Uno.UI.Svg.targets#L9

I'll investigate why this target didn't fail the build.

**Comment by Youssef1313** [comment]
The package is actually referenced already in

https://github.com/unoplatform/Uno.Gallery/blob/c1a5b9db263ceab86cfdbc8ab00c36aa84f47102/Uno.Gallery/Uno.Gallery.Skia.Gtk/Uno.Gallery.Skia.Gtk.csproj#L17

Interesting...

**Comment by sakshi173** [comment]
Verified issue is fixed, closing it.
