### ISSUE TITLE
Re-enable AAPT2 in the Samples and the Uno Solution Template

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#1382]
## Current behavior

We disabled AAPT2 in https://github.com/unoplatform/uno/issues/1186 and https://github.com/unoplatform/uno/issues/1364 because of https://github.com/xamarin/xamarin-android/pull/3327

## Expected behavior

When VSWIN ships https://github.com/xamarin/xamarin-android/pull/3327 we need to re-enable AAPT2 for:
- The Android head of the SamplesApp
- The Android head generated by the Uno Solution Template

## Environment

Nuget Package: master

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

Opening as a help wanted as the complexity is low and a good candidate for someone's first pull-request to the project. The following article is a good read about the differences between AAPT1 and AAPT2: https://connortumbleson.com/2018/02/19/taking-a-look-at-aapt2/

**Comment by MatFillion** [comment]
I tried using aapt2 since https://github.com/xamarin/xamarin-android/pull/3327 was merged and released.
I've set `<AndroidUseAapt2>true</AndroidUseAapt2>` instead of false but issue still occurs.

I'm on VS2019 16.4 and Xamarin.Android 10.1.1.0.

The fix was released in VS2019 16.3 and Xamarin 10.0.0.43 according to this reply https://github.com/xamarin/xamarin-android/pull/3327#issuecomment-534840419

**Comment by MatFillion** [comment]
Maybe the name is really invalid though, file failing is repos\App7\App7\App7.Shared\Assets\Square44x44Logo.targetsize-24_altform-unplated.png : error APT0003: Invalid file name: It must contain only [^a-zA-Z0-9_.]+.

That asset probably belongs in the UWP head and not in the shared project.
