### ISSUE TITLE
Cannot find guidance for running Wasm in IIS

### ISSUE THREAD

**Issue by wallyh010** [unoplatform/uno#1423]
- what version of uno and what platforms you are using it with?
latest pre-release version
- what do you like?
ease of creating UI
- what is lacking?
cannot find reliable guidance for running in IIS (not express)

**Comment by ghuntley** [comment]
Howdy @wallyh010, thanks for the feedback. Wondering if you have come across and read https://github.com/unoplatform/Uno.Wasm.Bootstrap#unowasmbootstrap?

**Comment by wallyh010** [comment]
Realized that Visual Studio was adding a web.config file to the root of project MyProject.Wasm.  This web.config file included "IISSupport" launcher commands.  
Updated my IIS web app to point to : Source\MyProject\bin\Debug\netstandard2.0\dist.
Now if I can just figure out where and how to access a configurable value for a BaseURL used to communicate with a REST API service. Submitted a different ticket for this question.

**Comment by jeromelaban** [comment]
Note for contributors:

The documentation for this should be located in https://github.com/unoplatform/uno/blob/master/doc/articles/how-to-host-a-webassembly-app.md.

**Comment by xperiandri** [comment]
The issue is that the publish command does steps for .NET Core (DLLs) but not WASM specific (`index.html`, etc.).
As far as I understand the contents of the `publish` folder must match the content of the `dist` folder.

I've just copied `...\<project>\.vs\<project>\config\applicationhost.config` to `...\<project>\<project>.Wasm\bin\Debug\netstandard2.0\dist\`
Then changed path in it 
``` XML
    <site name="<project>" id="2">
        <application path="/" applicationPool="Oiler.Wasm AppPool">
          <virtualDirectory path="/" physicalPath="..\<project>\<project>.Wasm\bin\Debug\netstandard2.0\dist\" />
        </application>
        <bindings>
          <binding protocol="http" bindingInformation="*:9061:localhost" />
        </bindings>
      </site>
```
And site launches pretty well using `issexpress.exe /config:"...\<project>\<project>.Wasm\bin\Debug\netstandard2.0\dist\applicationhost.config`

@jeromelaban can someone fix the publish so that it matches the dist artifacts?
