### ISSUE TITLE
Uno platform and Machine Learning

### ISSUE THREAD

**Issue by VGFP** [unoplatform/uno#1424]
## What would you like clarification on:

Does WebAssembly supports machine learning models? I know that UWP supports ONNX but is it going to work on WebAssembly? I have also a similar question: adding models to iOS and Android is the same as on Xamarin or are there any differences? It would be nice to have that clarified in your docs.

## Concern?

- [ ] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Publishing your application
- [ ] Support

## For which Platform:
- [ ] Android
- [ ] iOS
- [ ] WebAssembly

**Comment by ghuntley** [comment]
Howdy @vgfp, let's see if I can help you out. First up I need to clarify what the the Uno Platform is and is not. It's best to think of Uno as a user interface bridge that allows WinUI/UWP-based code (ie. Windows.UI.Xaml aka C# and XAML) to run on iOS, Android, and WebAssembly. 

![](https://s3.amazonaws.com/uno-website-assets/wp-content/uploads/2019/08/21141002/diagram.png)

Libraries for Xamarin iOS and Xamarin Android typically work with Uno because on iOS and Android, the Uno Platform relies extensively on the Xamarin Native stack. Thus Azure cognitive services should just work.

On WebAssembly, the Uno Platform relies directly on the Mono-Wasm runtime. Currently there is no way for library .NET authors to target WebAssembly so you would need to compile the Azure Cognitive Services SDK from source.

UWP applications that use the `Windows.AI.MachineLearning` APIs will not work on WebAssembly, Android or iOS however. It would be possible to build an application that supports ONNX with the Uno Platform but you'd need to use an abstraction such as Azure cognitive services or author your application in such a way that:

- on UWP you use the `Windows.AI.MachineLearning` APIs
- on iOS you'd use the CoreML APIs
- on Android you'd use the NNAPI APIs.
- on WebAssembly you'd use ONNX.js and bridge communication between WebAssembly/JavaScript.

As for your question about WebAssembly, it's best to think of WebAssembly as a portable compilation target which allows code to either run in the browser, as desktop and server-side applications. 

Nearly anything, can run in WebAssembly - https://win95.ajf.me/win95.html

I hope this answers a few questions.
