### ISSUE TITLE
Build issues in wasm

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#14259]
@Youssef1313 I ran more tests: the parameter you suggested resolved the issue on building on my local machine as well as on GitHub. Thanks

However, now there is the next problem: I found that in the build there now is created a subfolder `wwwroot` which holds important files (like `index.html`) and which was not there before. In fact, all the files and folders in that new `wwwroot` had been one level up before. This new logic screws up my complete build/deply/run logic and makes my product unusable.

How could that unwelcome change be reverted and the `wwwroot `subfolder be eliminated?

_Originally posted by @DierkDroth in https://github.com/unoplatform/uno/issues/14242#issuecomment-1792197236_

**Comment by jeromelaban** [comment]
@DierkDroth make sure to keep issues on topic, it's easier to track. 

If you can provide a repro for the issue you're seeing, it will help.

**Comment by DierkDroth** [comment]
@jeromelaban obviously it would be close to impossible to break down my existing project for a repo. Also, it just would demonstrate the problem which I already described (please let me know if it's not clear what I mean) and hence would be a waste of effort.

So the question to UNO rather is: is it a know 'feature' of `Uno.Wasm.Bootstrap 8.X` that the relevant files now are in a `wwwroot `subfolder and no longer 'top level'. And if so, how that could be reverted to the prior behaviour?

Also, I'm not sure if it helps but I attached my WASM project file which works no problem with the prior `Uno.Wasm.Bootstrap`.

[Unusual.Wasm.zip](https://github.com/unoplatform/uno/files/13249950/Unusual.Wasm.zip)

**Comment by jeromelaban** [comment]
It is always possible to create a repro of an issue so that it can be properly fixed. If we don't have a way to validate that what we fixed is actually fixing your problem, we won't be able to fix it.

The behavior you're describing is not known at this time, and a repro will show what it is.

**Comment by DierkDroth** [comment]
@jeromelaban I'm just getting nowhere with the quest here ... and I have to say it's frustrating to encounter these roadblock on every major UNO upgrade.

Here is the latest fail which I can't resolved after having spent a few more hours:
- I'm trying to setup a repo as per your request above and followed [these instructions](https://platform.uno/docs/articles/get-started-dotnet-new.html?tabs=net7%2Cwindows) (as always on every repo)
- next I updated the Uno.Wasm.Bootstrap(.DevServer) references to V8.X
- next I changed the RELEASE config of the WASM project to match what I'm having in my LIVE project
```
    <DefineConstants>$(DefineConstants)</DefineConstants>
    <WasmPWAManifestFile>manifest.json</WasmPWAManifestFile>
    <WasmShellWebAppBasePath>/app/wasm/Latest/</WasmShellWebAppBasePath>
    <UnoXamlResourcesTrimming>true</UnoXamlResourcesTrimming>
    <WasmShellMonoRuntimeExecutionMode>InterpreterAndAOT</WasmShellMonoRuntimeExecutionMode>
    <WasmShellILLinkerEnabled>true</WasmShellILLinkerEnabled>
```
... I had to add a manifest.json file which I simply copied from my LIVE project
- I added a make.bat file to build the WASM project (please see WASM project folder)
- now I'm running into build errors as per sceenshot below
<img width="867" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/74228e72-5cb2-45d6-ba9b-7f34b20e1246">
BINLOG + project attached below
[msbuild.zip](https://github.com/unoplatform/uno/files/13253976/msbuild.zip)
[wwwroot.zip](https://github.com/unoplatform/uno/files/13254018/wwwroot.zip)

As always I'm vested to help UNO to make progress, but I now needed a clear and helping guidance to see the light at the end of the tunnel. 
Thanks for your understanding

**Comment by jeromelaban** [comment]
Thanks for the repro. It's generally not a good idea to create a repro with a significant name like `wwwroot`, like would a project called `global` would fail.

About the issues you're facing, as frustrating as it can be, this is something that is happening with **any project**. We're not in your project and we cannot possibly cover every possible scenario that may happen for everyone.

That's why we're providing intermediate builds for everything, and if you want to avoid getting stuck, we suggest that you regularly validate your project against preview builds.

We're using this process against ourselves in the form of "canary builds" that build projects with everything latest in order to catch errors or issues as soon as they occur. If you're searching to implement this process, you can dig into the [uno playground](https://github.com/unoplatform/Uno.Playground) for an example.

Regarding your sample, the issue is only caused by the comments in the json file (It's an issue, let's track in https://github.com/unoplatform/uno.resizetizer/issues/191). Remove them and it will build properly. I'm not seeing any `wwwroot` folder in the published output, though so it's not reproducing the issue. Can you try adding some more files?

**Comment by DierkDroth** [comment]
@jeromelaban hah ... I just reproduced it.

Please see screenshot below
<img width="968" alt="image" src="https://github.com/unoplatform/uno/assets/26179242/969a8f7b-d0e5-4ff7-94fe-b98d34839707">

Here is the naked project again (I had to strip obj/bin folders, since this blows up the ZIP folder size). You can reproduce by running the make.bat in the WASM project folder. Please let me know if it's not reproduce for you. Thanks

[wwwroot.zip](https://github.com/unoplatform/uno/files/13254454/wwwroot.zip)

BTW, as you know I tested out latest UNO build many times. I just don't have the bandwidth to test every changes which is coming in the various different packages to see if they might impact me in future...

**Comment by jeromelaban** [comment]
Thanks for the update.

I see what you mean by the `wwwroot` folder. This is the expected behavior, aligned with what `dotnet publish` does with Blazor. We will not be altering this behavior and you can publish the `wwwroot` folder instead of the root folder of the publish command you could find in previous versions.

**Comment by DierkDroth** [comment]
Thanks for looking into @jeromelaban.

> The behavior you're describing is not known at this time
> This is the expected behavior,

I'm glad my multi-hour investment was not in vain, but highlighted what was not known before and is, as you said, a change in Blazor - not a welcome one I have to say...

> you can publish the wwwroot folder instead of the root folder

Nevertheless, I'm still hit the wall on trying to restore the prior behavior where all files/folder which are now under the `wwwroot` subfolder would again be one level up (as before). Something like `dotnet publish --output <anyFolder>` would not do since the `wwwroot `subfolder + content would be preserved.

Are you referring to something different?

**Comment by DierkDroth** [comment]
FYI 
For anyelse who's running into the problem that is folder structure is changed by upgrading to `Uno.Wasm.Bootstrap 8.X` (generataed files now as located in `wwwroot `subfolder)

I failed on trying to restore the folder structure as it was with `Uno.Wasm.Bootstrap 7.X` (and before) but had to change the logic on my end to reflect the change which came with `Uno.Wasm.Bootstrap 8.X`:
- my server backend now has to redirect the client to `.../wwwroot/index.html` instead of `.../index.html`
- I had to change the WASM project file to `<WasmShellWebAppBasePath>mypath/**wwwroot**/</WasmShellWebAppBasePath>`
