### ISSUE TITLE
[iOS][Android] TextBox content not wrapping

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#14267]
### Current behavior

Seemingly since https://github.com/unoplatform/uno/pull/13002 TextBox content does not wrap properly.

Current behavior
When using the code from a Material TextBox style to make a few changes to the style, the behavior of the TextBox using this style is different from a TextBox using the original Material style (for example MaterialFilledTextBoxStyle in this case). More specifically, the TextBox's content is not wrapping when the TextWrapping property is set to "Wrap".

Expected behavior
The TextBox's content should be wrapping when the TextWrapping property is set to "Wrap".

Environment
Tested on Uno.WinUI 4.10 and 5

Sample
[TextBoxWrap.zip](https://github.com/unoplatform/uno/files/13254015/TextBoxWrap.zip)

**Comment by Youssef1313** [comment]
> When using the code from a Material TextBox style to make a few changes to the style, the behavior of the TextBox using this style is different from a TextBox using the original Material style (for example MaterialFilledTextBoxStyle in this case). More specifically, the TextBox's content is not wrapping when the TextWrapping property is set to "Wrap".

Just to clarify on this. Using the code from Material TextBox style should have the same behavior. The reason they appeared to behave differently is that the Uno.Material version used is older and was compiled with XAML generator prior to supporting TemplateBinding of attached properties.

So, the real issue is that the workaround isn't working for Material style in general.
