### ISSUE TITLE
Type "BinaryPrimitives" is in both "System.Memory.dll" and "mscorlib" in release 1.45.0 on iOS

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#1445]
## Current behavior
error CS0433: 类型“BinaryPrimitives”同时存在于“System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”和“mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e”中

## How to reproduce it (as minimally and precisely as possible)
`var length = BinaryPrimitives.ReadUInt32BigEndian(header.AsSpan(1));`

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
Thanks for reaching out!

We require the template to be filled out when submitting all issues. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Can you please provide a project that reproduces this issue?

Thanks for understanding and meeting us halfway!
