### ISSUE TITLE
[Android] SuggestedStartLocation is not handled for FileOpenPicker

### ISSUE THREAD

**Issue by arianeleonard** [unoplatform/uno#14658]
### What would you like to be added

FileOpenPicker's feature SuggestedStartLocation is not handled for Uno Platform targets as mentioned here : https://platform.uno/docs/articles/features/windows-storage-pickers.html

### Why is this needed

The SuggestedStartLocation property can't be used to specify where to pick a picture from. For example, to pick a picture from iOS' or Android's native photo gallery, setting this property to PickerLocationId.PicturesLibrary has no effect, so the file system will be opened instead of the native photo gallery.

Here is an Uno sample where the photo gallery is opened for iOS, but not for Android : 
[SelectPhoto.zip](https://github.com/unoplatform/uno/files/13531639/SelectPhoto.zip)

It is possible to open the photo gallery instead of the file system on both mobile platforms with MAUI : 
[PickPhoto.zip](https://github.com/unoplatform/uno/files/13531603/PickPhoto.zip)

### For which platform

Android, iOS

**Comment by jeromelaban** [comment]
Thanks for the update. To be sure of the content, this is an Android issue only, right? You mention both targets in the title of the issue, but say it works on iOS in the sample.

**Comment by arianeleonard** [comment]
I mentioned iOS because it says it is not handled for iOS in the documentation, but it does work on iOS.

**Comment by arianeleonard** [comment]
@jeromelaban I tried using FileOpenPicker with SuggestedStartLocation set to PicturesLibrary with the latest version on Uno5 (5.0.152) and it still doesn't work for me on Android. Is there something I'm missing for it to work? (Testing on a Galaxy A13 5g) Here is the sample I created : 
[SelectPhoto.zip](https://github.com/unoplatform/uno/files/14069621/SelectPhoto.zip)

**Comment by pkar70** [comment]
Because on Android, SuggestedStartLocation is 'translated' to filetypes filter, and is not used as a real folder.

**Comment by ajpinedam** [comment]
@arianeleonard  what phone are you using to test? 

I am running the MAUI version you shared (thanks for that) on my OnePlus 7 Pro and I get a similar behaviour compared with Uno's FilePicker. This is the Explorer is launched instead of the default app (Native Photo App) as you suggested. I also tested on a Simulator running Android 12 and got the same result. 

Anyway, I am doing some changes that will get our `FilePicker` implementation and experience closer to what you see on **MAUI** Android, but first I'd like to reproduce it in order to test it's working.

https://github.com/unoplatform/uno/assets/1900897/80ff98db-0e4b-4468-8c84-c2e32ddf8cfd

**Comment by arianeleonard** [comment]
@ajpinedam Great! I'm using a Galaxy A13 and an iPhone 11.
