### ISSUE TITLE
Android SplashScreen build error

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#15405]
Hi, i receive this error on Android (windows and wasm works great) every time I create a new project and try to run in debug or release mode.
![error](https://github.com/unoplatform/uno/assets/16562078/5309430e-25ed-4c46-bfd1-391522ae5743)
This happens in both Visual Studio and Visual Studio Code, with UNO platform 5 and 5.1. I've tried to clean, build and rebuild solution, specify the .net version in global.json, try to run in WSA, my Android device and emulator but nothing works. This is the last project i created, hope is useful: 

https://github.com/unoplatform/uno/files/14209137/test.zip

_Originally posted by @Rafucho25 in https://github.com/unoplatform/uno/discussions/15322_

**Comment by pictos** [comment]
I couldn't reproduce on my machine... I was able to see the binlog provided by the user, and the error happens because `Uno.Resizetizer` doesn't generate the assets, and looking even further the task was skipped because the `input` and `output` files are marked as up-to-date. The workaround, I would say is to do a rebuild instead of a build. 

But I can't image what were the steps made to reproduce it

**Comment by jeromelaban** [comment]
Fixed in recent builds.
