### ISSUE TITLE
[WASM] TextBox natural width is too large

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1561]
## Current behavior

A ContentControl does not lay out contents correctly if a custom ControlTemplate is used.

## Expected behavior

Layout should match that in UWP

## How to reproduce it (as minimally and precisely as possible)

~~Build the attached project for UWP and observe layout of content inside ContentControl.  Load the same project in WASM and observe that contents are laid out incorrectly.~~

~~[ContentControlLayout.zip](https://github.com/unoplatform/uno/files/3632554/ContentControlLayout.zip)~~

Update (Carl de Billy): Check this link <https://playground.platform.uno/#0302c8a5>

## Environment

Nuget Package:
Uno.UI
Package Version(s):
1.46.230-dev.2733
Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Problem reproduced on the Playground: https://playground.platform.uno/#4057807b

`ContentControl` seems innocent here, it seems to be when we're putting a `TextBox` in a `Grid`'s column with a `Width="*"`.

Will continue to investigate...

**Comment by carldebilly** [comment]
Investigations finished. There's 2 components in this problem:
1. The _natural_ width (when no constrains nor stretches are speficied on it)  of a `<TextBox>` is too large. On Windows, it's 64px. On Wasm it's about 225px. That's not a big deal, except when you're using it in an `Auto` width column.
2. The actual problem here is caused by the clipping not being applied correctly on wasm.  The first element got clipped, but at the _arranged size_, which is bigger than the `availableSize` received during the _arrange phase. That means the control won't be clipped properly.

I'll change the title of this issue to reflect problem #1 previously.
The problem #2 will be tracked in the issue #652.

**Comment by carldebilly** [comment]
Fixed and published in `v2.0.512-dev.3728` https://www.nuget.org/packages/Uno.UI/2.0.512-dev.3728
