### ISSUE TITLE
[Gallery][WASM/iOS/Android]FAB- In the FAB section, the disabled buttons (such as 'Saved,' 'Pin,' and 'Checked') are not being displayed as disabled.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#15978]
### Current behavior

![FAB issue](https://github.com/unoplatform/uno/assets/74563602/3ac7b51c-8076-447f-90c0-9cf55381736d)

### Expected behavior

![FAB correct](https://github.com/unoplatform/uno/assets/74563602/9d6493e6-98f5-4027-8dc1-8d4a90069770)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app.
2. Click on “Floating Action Button” from the "UI Component" list.
3. Note that the Gallery app Should be opened in Light Theme.**( this issue is not happening in dark theme).**
4. Go to first section(Floating Action Button).
5. Notice that In the FAB section, the disabled buttons (such as 'Saved,' 'Pin,' and 'Checked') are not being displayed as disabled.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by jeromelaban** [comment]
@kazo0

**Comment by kazo0** [comment]
interesting, it seems related to the Uno version, not the Material version. Latest Themes sample app doesn't have this issue until I update Uno to the latest dev bits

**Comment by kazo0** [comment]
Can confirm it has started as of Uno 5.2.0-dev.960

Which is from this PR https://github.com/unoplatform/uno/pull/15524

FYI @Youssef1313 / @jeromelaban 

This might also be the cause of https://github.com/unoplatform/uno/issues/16007 and https://github.com/unoplatform/uno/issues/16009

**Comment by Youssef1313** [comment]
@kazo0 Thanks for finding this!
I may have a PR

**Comment by Youssef1313** [comment]
Same root cause as https://github.com/unoplatform/uno/issues/16006 as well.

The behavior introduced in #15524 appears to be correct. To summarize, WinUI has the behavior that, normally, Animation is higher precedence than Local. However, they special case that if the Local value is newer than Animation, then Local is what will take effect. This is a behavior I introduced in #15524.

Looking more through WinUI code, there is this part that we don't yet have and may very likely be the missing part here.

![image](https://github.com/unoplatform/uno/assets/31348972/9a9a44d9-1c05-45f2-8134-1d5773283e94)

When they detect a Local value being set during animation (which means it's going to take precedence over animation), they do stop template binding.

For FAB, the local value would be coming from [here](https://github.com/unoplatform/Uno.Themes/blob/d2eb75cc5d231bc7b12b372982d83c9cf68baad0/src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml#L220), and Animation value from [here](https://github.com/unoplatform/Uno.Themes/blob/d2eb75cc5d231bc7b12b372982d83c9cf68baad0/src/library/Uno.Material/Styles/Controls/v2/FloatingActionButton.xaml#L284)

Reading WinUI code I referenced above, I think TemplateBinding should be removed in this case.

**Comment by Youssef1313** [comment]
The fix I have appears to only fix #16006 for some reason.

I'm going to dig more.

**Comment by kazo0** [comment]
#16007 confirmed broken as of -dev.960
#16006 confirmed broken as of -dev.960
#16009 confirmed broken as of -dev.960

@Youssef1313 for #16009 it seems to be related, I noticed that it's not happening all the time but as of `-dev.960` the selected state doesn't always show. Notice in the video that once I hover my cursor over the items, the selected state appears

FYI these were all tested using WASM, didn't look for Android/iOS but I assume it's the same

### 5.2.0-dev.954

https://github.com/unoplatform/uno/assets/4793020/7668f248-5e64-46ac-85d3-c4e3d1d07817

### 5.2.0-dev.960

https://github.com/unoplatform/uno/assets/4793020/d6523111-9589-46c2-95f3-1af5e72cf140

**Comment by Youssef1313** [comment]
@kazo0 The video from dev.954 is testing "c" and "e" items in the ComboBox, while the other video that shows the video is testing "d". The issue is only reproducible with "d" actually, or more specifically, the middle item in ComboBox in general. So, I'm not yet sure if it's a regression from #15524 or not.

**Comment by kazo0** [comment]
> @kazo0 The video from dev.954 is testing "c" and "e" items in the ComboBox, while the other video that shows the video is testing "d". The issue is only reproducible with "d" actually, or more specifically, the middle item in ComboBox in general. So, I'm not yet sure if it's a regression from #15524 or not.

Hmm interesting, ok I will keep testing and let you know!
