### ISSUE TITLE
ListView.Header has no DataContext

### ISSUE THREAD

**Issue by juliecantin** [unoplatform/uno#1598]
## Current behavior

When a ListView has a Header, the content of that header does not inherit the ListView's DataContext. You must use HeaderTemplate instead and set Header="{Binding}"

## Expected behavior

When a ListView has a Header, the content of that header inherits the ListView's DataContext.

## How to reproduce it (as minimally and precisely as possible)

https://github.com/jcantin-nventive/ListViewHeaderDemo
Launch the app and look at the text displayed. On iOS/Android, the DataContext is the StackPanel instead of receiving the parent's DataContext. On UWP, the DataContext is set correctly.

## Environment

Nuget Package: Uno.UI

Package Version(s): 1.45.0

Affected platform(s):
- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.9.11)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MatFillion** [comment]
Same applies to ListView.Footer

**Comment by YGuerin** [comment]
Any update on this one ?

**Comment by jeromelaban** [comment]
We'll take a look for 2.2

**Comment by agneszitte-nventive** [comment]
@davidjohnoliver do you think this issue is still happening with latest Uno version ?

**Comment by davidjohnoliver** [comment]
@agneszitte-nventive Not sure

**Comment by artemious7** [comment]
It's still happening with Uno.UI 4.6.39. 
On iOS it's inconsistent. iOS gets `ListView`'s `DataContext` value and puts it on the `Header`/`Footer` and if the `DataContext` is `null` at the time of the call, it will not update later because it doesn't take the binding, but the value.
The workaround is to additionally set `Footer="{Binding}"` or `Header="{Binding}"`.

Here's a repro:

[App15.zip](https://github.com/unoplatform/uno/files/10326120/App15.zip)

@davidjohnoliver

**Comment by jeromelaban** [comment]
fixed in 5.0-dev
