### ISSUE TITLE
[WASM] Touchpad taps not registered as clicks on macOS

### ISSUE THREAD

**Issue by kazo0** [unoplatform/uno#16076]
### Current behavior

I can't click on buttons or anything else unless I physically click my trackpad on my macbook. Everywhere else it works to just tap the trackpad without clicking down. It seems like we aren't registering that as a click? This is with latest Edge and Chrome on macOS only

Edge: 123.0.2420.65 (Official build) (arm64)
Chrome: 123.0.6312.87 (Official Build) (arm64)
MacBook Air M2: macOS 14.4.1 (23E224) (Sonoma)

Jumping from a Blazor app where this is working, to the Uno Gallery where tapping on the ToggleSwitch/NavigationView button does nothing:

https://github.com/unoplatform/uno/assets/4793020/2726fa73-9b02-4b35-b664-15e582aee6ee

**Comment by MartinZikmund** [comment]
@kazo0 I am not able to reproduce this one on Edge on my Mac (version 124.0.2478.67). Can you try updating to the latest Edge version and see if that fixes it? If not, are there any errors showing up in F12 Developer tools?

**Comment by kazo0** [comment]
Yep I'm on latest:

<img alt="image" src="https://github.com/unoplatform/uno/assets/4793020/5e9752dd-4b09-42d0-9d60-85dd14835d43">

If I continuously tap on my touchpad (not physcially clicking it down), every 4th or 5th tap will eventually trigger a click and be registered by an Uno app:


https://github.com/unoplatform/uno/assets/4793020/885d3a9b-f5da-4921-9ce2-a9b5314c9c30

**Comment by kazo0** [comment]
Same behavior on Safari and Chrome latest

**Comment by MartinZikmund** [comment]
@kazo0 I was trying this on my Mac, but I might have a different kind of touchpad, because if I just touch it (without pressing to get the haptic feedback, it does not do the "click" action anywhere, even throughout the OS. It could be interesting if @dr1rrb was able to reproduce this, as if there is an issue, it must be somehow that the "light touch" triggers different JS events somehow

**Comment by kazo0** [comment]
@MartinZikmund you need to enable it in the settings: 
<img alt="image" src="https://github.com/unoplatform/uno/assets/4793020/835bc565-91d3-48e8-8ca7-c5a4f94f44b8">

**Comment by MartinZikmund** [comment]
The problem is an oddity! When Tap to click is enabled on macOS, a short tap may sometimes (but very unreliably) trigger JS `pointerdown` but have all the mouse buttons set as off.

<img width="500" alt="Screenshot 2024-05-27 at 13 20 11" src="https://github.com/unoplatform/uno/assets/1075116/d20622e2-3c59-4415-bd8c-3fb09346bc6a">

This is logically an impossibility, so the issue is rather a browser handling problem, but in any case we need to adjust for this. My workaround is to set left button on pointer down in case the device is a mouse and no button is seemingly pressed
