### ISSUE TITLE
Icon property not working when using c# to define resources.

### ISSUE THREAD

**Issue by MarkLFT** [unoplatform/uno#16133]
### Current behavior

Unable to build with error: 

CS0311	The type 'Uno.Toolkit.UI.TabBarItem' cannot be used as type parameter 'T' in the generic type or method 'AppBarButtonMarkup.Icon<T>(T, IconElement)'. There is no implicit reference conversion from 'Uno.Toolkit.UI.TabBarItem' to 'Microsoft.UI.Xaml.Controls.AppBarButton'.

### Expected behavior

I expect it to be able to build.

### How to reproduce it (as minimally and precisely as possible)

Created a new project using the latest template version, specifying using C# not xaml.
Updated nugets to latest versions.
Modified main page.  No other pages in code changed.  

### Workaround

Non found

### Works on UWP/WinUI

None

### Environment

Other

### NuGet package version(s)

5.1.104

### Affected platforms

Windows

### IDE

Visual Studio 2022

### IDE version

Latest

### Relevant plugins

None

### Anything else we need to know?

I have shared the project through github.  It can be found at https://github.com/MarkLFT/RMUtility.git

**Comment by kazo0** [comment]
Thanks @MarkLFT!

I have made [a PR](https://github.com/MarkLFT/RMUtility/pull/1) to your GitHub repo that should fix your problem.

In order to use the `TabBar` you'd need to have a reference to the [Uno.Toolkit.WinUI NuGet package](https://www.nuget.org/packages/Uno.Toolkit.WinUI/).

Since you are also looking to use the Material styles for the Toolkit controls and use the Toolkit with C# Markup, there is a package that exists that bundle Uno Material, Uno Toolkit, and the Markup helpers all in one package that can be found here: https://www.nuget.org/packages/Uno.Toolkit.WinUI.Material.Markup

Along with that, you need to bootstrap that `AppResources.cs` with the initialization of the Material Toolkit resources, which I have done in my PR. The `Uno.Toolkit.WinUI.Material.Markup` packages comes with a helper method (`UseMaterialToolkit()`) to use in the `AppResources.cs` and can be used like this:

```cs
this.Build(r => r
    .Merged(new XamlControlsResources())
    .UseMaterialToolkit()
);
```

I'm curious if you had selected to use Material and Toolkit in the wizard when you initially created this project because that should have done all of this work for you from the start. 

Within the wizard, you can select Material as your theme from here:

![image](https://github.com/unoplatform/uno/assets/4793020/a41c0db1-9533-4dcc-bab5-459e1dca1ebc)


And then you can add the Toolkit controls (like `TabBar`) by enabled Toolkit here:

![image](https://github.com/unoplatform/uno/assets/4793020/aaea4bb8-6c07-4aeb-bf4a-5dd4f4d84769)


Otherwise, if you are creating your app with the CLI you can use the command:

```sh
dotnet new unoapp -preset blank -o MyApp -toolkit -theme material -markup csharp
```
