### ISSUE TITLE
[skia][macos] A default `exec` icon is shown in the dock bar when no icon is provided

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17002]
### Current behavior

When debugging the app with VS Code, I see the following icon in the taskbar.

![image](https://github.com/unoplatform/uno/assets/1608424/32c22b5c-891b-4447-9fef-05c1a8363ab6)

### Expected behavior

The app icon should be used

### How to reproduce it (as minimally and precisely as possible)

Git clone: https://github.com/ArchieCoder/UnoIconBug

This is a brand new project where I removed the platform: iOS/Android/Web. In other words, I only select Desktop and Windows.

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (macOS)

**Comment by agneszitte** [comment]
cc @spouliot

**Comment by spouliot** [comment]
> The app icon should be used

AFAICT there's no icon set so I think you're expecting a _default_ Uno app icon ?

Here's what happening... @jeromelaban correct me if/where I'm wrong 😄 

Both the `net8.0-windows10.0.19041` (WinUI) and `net8.0-desktop` for Windows (Uno's WPF backend) are producing a managed executable, a PE/WinEXE `.exe` file, which includes a (default) Uno icon. The OS takes care of the rest when it runs the executable.

However when `net8.0-desktop` on macOS is used you get a (copied) native executable [1] (using the same name as the project) and a `.dll`. Both formats [2] do not include icons.

```
l bin/Debug/net8.0-desktop/UnoIconBug*
-rwxr-xr-x  1 poupou  staff   120K  4 Jun 19:08 bin/Debug/net8.0-desktop/UnoIconBug
-rw-r--r--  1 poupou  staff    97K  4 Jun 18:52 bin/Debug/net8.0-desktop/UnoIconBug.deps.json
-rw-r--r--  1 poupou  staff   576K  4 Jun 19:08 bin/Debug/net8.0-desktop/UnoIconBug.dll
-rw-r--r--  1 poupou  staff   305K  4 Jun 19:08 bin/Debug/net8.0-desktop/UnoIconBug.pdb
-rw-r--r--  1 poupou  staff   410B  4 Jun 18:52 bin/Debug/net8.0-desktop/UnoIconBug.runtimeconfig.json
```

[1] it's copied by and from `dotnet` and it **not** made for exclusively for the executing app
[2] it's not an app bundle executable, which could have an icon, since it's also used to service console-based apps

In the case of `net8.0-desktop` on Linux/X11 the situation (wrt formats) is identical but there's an icon. I think it's being set at runtime (not at build time like on Windows). I guess the macOS backend should do the same.

Side note: if you set your own icon (in the manifest or using the API) then it will be shown on all OS / backends. IOW this only happens if you're expecting the default icon to be the Uno logo.
