### ISSUE TITLE
Fail the build on uses of MediaPlayer and ProgressRing if related packages cannot be found

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17026]
### What would you like to be added

The XAML Generator should detect uses of those types and fail if the related support packages are not included in the build.

### Why is this needed

Better initial experience and avoid runtime-only failures

**Comment by Youssef1313** [comment]
Not sure if it's better suited for a separate analyzer. I don't have a strong opinion though. Let's discuss this.

**Comment by Youssef1313** [comment]
I'll go with a simplified approach for now. But here is a proposal that we may want to consider in future.

First, we can introduce a new attribute `UnoRequiresAssemblyAttribute` which will be present in Uno.UI.Toolkit (so that it's available for WinAppSDK as well)

```csharp
[AttributeUsage(AttributeTargets.Method)]
public sealed class UnoRequiresAssemblyAttribute : Attribute
{
    public UnoRequiresAssemblyAttribute(string assemblyName) // maybe allow multiple assemblies?
    {
    }
}
```

The analyzer will then look for regular method calls as well as constructor calls and determine if the called method has that attribute, then it will verify that the required assembly exists.

This proposal is beneficial for following scenario:

1. A library author can decide to use `ProgressRing` but leave it to the consumer to reference the required packages (maybe the consumer doesn't use a code path from the library that hits `ProgressRing` and so they don't need the extra package)
2. The library author will be getting a warning if they don't reference the required package, but they should be able to delegate the responsibility to the caller by adding the attribute himself to such method. For example:

    ```csharp
    [UnoRequiresAssembly(...)]
    public ProgressRing CreateProgressRing() => new(); // no warning even if assembly not existing.
    ```

One open question with this proposal is how we handle things in XAML inside a library. The XAML generator won't be generating `UnoRequiresAssembly`. Maybe we can allow the attribute on classes to effectively mean "all methods within this class" and then the library author can add the attribute himself on the non-generated partial (the one where they manually call `InitializeComponent`)?
