### ISSUE TITLE
[WASM] `SettingsExpander` does not render correctly

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17312]
### Current behavior

https://github.com/CommunityToolkit/Windows/issues/393

### Works on UWP/WinUI

None

**Comment by ajpinedam** [comment]
We found the problem with this issue is connected to the Uno Expander Control.

The `SettingsExpander` has the following Style Configuration (simplified version):

```xml
<Expander>
    <Expander.Header>
        <SettingsCard />
    </Expander.Header>
    <Expander.Content>
        <ItemsControl />
    </Expander.Content>
</Expander>
```

When rendered, the `SettingsCard` is part of the Visual Tree, but the Data bound is not correct.

The `SettingsCard` sets a `TemplateBinding` from the Expander.Header but due to an issue on the TemplatedParent Syncronization this is returning the wrong information.

Expander Control Template Template (simplified version):

```xml
<!-- Expander ControlTemplate -->
<Grid>
    <RowDefinition x:Name="Row0" Height="Auto" />
    <RowDefinition x:Name="Row1" Height="*" />    
    <ToggleButton  Content="{TemplateBinding Header}" Style="{StaticResource ExpanderHeaderDownStyle}" />
    <Border>
        <ContentPresenter Content="{TemplateBinding Content}" Grid.Row="1" />
    </Border>
</Grid>


<!-- Expander Header Control Template (ExpanderHeaderDownStyle) -->
<Grid>
     <ContentPresenter x:Name="ContentPresenter" />
</Grid>
```

As can be seen, the Header ContentPresenter is inside a `ToggleButton`. When calling the TemplatedParentSyncronization [here](SynchronizeContentWithOuterTemplatedParent ), this returns a level dip in the UI tree. 

Specifically, in this line of code:

```csharp
return (this.TemplatedParent as IFrameworkElement)?.TemplatedParent;
```

It's returning the `Expander` instead of the `SettingsExpander`

We believe that @Xiaoy312  PR [17645](https://github.com/unoplatform/uno/pull/17645) will fix this issue since this PR is fixing issues related to the TemplatedParent like this one.
