### ISSUE TITLE
[DROID] ApplicationData.Current null in App constructor

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#1741]
## Current behavior

On Droid, if you attempt to access ApplicationData.Current in the App constructor it is null.  This should be available so things like user-selected themes could be pulled from the LocalSettings store before the App InitializeComponent call is made.

## Expected behavior

ApplicationData.Current should be usable in App constructor.

In the attached project, attempt to start in Droid - you receive a null object error when attempting to check for a local setting.  Works in UWP and WASM.

[App17.zip](https://github.com/unoplatform/uno/files/3697856/App17.zip)

Nuget Package:
Uno.UI
Package Version(s):
2.0.282-dev.3016
Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by ghuntley** [comment]
howdy @Pedrocssg, thanks for providing the reproduction. I can confirm reproducibility on Android when used in the App constructor whilst usage afterwards works fine.

**Comment by MartinZikmund** [comment]
I wonder if the Android problem is related to the issue I was seeing when implementing RequestedTheme support. I think there is a problem in that accessing ApplicationContext in App constructor fails, as the App instance is created *before* the Android Application base constructor runs - hence it does not exist yet. I got into a `StackOverflowException` this way, as attempt to use ApplicationContext tried to run the app initialization again repeatedly ad infinitum.

**Comment by ghuntley** [comment]
On Android, `ApplicationData.Current.[LocalFolder|RoamingFolder]` throws a NRE exception if accessed in the constructor of App.xaml.cs.

Digging into the current implementation on Android reveals:

https://github.com/unoplatform/uno/blob/master/src/Uno.UWP/Storage/ApplicationDataContainer.Android.cs#L29

Specifically there's a dependency on `ContextHelper.Current`:

```csharp
_preferences = PreferenceManager.GetDefaultSharedPreferences(ContextHelper.Current);
```

and `ContextHelper.Current` isn't populated until an activity is created:

```
protected override void OnLaunched(LaunchActivatedEventArgs e)
{
    Console.WriteLine(ContextHelper.Current); // is the name of the current activity.
}
```

Here's `ContextHelper.Current` in the App.xaml.cs constructor:

```csharp
sealed partial class App : Application
{

    public App()

    {

    Console.WriteLine(ContextHelper.Current); // is null.

    }

}
```

The fix is to change the internals of Uno to use `Android.App.Application.Context` instead of `ContextHelper.Current` as the preference manager needs any context and the application context will do. 

A pull-request has been raised over at https://github.com/unoplatform/uno/pull/1790 which resolves this issue.

**Comment by NGame1** [comment]
It is still null for me on latest build
2.0.512-dev.4042
Android 5.0

**Comment by MartinZikmund** [comment]
@NGame1 Have you updated to use the new constructor in the Android project? Instead of directly creating `App` instance, you now need to pass a `Func<App>` that creates the instance: 
https://github.com/unoplatform/uno/blob/12d1c26b110a8ad119b55221dea408265d818eab/src/SolutionTemplate/UnoSolutionTemplate/Droid/Main.cs#L26

**Comment by NGame1** [comment]
uh nice, Now it's not null.

**Comment by jeromelaban** [comment]
There's a message in the logs that should have told you what to do. It may be drowned in other android messages though...
