### ISSUE TITLE
Support for generating a signed `.app`

### ISSUE THREAD

**Issue by dansiegel** [unoplatform/uno#17427]

**Comment by TopperDEL** [comment]
This needs a new uno-Release, right?

**Comment by jeromelaban** [comment]
Yes it does, it will be in the next release.

**Comment by spouliot** [comment]
@jeromelaban maybe we should re-open this one.

It seems the latest versions of macOS [1] do not like the format on the app bundle (it says it's damaged) but it works on earlier versions [2] of macOS.

That will also block [signing](https://github.com/unoplatform/uno/issues/17141) the app bundle (since it won't be accepted as valid).

[1] macOS 14.7 and 15.1 on arm64
[2] macOS 14.3 on x64_64

**Comment by spouliot** [comment]
Some dylibs [1] are fat (both `arm64` and `x86_64`) while most of them (including the ones from dotnet) are for the selected architecture. If producing a _thin_ bundle then they should be thinned (`lipo -extract`) to reduce the size of the bundle.

[1] including
* libSkia.dylib
* libHarzBuff.dylib
* libUnoNativeMac.dylib

**Comment by spouliot** [comment]
The PR https://github.com/unoplatform/uno/pull/18984 is a pre-requisite to use app bundles.

**Comment by spouliot** [comment]
Included in 5.6 (along with app bundle notarization)
[Documentation PR](https://github.com/unoplatform/uno/pull/19045)
