### ISSUE TITLE
[Skia WPF] SolidColorBrush message should not appear

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#17478]
### Current behavior

Starting the Skia Desktop target on windows shows this message:

```
warn: Uno.UI.Runtime.Skia.Wpf.UI.Controls.UnoWpfWindowHost[0]
      This platform only supports SolidColorBrush for the Window background
```

### Expected behavior

No error

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
The default background is null which is why the warning shows.

https://github.com/unoplatform/uno/blob/e533059636ea4e64a42ba27e9efc3dd649b08386/src/Uno.UI.Runtime.Skia.Wpf/UI/Controls/UnoCompositeWindowHost.cs#L103-L113

This `else` should be `else if (_winUIWindow.Background is not null)`

(Same goes for X11 and Gtk)

**Comment by jeromelaban** [comment]
We probably should not warn if it null then, or we should be providing a proper default color that won't warn.
