### ISSUE TITLE
Loading ContentPresenter stackoverflows (possibly a regression?)

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#17470]
### Current behavior

When the following test executes for ContentPresenter, it stackoverflows :(

```csharp
​  [TestMethod]
  [RunsOnUIThread]
  [DataRow(typeof(Grid))]
  [DataRow(typeof(StackPanel))]
  [DataRow(typeof(Border))]
  [DataRow(typeof(ContentPresenter))]
  public async Task MyTest(Type type)
  {
    var control = (FrameworkElement)Activator.CreateInstance(type);

    control.Width = 200;
    control.Height = 200;

    await UITestHelper.Load(control);
  }
```

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment]
@ramezgerges Could it be a regression from recent ContentPresenter changes?

**Comment by ramezgerges** [comment]
I couldn't reproduce this on my machine (on Windows with latest master).

**Comment by Youssef1313** [comment]
@MartinZikmund Can you check if you can repro or if it's just me somehow? :/

**Comment by MartinZikmund** [comment]
I have tested this by adding the snippet above in `Given_ContentControl.cs` (you can even just keep the `[DataRow(ContentPresenter)]`, others are not needed) and indeed it stack overflows for me on Skia.Generic and on UnoIslandsSamplesApp.Skia.Wpf. Based on my debugging the problem is as follows:

1. `ContentPresenter` is constructed
2. `OnApplyTemplate` is called
3. Inside the binding to `Content` is created - **binding to `ContentControl.Content` of the `TemplatedParent` of the `ContentPresenter`**
4. Incorrectly the `TemplatedParent` is assumed to be `SampleControl` - which applies its content (`UnitTestsPage`) as the `Content` of the tested `ContentPresenter` - thus creating a circular visual tree where the parent of the page is the grand child `ContentPresenter`
5. The stack overflow just occurs on "LostFocus" event which is bubbling up from the button that runs the test up and which just ends up in infinite loop -> Page -> ContentPresenter -> up towards Page -> ContentPresenter -> ...

**Comment by MartinZikmund** [comment]
I assume the problem that needs to be fixed here is the fact that `TemplatedParent` of the `ContentPresenter` should just be `null`, as it is actually not part of a template. Adding @ramezgerges and @Xiaoy312

**Comment by Youssef1313** [comment]
Let's wait for Xiao's work then.

**Comment by MartinZikmund** [comment]
To debug this most easily, adjust the `SetParent` method in `src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs` as follows:

![image](https://github.com/user-attachments/assets/265b771d-1137-4118-8a6a-1ece08f15eb4)

You will be able to see that this gets executed for `UnitTestsPage` once when it is first opened, and then the second time after the unit test starts - setting the page's `Parent` to be its grand child `ContentPresenter`

**Comment by agneszitte** [comment]
@jeromelaban Can this need to be QA'ed as last time?
