### ISSUE TITLE
Custom font not working as expected

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17536]
### Current behavior

Following the instructions from https://platform.uno/docs/articles/features/custom-fonts.html#adding-a-custom-font-in-the-app-assets-folder will lead to "could not be found, using system default" at runtime.

I'm using the variable font Inter from Google library.

I suspect that there is more issues with the usage of variable font because specifying **any weight does not work** with Skia

Screenshot from Skia Desktop
<img width="1046" alt="Custom Font" src="https://github.com/user-attachments/assets/31a47cb7-e91c-4bce-9135-b41d8ab3121b">

Screenshot from WinUI (Custom font does not work at all)
![image](https://github.com/user-attachments/assets/ebc03967-cac2-4f9c-9187-7dba8a24a902)

### Expected behavior

Custom font should work

### How to reproduce it (as minimally and precisely as possible)

Skia custom font issue:
[UnoCustomFont.zip](https://github.com/user-attachments/files/16237443/UnoCustomFont.zip)

WinUI custom font does not work at all (notice that I remove the FontFamily for each of the scenario
[UnoCustomFont2.zip](https://github.com/user-attachments/files/16237616/UnoCustomFont2.zip)

### Works on UWP/WinUI

No

### Affected platforms

Skia (WPF), Skia (Linux X11), Skia (macOS), Windows (WinAppSDK)

### IDE

Visual Studio 2022

**Comment by ArchieCoder** [comment]
After more investigation, even in a pure WinUI app, I'm not able to use the Inter font. They must be some restrictions, but I don't find them.

**Comment by Youssef1313** [comment]
You have:

```xml
<FontFamily x:Key="MainFont">
    ms-appx:///Assets/Fonts/inter.ttf
</FontFamily>

<FontFamily x:Key="MainFontWithAppName">
    ms-appx:///UnoCustomFont/Assets/Fonts/inter.ttf
</FontFamily>

<FontFamily x:Key="MainFontWithAppNameAndFontName">
    ms-appx:///UnoCustomFont/Assets/Fonts/inter.ttf#Inter Thin
</FontFamily>
```

The ones with "AppName" are not correct both for Uno and WinAppSDK. It should simply be `ms-appx:///Assets/...`

And for this to work on WinAppSDK, it should exactly be `ms-appx:///Assets/Fonts/inter.ttf#Inter`.

Still, there will be remaining difference between WinAppSDK and Uno caused by SkiaSharp not supporting variable fonts. The variable font support recently implemented in Uno Platform 5.3 works via an Uno-specific feature called "font manifest". See [Variable fonts and font manifest documentation](https://platform.uno/docs/articles/features/custom-fonts.html#variable-fonts-and-font-manifest).

**Comment by MartinZikmund** [comment]
Just to note - the fact that previously the "app name" in `ms-appx:///` was needed was because of multi-project template, which used a class library for the common source code. Now that we have single-project layout, the library itself **is** the app project, so that's why the `ms-appx:///` is pointing directly at the project root and the paths are simpler.

**Comment by ArchieCoder** [comment]
@Youssef1313 Please see my updated app. Good news, the font family seems to be selected correctly (you can see clearly the differences), however the Weight on Skia Desktop does not work.

Skia
<img width="565" alt="SkiaDesktop" src="https://github.com/user-attachments/assets/49b8df31-81eb-435c-b55e-57bf976b03b8">

WinUI
<img width="566" alt="WinUI" src="https://github.com/user-attachments/assets/1e36c22f-d11c-404e-8ca1-f83cb73b2d4a">

Project
[UnoCustomFont.zip](https://github.com/user-attachments/files/16363209/UnoCustomFont.zip)

**Comment by ArchieCoder** [comment]
Question: do I need to add the main font from the non static folder? If I double-click on it in File Explorer, the font is "Inter **Thin**"

<img width="570" alt="image" src="https://github.com/user-attachments/assets/b9e83e26-9d67-4906-a4b6-8009b61f5f71">

Source from Google

<img width="781" alt="image" src="https://github.com/user-attachments/assets/c9aa47a4-95ff-4321-b031-a4c67e16cad8">

[Inter.zip](https://github.com/user-attachments/files/16363244/Inter.zip)

**Comment by Youssef1313** [comment]
@ArchieCoder Your structure is right. It looks like `FontWeight="Number"` is not supported in by XAML generator, and it defaults to Normal right away. We will need to adjust this in https://github.com/unoplatform/uno/blob/1a6820b3ad48a42458a0ce058bb0e891d3e9eea2/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L5178-L5190

Meanwhile, if you use literal values instead of numeric values, it works on Skia Desktop:

![image](https://github.com/user-attachments/assets/55554f16-fabd-44d3-8c6b-0bd8397908ab)

**Comment by ArchieCoder** [comment]
@Youssef1313 I tested it and yes it works! I see that you have a fix already. I appreciate the fast response 👍

**Comment by Youssef1313** [comment]
Happy to help @ArchieCoder!
