### ISSUE TITLE
`Uno.UI.Xaml.Core.VisualTree` Visual Tree was not found

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17627]
### Discussed in https://github.com/unoplatform/uno/discussions/17622

<div type='discussions-op-text'>

<sup>Originally posted by **WenHong-Lau** July 22, 2024</sup>
I'm currently debugging an Android application and encountering numerous "Uno.UI.Xaml.Core.VisualTree: Visual Tree was not found." messages. This issue is causing significant delays in rendering controls, and in some cases, controls are not rendering at all.

In this repro, the controls were rendered but there are still Uno.UI.Xaml.Core.VisualTree: Visual Tree was not found. in the output.
[TestProj.zip](https://github.com/user-attachments/files/16329814/TestProj.zip)

</div>

**Comment by MartinZikmund** [comment]
@wenhong-lau While I fixed the issue of log messages appearing too frequently, your problem with control rendering delays must be caused by something else. Although there was quite a few of these messages showing up, they were actually not causing any performance issues. Please try to create a super-minimal repro where the performance issue still happens and report it as a new issue.

**Comment by WenHong-Lau** [comment]
Hi @MartinZikmund, I believe the current reproduction is sufficient. In the `TestProj.Common project`, specifically in `FormTableField.cs at line 41` within the `GenerateFields()` method, I have expanded the list to include 84 elements by duplicating the existing ones. You will notice that not all fields are being rendered. Additionally, when you click on the "**View Next Page**" TabBarItem at the bottom, the controls take a long time to load. I thought this was caused by the "Visual Tree was not found" error, as the controls only finish rendering after this error stops being reported. 

Below are the screenshots of the page show controls not rendering on Android:

**WinAppSDK**
![image](https://github.com/user-attachments/assets/b6f901e2-1cbd-450e-ab9a-dd14d46b6f68)
**Android**
![image](https://github.com/user-attachments/assets/d0493b9d-f2f2-41fa-83c6-0b34762d550b)
