### ISSUE TITLE
HotReloadStatusView doesn't show indicator when added to existing UI

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#17837]
### Current behavior

If the HotReloadStatusView is created and added to an existing UI it doesn't show any status indicator (just shows a white square) 

### Expected behavior

Same indicators are presented as the HotReloadStatusView on the DiagnosticsOverlay

### Works on UWP/WinUI

None

**Comment by dr1rrb** [comment]
This is because the [`OnHotReloadStatusChanged()`](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.RemoteControl/HotReload/HotReloadStatusView.cs#L158) is not invoked (it's expected to be invoked externally by the [`ClientHotReloadProcessor`](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs#L137). We need to provide a public ctor which will self-connect to the [`ClientHotReloadProcessor.StatusChanged` event](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.RemoteControl/HotReload/ClientHotReloadProcessor.Common.Status.cs#L26).

**Comment by dr1rrb** [comment]
@rajamatt I did it as I was working on this file

**Comment by dr1rrb** [comment]
Even if now properly init and fed with events, the indicator is still not showing

**Comment by agneszitte** [comment]
@nickrandolph additional QA is needed for this issue, please?
