### ISSUE TITLE
Who's using Uno in production?

### ISSUE THREAD

**Issue by aronmek** [unoplatform/uno#18]
Can you list some names of real companies/apps built on the uno platform?
Also the history of the project wouldn't hurt :)

**Comment by SirAnimesh** [comment]
This *.NET Rocks* [podcast episode](https://pca.st/06Og) covers Uno in depth. Hope it helps.

**Comment by jeromelaban** [comment]
We're still working out the details of sharing details, but here are some apps that have been published:
- https://itunes.apple.com/ca/app/jean-coutu/id351461407
- https://itunes.apple.com/ca/app/my-md-mobile/id1144752656
- https://itunes.apple.com/us/app/vca-careclub/id1172429469

**Comment by ghuntley** [comment]
Howdy folks,

As @jeromelaban has alluded to Uno has been essentively used by https://nventive.com/ to ship production applications to their customers. There's some they can talk about and a whole heap they cannot. 

If you are using Uno in production, we would love to hear about it. Please leave a comment below with where you are using Uno, what problems it solved for you and the platforms used. 

# template
```
<share a screenshot or two by dragging it onto the comment>

Author: 
Website: 

Apple Store: 
Android Store: 
Windows Store:
WebAssembly Url: 

If open-source, where is the git repo?:
```

**Comment by TopperDEL** [comment]
I'm using it for a - german - app to help my theater-group organize our Performances and Trainings. The app is open for everyone and Shows our next Performances. It has a secret area where only we can get into and work with it.
It currently is in beta - there are many todos left. :)
![Screenshot_20190523_202709_de vollemoehre mobilmoehre](https://user-images.githubusercontent.com/1833242/58277083-37bb4980-7d99-11e9-98ad-00eb78369474.jpg)
![Screenshot_20190523_202657_de vollemoehre mobilmoehre](https://user-images.githubusercontent.com/1833242/58277097-3db12a80-7d99-11e9-9434-51eee21eebc9.jpg)

Author: Tim Parth
Website: www.vollemoehre.de

Apple Store: not yet available
Android Store: [Store-Entry](https://play.google.com/store/apps/details?id=de.vollemoehre.mobilmoehre&hl=de)
Windows Store: not yet available
WebAssembly Url: not yet available

Unfortunately closed source, as this app is mostly for internal use.

**Comment by ghuntley** [comment]
Here's a list of live apps made with the Uno Platform for WebAssembly.

* The [Uno Platform Playground](https://playground.platform.uno) ([Source](https://github.com/nventive/Uno.Playground))
* The [Xaml Controls Gallery](https://xamlcontrolsgallery.platform.uno/) ([Source](https://github.com/nventive/Uno.Xaml-Controls-Gallery))
* The [Uno.WindowsCommunityToolkit](https://windowstoolkit-wasm.platform.uno/), ([Source](https://github.com/nventive/Uno.WindowsCommunityToolkit))
* The [Uno.Lottie](https://lottie.platform.uno/), a sample that uses the [AnimatedVisualPlayer](https://docs.microsoft.com/en-us/uwp/api/microsoft.ui.xaml.controls.animatedvisualplayer) ([Source](https://github.com/nventive/Uno.LottieSample))
* The [Uno.RoslynQuoter](http://roslynquoter-wasm.platform.uno/), a [Roslyn](https://github.com/dotnet/roslyn) based C# analysis tool ([Source](https://github.com/nventive/Uno.RoslynQuoter))
* The [Uno.BikeSharing360 App](http://bikerider-wasm.platform.uno/), a Xamarin.Forms app running on top of Uno for WebAssembly ([Source](https://github.com/nventive/Uno.BikeSharing360_MobileApps))
* The [Uno.WindowsStateTriggers App](http://winstatetriggers-wasm.platform.uno/), a demo of the [Morten's WindowsStateTriggers](https://github.com/dotMorten/WindowsStateTriggers) ([Source](https://github.com/nventive/Uno.WindowsStateTriggers))
* The [SQLite + Entity Framework Core App](http://sqliteefcore-wasm.platform.uno), a demo of the combination of [Roslyn](https://github.com/dotnet/roslyn), [Entity Framework Core](https://docs.microsoft.com/en-us/ef/core/), [SQLite](https://github.com/nventive/Uno.SQLitePCLRaw.Wasm) and the Uno Platform to manipulate an in-browser database.
* The [Uno.WebSockets App](https://websockets-wasm.platform.uno), a demo of System.Net.WebSocket running from WebAssembly ([Source](https://github.com/nventive/Uno.Wasm.WebSockets))
* A [mono-wasm AOT RayTracer](https://raytracer-mono-aot.platform.uno/)

**Comment by ghuntley** [comment]
Stumbled upon this tweet by @gritsenko.

https://twitter.com/Pix2d/status/1153326997029949441?s=09

Pix2D, an application for developing pixel art for games uses Uno!

![image](https://user-images.githubusercontent.com/127353/61765335-0229ef80-ae20-11e9-9dae-66543813d686.png)


https://play.google.com/store/apps/details?id=com.pix2d.pix2dapp&hl=en

**Comment by TopperDEL** [comment]
I did a sample-app for another open source component called "uplink.NET" (see [here](https://github.com/TopperDEL/uplink.net)). The library helps connecting to the storj-network ([storj.io](https://storj.io)) a private, secure and decentralized storage network.

The sample app shows how to use the library to upload and download files. It currently works on UWP and Android. iOs is not supported because uplink.NET does not have the necessary binaries.

![uplink1](https://user-images.githubusercontent.com/1833242/65378729-fe4e0880-dcbc-11e9-9c96-7e7aee2f1893.jpg)
![uplink3](https://user-images.githubusercontent.com/1833242/65378730-0148f900-dcbd-11e9-80dd-795778623593.jpg)
![uplink2](https://user-images.githubusercontent.com/1833242/65378732-06a64380-dcbd-11e9-99b2-7b7885121cd7.jpg)

**Comment by MartinZikmund** [comment]
I have brought my old Windows Phone app for purchasing SMS tickets to Android and iOS via Uno Platform. It is doing rather well, especially on Android where it has already over 3000 downloads and counting :-) . It uses some of the new APIs like SMS compose and JumpLists.

iOS App Store: https://apps.apple.com/us/app/czech-sms-ticket/id1477710726
Android Play Store: https://play.google.com/store/apps/details?id=com.sphereline.smsticketandroid


![EDeq6J2W4AUZpic](https://user-images.githubusercontent.com/1075116/65903157-37bcfd00-e3bc-11e9-8d3c-8817dc400e57.jpg)
![EDeq6eyWwAEG-Pg](https://user-images.githubusercontent.com/1075116/65903171-3ab7ed80-e3bc-11e9-8ddd-d2b849274b6c.jpg)
![EDeq71dXoAAHXTe](https://user-images.githubusercontent.com/1075116/65903177-3d1a4780-e3bc-11e9-8813-21dc69dadb06.jpg)

**Comment by mizzleinetimi** [comment]
i believe accunews makes use of it
https://www.accunewsapp.com/

**Comment by ghuntley** [comment]
The Monkey Fest conference website is built with Uno's Xamarin Forms WebAssembly custom renderers.

https://javiersuarezruiz.wordpress.com/2019/10/16/xamarin-forms-en-la-web-con-webassembly-y-uno/

Source code is available at https://github.com/jsuarezruiz/monkeyconf-website

**Comment by pkar70** [comment]
And my app, simple "merge" of Wikipedia 'today' pages from languages... As it seems that very different birthdays, deaths and events are celebrated in different language regions. In effect, you get more events  than in any single language.

https://play.google.com/store/apps/details?id=pkar.Anniversaries 

(only for Android, as I have no access to iOS to test).
UWP version: https://www.microsoft.com/en-us/p/a/9pjw858v28w8

**Comment by pkar70** [comment]
And my second app, simple "self-test" of character's dynamism. For two years, it was only UWP and only Polish; as I could not find where I can set default lang = "pl" in Uno, I added English version...

https://play.google.com/store/apps/details?id=pkar.MazurCiC

(only for Android, as I have no access to iOS to test).
UWP version: https://www.microsoft.com/en-us/p/d/9npj2m5d8lf4
UWP has one feature not present in Android version - prognosis of relation (e.g. marriage).

**Comment by pkar70** [comment]
My third app, public transport in Kraków (Poland).
 Android version is stripped-down version of UWP - e.g. MapControl doesnt work (so you cannot choose location from map), files in package cannot be referenced (so no history of tram network), no Grid.ContextFlyout (going to tram/bus route, and sorting, is unavailable).

https://play.google.com/store/apps/details?id=pkar.KrakTram

UWP version: https://www.microsoft.com/en-us/p/k/9nc74c3g8kgn

**Comment by pkar70** [comment]
My next app, current state of environment.
Android version is stripped-down version of UWP - e.g. MapControl doesnt work (so you cannot choose location from map), no tiles, no notification - because no timer background execuction, and no data exchange (no RemoteSystem).

https://play.google.com/store/apps/details?id=pkar.EnviroStatus

UWP version: https://www.microsoft.com/en-us/p/s/9PHHVVCP239D

**Comment by TopperDEL** [comment]
I've created "NutzMich", a German-App to rent and exchange children toys with other families of my home-town. It uses kind of a "web-of-trust" so that only know members can join the group - but the basic catalog can be browsed by anybody.
The app is open source and free for all. It uses [Storj](https://storj.io) as the backend so does not need any additional infrastructure - even for a simple chat. It get's deployed fully automatically via Azure DevOps to Google Play and the Apple Store.

Author: Tim Parth
Website: [NutzMich.de](https://www.nutzmich.de)
Apple Store: [NutzMich for iOs](https://apps.apple.com/us/app/nutzmich/id1545146982)
Android Store: [NutzMich for Android](https://play.google.com/store/apps/details?id=de.nutzmich.app)

![NutzMichScreenshot1](https://user-images.githubusercontent.com/1833242/104424923-4d8a0d80-5580-11eb-87f8-5c6b4ff504ee.png)
![NutzMichScreenshot2](https://user-images.githubusercontent.com/1833242/104424936-5084fe00-5580-11eb-8b70-3bf8313a3474.png)
