### ISSUE TITLE
[Android] `NavigationBar` PrimaryCommands unresponsive

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#18506]
## Current behavior

When I try to put AppBarButton in PrimaryCommands, it becomes unresponsive, the Command and Click doesn't work. When I put it outside of NavigationBar, everything works as expected. 

This seems to be a regression in the latest dev versions. I tested with `5.5.0-dev.40` and `5.5.0-dev.50`, on both the issue appears. 

## How to reproduce it (as minimally and precisely as possible)

```
      <utu:NavigationBar>
        <utu:NavigationBar.PrimaryCommands>
          <AppBarButton Icon="Favorite" Click="AppBarButton_Click" />
        </utu:NavigationBar.PrimaryCommands>
      </utu:NavigationBar>
          <AppBarButton Icon="Account" Click="AppBarButton_Click" />
```

[NavigationBarRepro.zip](https://github.com/user-attachments/files/17100634/NavigationBarRepro.zip)

Nuget Package:

Uno.Sdk `5.5.0-dev.50`

Affected platform(s):

- [ ] WebAssembly
- [x] Android
- [?] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows

**Comment by morning4coffe-dev** [comment]
@agneszitte, @vatsashah45, I did a quick round of tests as well and can reproduce this on both an emulator and an actual device with similar versions to the ones Agnès shared.

**Comment by kazo0** [comment]
I can repro as long as the Material styles are not used alongside Toolkit. Interesting

[UnoApp113.zip](https://github.com/user-attachments/files/17905958/UnoApp113.zip)

**Comment by rajamatt** [comment]
Following up on @kazo0's finding I could also only make the NavBar's AppBarButton work with Material. Then I tried removing Material entirely, at this point the issue is reproducible

However then I removed the Icon property from the AppBarButton and the command was being triggered again. So it seems to be related to the Icon in Fluent in a way or another. It is not working with a BitmapIcon defined either.

Next step would be to debug in here https://github.com/unoplatform/uno.toolkit.ui/blob/91c5efcb40ef385f98225c258ff60664c2735815/src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs#L167

**Comment by rajamatt** [comment]
Another update, turns out its being invalidated when clicking on the button since fluent is changing the opacity of the icon OnPressed: [these lines](https://github.com/unoplatform/uno.toolkit.ui/blob/91c5efcb40ef385f98225c258ff60664c2735815/src/Uno.Toolkit.UI/Controls/NavigationBar/AppBarButtonRenderer.Android.cs#L99C6-L100C105) show the Icon foreground is being observed. 

Will be removing these and adding a test for the scenario

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
I can confirm that this is fixed in the latest versions. I tested it today with latest **Uno.Sdk 5.6.22**. 
Other `NavigationBar` issues are tracked separately (like https://github.com/unoplatform/uno/issues/18545 for example).

---
Tested with:
- SDK/Templates: **5.6.22**
- VS version: VS 2022 (64-bit) - Version 17.12.4
- VS vsix: [5.6.15](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=153669)
- Solution used to test: [BlankAppWithToolkit.zip](https://github.com/user-attachments/files/18645577/BlankAppWithToolkit.zip)
