### ISSUE TITLE
[Desktop] PathGeometry filled up wrongly

### ISSUE THREAD

**Issue by kucint** [unoplatform/uno#18694]
### Current behavior

Draw an arrow on `Canvas` as follow:

```xaml
<Canvas>
    <Path Stroke="Black" StrokeThickness="1" Fill="LawnGreen" >
        <Path.Data>
            <PathGeometry>
                <PathGeometry.Figures>
                    <PathFigure StartPoint="100,100" IsClosed="False" IsFilled="False">
                        <PathFigure.Segments>
                            <BezierSegment Point1="150, 100"
                                     Point2="150, 200"
                                     Point3="200, 200"/>
                        </PathFigure.Segments>
                    </PathFigure>
                    <PathFigure StartPoint="220, 200" IsClosed="True" IsFilled="True">
                        <PathFigure.Segments>
                            <LineSegment Point="200, 190"/>
                            <LineSegment Point="200, 210"/>
                        </PathFigure.Segments>
                    </PathFigure>
                </PathGeometry.Figures>
            </PathGeometry>
        </Path.Data>
    </Path>
</Canvas>
```

On `Desktop` Framework the path is wrongly filled:

![image](https://github.com/user-attachments/assets/5ac29c02-905d-44e1-abb1-39108d787e0f)

On `WindowsSDK` Framework the path is working fine:

![image](https://github.com/user-attachments/assets/0e52bb2b-29ae-4f3a-b1c9-7e068b24a66c)

### Expected behavior

The `Desktop` Framework shall behave exactly as `WindowsSDK` Framework.

### How to reproduce it (as minimally and precisely as possible)

MINIMAL REPRO PROJECT: [UnoPathOnCanvasApp.zip](https://github.com/user-attachments/files/17632780/UnoPathOnCanvasApp.zip)

### Workaround

none

### Works on UWP/WinUI

Yes

### NuGet package version(s)

`"Uno.Sdk": "5.5.32"`

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can this issue with latest internal 5.6 stable please

**Comment by agneszitte** [comment]
@ramezgerges I tested this issue today with latest **Uno.Sdk 5.6.22** on all platforms, and now it is properly fixed for Desktop and Desktop WSL, but the issue is still happening for **WebAssembly**, **Android**, **iOS**, **macOS** (see images below).

I have opened https://github.com/unoplatform/uno/issues/19430 to track the issue for the other platforms.

---
Tested with:
- SDK/Templates: **5.6.22**
- VS version: VS 2022 (64-bit) - Version 17.12.4
- VS vsix: [5.6.15](https://dev.azure.com/uno-platform/uno-private/_build/results?buildId=153669)
- Solution used to test: [BlankAppVSWizardNet9.zip](https://github.com/user-attachments/files/18649192/BlankAppVSWizardNet9.2.zip)

| Platform        | Screenshot |
|----------------|------------|
| **WebAssembly** (Same behavior on Edge, Chrome, Firefox) | <img src="https://github.com/user-attachments/assets/317bfbbb-d24d-4fc1-81a9-0e0057eee6b1" width="200"/> |
| **Android** | <img src="https://github.com/user-attachments/assets/1a20af48-e2ba-4df1-a506-3af74c1d2647" width="200"/> |
| **iOS** | <img src="https://github.com/user-attachments/assets/62040bdb-b11b-4941-a3a0-2ff758c5f0e5" width="200"/> |
| **WinAppSdk** | <img src="https://github.com/user-attachments/assets/e2b6e465-e055-462d-9b31-4b9eaf30407f" width="200"/> |
| **Desktop** | <img src="https://github.com/user-attachments/assets/5a312f0e-a7a4-446b-8356-f9e569f8edac" width="200"/> |
| **Desktop WSL** | <img src="https://github.com/user-attachments/assets/fcb90b64-d362-4314-98fb-eb969b9744fa" width="200"/> |
