### ISSUE TITLE
Empty project does not build

### ISSUE THREAD

**Issue by AP2020C** [unoplatform/uno#18713]
### Current behavior

All of this is **SCANDALOUS**! I create an **empty** project, open Presentation\MainPage.xaml and it finds 1000 errors!
And, of course, it doesn't build.
I understand that this is my first Uno project and that I might make programming mistakes, but it is **wrong** to have to correct the platform's mistakes before even making my own.

### Expected behavior

I would like that at project creation I find an empty but buildable project with an interface similar to VB form projects. And, in this regard, I would like VB to be supported as well as C#!
When I install Platform One in VS it should instal all the necessary components.
Otherwise, I will abandon Uno forever by putting it in the same circle of hell as Maui and Xamarin.

### How to reproduce it (as minimally and precisely as possible)

Create a project

### Works on UWP/WinUI

None

**Comment by MartinZikmund** [comment]
Please avoid harsh tone and keep things friendly.

Have you followed our [getting started guide](https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=ubuntu1804)? Most crucially - have you run `uno-check`?

**Comment by DevTKSS** [comment]
@AP2020C for those who might could help or fix any problem, you maybe should add some information e.g:
which Template/UI do you tryed to use: WPF, WinUI (most of the time the template which is listed on first place), Xamarin/.Net 6?
which UI Markup: Xaml/C#?
which Binding Stategy: Mvvm/Mvux?

Just trying to help. I am also coming freshly from VB.NET and WinForms and its kind of a hard step to get used to the new UI definition and Binding behind which was (like you said) much easyer in Winforms Applications. Not beeing able to use VB language in "modern/new" applications (also tryed Maui before, didnt build on my maschine like you told here with uno and there were all around said, no one had this problem which was really frustrating!) is also annoying to me, but I don't think that will change at all in any soon time, because VB is (my stand of knowledge) not longer activ developed from Microsoft.
But on uno here I did make the experience in the last days since I did start like you, the community and also the uno team here and on discord is really trying to help and to fix bugs where they are seeing the chance in my opinion, there are also contributing developers I got to knew in last days here and on discord, out there which are listing the issues they get confronted to also trying to help where they can. 

That's what the definition of each open source software should be and I think if you are only giving them all just a fair chance to help you with the problem you got now or later confronted with, you might be positiv surprised.

If you want a perfect software, that will never ever have a bug, lets tell, even VB.NET and WinForms I did find enough bugs which are way more annoying and that is much longer developed than uno here ;)

**Comment by AP2020C** [comment]
I tried to follow getting started guide. During uno-check i got
`! There were one or more problems detected.
Please review the errors and correct them and run uno-check again.`
After installing numerous packages. And I have no idea how to check for errors, since others I haven't seen.
Above all, I would like to say that a one-click installation is very welcome!
I had created a "Uno platform app".

**Comment by DevTKSS** [comment]
@AP2020C okay that was a text it also prompted me :) Can you tell, if in the text in the console, it wrote there, you might see any red line, which could tell about the failing element or is it (like mine on installing) saying to each of its tasks, it had no problem?
If it is saying last of mentioned options, please have a look on the Troubleshooting area here: https://platform.uno/docs/articles/external/uno.check/doc/using-uno-check.html?tabs=windows#install-and-run-uno-check

**Comment by jeromelaban** [comment]
> I tried to follow getting started guide. During uno-check i got `! There were one or more problems detected. Please review the errors and correct them and run uno-check again.`

Can you paste the output of Uno.Check here? You can also run `uno-check --verbose` to have more information.
