### ISSUE TITLE
WebView2 Sample Code not working

### ISSUE THREAD

**Issue by datovy-edam** [unoplatform/uno#18767]
### On which page?

https://platform.uno/docs/articles/controls/WebView.html

### What's wrong?

I created a brand-new project using uno platform templates (5.3) and updated the MainPage.xaml as follows:

```
<Page x:Class="UnoApp2.MainPage"
      xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
      xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
      xmlns:local="using:UnoApp2"
      xmlns:utu="using:Uno.Toolkit.UI"
      xmlns:um="using:Uno.Material"
      Background="{ThemeResource BackgroundBrush}">
    <Grid BorderBrush="Gray" BorderThickness="1" Padding="10">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
            <RowDefinition Height="Auto" />
        </Grid.RowDefinitions>
        <StackPanel Grid.Row="0" Background="LightBlue">
            <TextBlock Text="Hello" />
        </StackPanel>
        <WebView2 Grid.Row="1" x:Name="WebBrowser" />
        <StackPanel Grid.Row="2" Background="LightBlue">
            <TextBlock Text="Goodbye" />
        </StackPanel>
    </Grid>
</Page>
```
Following the sample I wrote "MainPage.xml.cs":
```
using Microsoft.Web.WebView2.Core;

namespace UnoApp1.Presentation;

public sealed partial class MainPage : Page
{
    public MainPage()
    {
        this.InitializeComponent();
        InitAsync();
    }
    public async Task InitAsync()
    {
        try
        {
            await WebBrowser.EnsureCoreWebView2Async();
            WebBrowser.CoreWebView2.SetVirtualHostNameToFolderMapping(
                "UnoNativeAssets",
                "WebContent",
                CoreWebView2HostResourceAccessKind.Allow);
            WebBrowser.CoreWebView2.Navigate("http://UnoNativeAssets/index.html");
        }
        catch (Exception ex)
        {

        }
    }
}
```
The above does not work in WinAppSDK, neither in WebAssembly.

Can you provide a VS (uno 5.2 and 5.3) simple Project that does work for both Win and WebAssembly targets?

I do have a project using (I guess) uno 5.2 with .Net 8.0 in where WebView2 works in WinAppSDK but not in WebAssembly.  It looks like WebView2 is not implemented under WebAssembly in this case.

**ANOTHER WEBVIEW2 ISSUE**

Actually, that other application (see "https://github.com/datovy-edam/Edam.Data.Catalog") is using the Monaco Editor sample code in the uno-platform that uses WebView2 to view the editor and works as expected in WinAppSDK, but not in WebAssembly.

Any sugestions?

Hope to hear from you soon,

Eduardo

**Comment by jeromelaban** [comment]
Thanks for the report.

WebView2 support is in progress for some platforms, but we added support for Web in uno 5.5. It's required to upgrade the latest builds to use that feature.

**Comment by jeromelaban** [comment]
Fixed in https://github.com/unoplatform/uno/pull/18872

**Comment by agneszitte** [comment]
@jhanvi03, @Darsh0307 if you can test this issue with latest internal 5.6 stable please

**Comment by lucaregini** [comment]
I am experiencing the same problem. The issue here seems that EnsureCoreWebView2Async doesn't guarantee complete initialization of the webview and therefore calling SetVirtualHostNameToFolderMapping immediatly after is ignored.
Putting a 1 second delay between the two calls results in the code working. In addition to that I believe that calling InitAsync in the constructor is wrong as we have to make sure that the webview is loaded so it should be called in an event handler.

With respect to determining which event handler is the best I tried several combinations of events without much success. Calling SetVirtualHostNameToFolderMapping in CoreWebView2Initialized doesn't work either. The best that I found is calling it in the NavigationStarting event and this somewhat works but shows a glitch: the event is called twice for the same url and the first time it results in the "ip not found message" while the second time it works as expected and the folder is mapped. This results in flash where you can see for a moment the error and then the local page is displayed correctly. Can somebody shed some light on the issue?
