### ISSUE TITLE
VS Template doesn't build after updatting Microsoft.Extensions.Logging.Console

### ISSUE THREAD

**Issue by MikePelton** [unoplatform/uno#2013]
Tried to go through the "getting started" guide yesterday and struggled. When I stepped back to simply creating a new Cross-Platform App (Uno)  - i.e. just loading the template - the build fails. Specific issues are to do with the call to AddConsole in ConfigureFilters - that method seems to have gone from Microsoft.Extensions.Logging.Console. I've tried 3.0.0 and the v3.1.0-preview, both fail.

Also there's an implicit dependency on .NET 4.6.2 from the WASM side, which needs to be resolved by adding the 4.6.2 Targeting Pack - the documentation should call that out.

It's important that the initial experience is positive, so while these might seem like small issues, if I'd had less time to persevere I'd have given up, which would be a shame as Uno looks as though it will address many challenges for us

VS2019 16.3.7, Windows 10 Home 1903

**Comment by MikePelton** [comment]
Looks like the call to .AddConsole needs to be replaced with a call to .CreateLogger?

**Comment by jeromelaban** [comment]
Thank your for your report @MikePelton.

This isn't technically out of the box, since updates to the original packages have been made. The updated packages for the Loggers are not yet supported, particularly regarding some breaking changes made to the latest 3.0 updates. This is a missing nuget feature that would be nice to have in Visual Studio, w.r.t notifying of breaking changes.

Also, Uno only supports the version 1.1.1 of the debug loggers because of the missing threading support for wasm. You may have noticed this line:
https://github.com/unoplatform/uno/blob/f6b2b03d53d1a3303004fd075853ddb6bb64558d/src/SolutionTemplate/UnoSolutionTemplate/Wasm/UnoQuickStart.Wasm.csproj#L45.

As for the net462 dependency, it's going to be fixed by  https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/134

**Comment by MikePelton** [comment]
Take your point re the package updates, but the "[getting started](https://platform.uno/docs/articles/getting-started-tutorial-1.html)" page explicitly advises it - maybe it would be safer not to? Thanks for coming back so fast - sounds like you're very much on the case!

**Comment by jeromelaban** [comment]
True! Thank you for point this out, this indeed not correct. We need to adjust that.

**Comment by dansiegel** [comment]
@jeromelaban this used to build from `File -> New Project`, it's absolutely less than ideal that the template doesn't generate a buildable solution.
