### ISSUE TITLE
[WASM] Textblock runs and \n don't create new line

### ISSUE THREAD

**Issue by soriyathach** [unoplatform/uno#2025]
## Current behavior

All the text is displayed only one line:
Text on line 1. Text on line 2.

## Expected behavior

The text should be displayed on two lines just like other platforms:
Text on line 1.
Text on line 2.

## How to reproduce it (as minimally and precisely as possible)
Set this text in resources:
```
<data name="MyContent.Text" xml:space="preserve">
    <value>Text on line 1.
Text on line 2.</value>
</data>
```
and a common textblock:
```
<TextBlock x:Uid="MyContent"
		uloc:Localize="Text"/>
```

## Environment

Nuget Package:

Package Version(s):
UNO.UI 1.46.196-dev.2440
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.2.0 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Please try to add `white-space: pre` into the `Uno.UI.css` file...
https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Wasm/WasmCSS/Uno.UI.css#L56

**Comment by agneszitte-nventive** [comment]
@carldebilly / @jeromelaban Issue closed.
Fixed with latest dev (Tested with: **Uno.UI 3.1.0-dev.39** on **UWP/iOS/Android/WASM/MacOS**)

![image](https://user-images.githubusercontent.com/16295702/90428799-86d25600-e092-11ea-8639-8f25479a47f1.png)
![image](https://user-images.githubusercontent.com/16295702/90430417-65269e00-e095-11ea-993c-9f0a39a8e4ba.png)
