### ISSUE TITLE
[Wasm] non-virtualized lists are incorrectly allowing scrolling

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2111]
## Current behavior

The home page of XAML Controls gallery allows for scrolling: https://xamlcontrolgallery-xamlcontrolgallery-staging.azurewebsites.net/

## Expected behavior

The scrolling should not be enabled if the list fills the whole available space.

## How to reproduce it (as minimally and precisely as possible)

https://xamlcontrolgallery-xamlcontrolgallery-staging.azurewebsites.net/

## Environment

Package Version(s): 2.0.512-dev.3976

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This is due to a weird behavior (a.k.a. bug) of webkit (this works properly on Edge) which seems to be caused by the [`transform: translate(0, 0);` that we added on all `UIELement` in order to be able to properly measure text and images](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Wasm/WasmCSS/Uno.UI.css#L38).

It was hidden by the fact that we where clipping almost all elements, but this is no longer the case since https://github.com/unoplatform/uno/pull/1726.

**Comment by paulovila** [comment]
Also note that when you rotate a button the clicking area does not rotate
```xml
<ItemsControl.ItemTemplate>
    <DataTemplate x:DataType="viewModels:ButtonViewModelBase">
        <Button VerticalAlignment="Stretch" HorizontalAlignment="Stretch"
                Command="{Binding }" Content="{Binding Text}" >
            <Button.RenderTransform>
                <CompositeTransform Rotation="-22.246"/>
            </Button.RenderTransform>
        </Button>
    </DataTemplate>
</ItemsControl.ItemTemplate>
```
![image](https://user-images.githubusercontent.com/888391/69379418-58148400-0ca8-11ea-9176-0f528060ef87.png)
So if you click in the corners of the button it doesn't work
