### ISSUE TITLE
[Playground][Wasm][Chrome][Grid] TextBox does not clear on single click of clear button

### ISSUE THREAD

**Issue by StewartPolsky** [unoplatform/uno#2201]
## Current behavior

![playground text clear bad](https://user-images.githubusercontent.com/49959074/69673262-efdaef00-1067-11ea-99c6-a18349776b9b.gif)

## Expected behavior

![playground text clear good](https://user-images.githubusercontent.com/49959074/69673270-f36e7600-1067-11ea-8ec5-8964563087fb.gif)

## How to reproduce it (as minimally and precisely as possible)

Visit https://playgroundcanary.z19.web.core.windows.net/#grid
Enter text in any TextBox
Attempt to clear TextBox 
Notice that clicking "X" does not clear text after one click

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Related to https://github.com/unoplatform/uno/issues/2138

**Comment by francoistanguay** [comment]
Isn't this fixed in latest?

**Comment by MartinZikmund** [comment]
> **Reopened by this audit** — the issue was closed, but items from its own Definition of Done are still outstanding on `feature/breakingchanges`.

**Audit result: PARTIALLY DONE** in `feature/breakingchanges` (as of `43acbf69dd`).

The public/protected surface of `Uno.UI`, `Uno.UWP`, `Uno.Foundation`, `Uno.UI.Composition` and `Uno.UI.Dispatching` was swept against the WinAppSDK reference assemblies and eight accidental narrowings were widened. A follow-up cross-check against Uno's own generated reference metadata still finds two constructor-level narrowings that were not caught.

- **`Uno.UI` widenings verified on branch** — `src/Uno.UI/UI/Xaml/Controls/Repeater/ItemsRepeaterScrollHost.cs:229/231` now `public double HorizontalAnchorRatio` / `VerticalAnchorRatio`; `src/Uno.UI/UI/Xaml/Controls/Repeater/ItemsSourceView.cs:53` now `public int IndexOf(object item)`; `src/Uno.UI/UI/Xaml/Controls/ScrollPresenter/SnapPoint.cs:614/616` and `:1495/1497` now `public double Start` / `End`.
- **`Uno.UWP` widenings verified on branch** — `src/Uno.UWP/Graphics/PointInt32.cs:8`, `RectInt32.cs:10` and `SizeInt32.cs:10` declare public constructors, so `new PointInt32(x, y)` / `new SizeInt32(w, h)` compile against Uno as they do against WinAppSDK.
- **Originating defect** — `Hyperlink.UnderlineStyleProperty` is public (`src/Uno.UI/UI/Xaml/Documents/Hyperlink.cs:120`). unoplatform/uno#23653 targeted `master`; the fix reached this branch via the automated sync rather than directly.
- **Cross-checked** — all eight widenings corroborated against the WinUI IDL (`ItemsRepeater.idl:379-392` and `:146`, `ScrollPresenterPrimitives.idl:70-78`). A separate sweep for protected-in-Uno / public-in-WinUI members returned nothing, and the `internal` overloads that surfaced (e.g. `FlyoutBase.Hide(bool)`, `DependencyProperty.Register` internal overloads, `UIElement.Focus(FocusState, bool, ...)`) all have a public sibling, so they are not narrowings.

**Fixed by** unoplatform/uno#23668, unoplatform/uno#23653

### Remaining

- [ ] `src/Uno.UI/UI/Xaml/Controls/ColorPicker/ColorPickerSliderAutomationPeer.cs:14` — `internal ColorPickerSliderAutomationPeer(ColorPickerSlider owner)` on a `public partial class` should be `public`. The generated reference declares the identical signature (`src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Automation.Peers/ColorPickerSliderAutomationPeer.cs:11`), and the siblings `SliderAutomationPeer.cs:22` / `ColorSpectrumAutomationPeer.cs:26` are already `public`. Same defect shape as unoplatform/uno#23653.
- [ ] `src/Uno.UI/UI/Xaml/Media/Animation/ObjectKeyFrameCollection.cs:9` — the sealed class's only constructor is `internal ObjectKeyFrameCollection(DependencyObject, bool)`; the reference declares a public parameterless `ObjectKeyFrameCollection()` (`src/Uno.UI/Generated/3.0.0.0/Microsoft.UI.Xaml.Media.Animation/ObjectKeyFrameCollection.cs:14`, `microsoft.ui.xaml.coretypes.idl:3108-3111`). Siblings `DoubleKeyFrameCollection.cs:12` and `ColorKeyFrameCollection.cs:7` already expose public parameterless constructors, so `new ObjectKeyFrameCollection()` compiles against WinAppSDK but not Uno. Neither of these is a CsWinRT composability artifact, so the PR's projection-artifact rule-out does not cover them.
- [ ] No verification tooling or regression guard was committed, so the sweep is a one-shot snapshot. Consider committing the audit tool, or a unit test over the generated `// Skipping already declared method` markers, so this cannot silently regress.

_Audit is code inspection against the branch worktree; no build or runtime validation was performed._
