### ISSUE TITLE
WASM version hangs at splash screen after adding ReactiveUI.Uno

### ISSUE THREAD

**Issue by 33kelder** [unoplatform/uno#2204]
## Current behavior

WASM version hangs at splash screen

## Expected behavior

Should display MainPage, as UWP version does

## How to reproduce it (as minimally and precisely as possible)

[Test project repository](https://github.com/oakrefactory/ReactiveUNO)

## Environment

Nuget Package: 
"ReactiveUI.Uno" Version="10.5.31"
"Splat.Drawing" Version="9.2.7"
"Uno.UI" Version="2.0.512-dev.4129"
"Uno.Wasm.Bootstrap" Version="1.0.5"

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

Happens also after adding MvvmCross.Uno following [Nicks travels](https://nicksnettravels.builttoroam.com/uno-with-mvvmcross/)

**Comment by jeromelaban** [comment]
Thanks for the report @oakrefactory. Could you provide a gist of the outpout of the browser debugger ?

**Comment by Massimo37** [comment]
Relating this to #2149 since both issues mention a hang at splash screen on Wasm

**Comment by oakrefactory** [comment]
I got the following output:
`
>>mono_wasm_runtime_ready
mono.js:1 ﻿The Bindable attribute is missing and the type [Windows.UI.Xaml.UnsetValue] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.
6mono.js:1 The Bindable attribute is missing and the type [Windows.UI.Xaml.UnsetValue] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.
mono.js:1 LogHost: Initializing to normal mode
mono.js:1 LogHost: It seems you are running .NET Standard, but there is no host package installed!
mono.js:1 
mono.js:1 LogHost: You will need to install the specific host package for your platform (ReactiveUI.WPF, ReactiveUI.Blazor, ...)
mono.js:1 
mono.js:1 LogHost: You can install the needed package via NuGet, see https://reactiveui.net/docs/getting-started/installation/`

Running the [reactive sample](https://github.com/reactiveui/ReactiveUI.Samples/tree/master/uno) as mentioned in #2149 
`
RoutedViewHost: Couldn't find an IPlatformOperations implementation. Please make sure you have installed the latest version of the ReactiveUI packages for your platform. See https://reactiveui.net/docs/getting-started/installation for guidance.
mono.js:1 WASM doesn't support threading
mono.js:1 fail: Windows.UI.Core.CoreDispatcher[0]
mono.js:1       Dispatcher unhandled exception
mono.js:1 System.Exception: Failed to load Page ReactiveUI.UwpRouting.Views.MainView
`

**Comment by grahamehorner** [comment]
I'm seeing the same type of issue with a number of example sites; where mono.js throws an exception -> Memory index is out of range

**Comment by bcaceiro** [comment]
I am getting the same, tring to run  Xamarin.Forms based project on Uno. Any solutions?

The Bindable attribute is missing and the type [UWP.MainPage] is not known by the MetadataProvider.

**Comment by ushenkodmitry** [comment]
Same here with Uno 3.0.5 and ReactiveUI 11.26.5. 
Seeing only blue splash screen on launch. Some output in console:
`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Don't know how to detect when ReactiveUI.Uno.RoutedViewHost is activated/deactivated, you may need to implement IActivationForViewFetcher`

**Comment by Rhorandir** [comment]
Hi, 
I had the same issue and search a lot and landed here aswell, so I would like to comment my solution to this issue in case, someone else lands here too.
According to Uno Platform Docs, this issues results from a missing library in the LinkerConfig.xml file:
I added:
<assembly fullname="ReactiveUI.Uno" /> to the LinkerConfig.xml

**Found here:**
[Uno Platform - Get Started Wizard](https://platform.uno/docs/articles/get-started-wizard.html)
Search for:
Don't know how to detect when XXX is activated/deactivated, you may need to implement IActivationForViewFetcher (ReactiveUI)

[Uno Platform - LinkerConfig.xml](https://platform.uno/docs/articles/features/using-il-linker-webassembly.html)

**Comment by Massimo37** [comment]
@Rhorandir  thanks for posting a workaround 👍

**Comment by Rhorandir** [comment]
@Massimo37 you're welcome ;-) 
#2149 I think so, atleast I had a very similar behaviour. I'm also using the IRoutableViewModel and it failed at the first try load the first page, that implements a RoutedViewHost Element and is derived from the ReactivePage. The matching viewModel is derived from the ReactiveObject and Implementes the IRoutableViewModel.
I actually followed the getting started here: https://platform.uno/blog/getting-started-with-uno-platform-and-reactiveui/

And when I'm missing the entry in the LinkerConfig.xml the splashscreen dont disappear and the website is not working.
My error message is as follows.:
Don't know how to detect when [MyNamespace].NavigationPage is activated/deactivated, you may need to implement IActivationForViewFetcher

In my example the error appears during OnLaunched in the App-Class , I guess, because I'm adding there a view and a viewmodel to the Windows.UI.Xaml.Window.Current.Content for the first time.

I also had once a similar behaviour for the WebAssembly-Project (freezing in Splashscreen) and the LinkerConfig.xml did the fix there too, but I cannot remember which Framework/Library was the problem a that time.

**Comment by Massimo37** [comment]
@Rhorandir  thanks for the detailed explanation!! 👍

**Comment by MartinZikmund** [comment]
The workaround of adding the entry to `LinkerConfig.xml` is the correct solution:

```
<assembly fullname="ReactiveUI.Uno" />
```

Closing this for now.
