### ISSUE TITLE
Build error "Failed to execute the linker"

### ISSUE THREAD

**Issue by bPoller2810** [unoplatform/uno#2272]
i set up a new uno Xamarin.forms project, 

NuGet Versions:
Uno.Wasm.Bootstrap v1.0.8
Uno.Xamaron.Forms.Platform v4.1.0-uno.125
Xamarin.Forms v4.3.0.991221

every time i build the project i get a linker error:

```
3>C:\Users\bpoll\.nuget\packages\uno.wasm.bootstrap\1.0.8\build\Uno.Wasm.Bootstrap.targets(125,5): error : System.Exception: Failed to execute the linker
3>C:\Users\bpoll\.nuget\packages\uno.wasm.bootstrap\1.0.8\build\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v680e650b8838ea96c5ecb6eaea5ea2e3f69e06d3.RunPackager() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 529
3>C:\Users\bpoll\.nuget\packages\uno.wasm.bootstrap\1.0.8\build\Uno.Wasm.Bootstrap.targets(125,5): error :    at Uno.Wasm.Bootstrap.ShellTask_v680e650b8838ea96c5ecb6eaea5ea2e3f69e06d3.Execute() in D:\a\1\s\src\Uno.Wasm.Bootstrap\ShellTask.cs:line 149
3>Done building project "PROJECTNAME.Wasm.csproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========
```

The UWP project runs as exprected(if this information may be helpfull)

Is this problem known or did i just screw up anywhere in setting up the project? 
(if you need more informations just let me know i send you what i have).

**Comment by jeromelaban** [comment]
@bPoller2810 Thanks for the report! You most probably need to adjust the `LinkerConfig.xml` file. If you set the build log level to "normal" or "detailed", you should be seeing more information.

**Comment by bPoller2810** [comment]
i went back to pure platform.uno. Using the Xamarin forms integration was just to see if i can speed up my development(as i am mainly working in xamarin forms on frontent projects) by using all the familiar controls etc.

maybe later today i build back to the state i had yesterday while my error occured. i will try your tip then.

**Comment by jeromelaban** [comment]
Thanks, let us know what you find.

**Comment by pauldiston** [comment]
I have run into this issue when trying to get a sample running based on the instructions here - https://platform.uno/xamarin-forms/

Having found out that I need to use a Shared project rather than the steps in the link, now when I compile the solution I get a _System.Exception: Failed to execute the linker_ raised and looking at the Output window, I find the following :-

3>    Mono.Linker.Steps.XmlResolutionException: Failed to process XML description: resource UnoSample.UWP.Wasm.xml in UnoSample.UWP.Wasm, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnoSample.UWP, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'UnoSample.UWP, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'

I don't use Shared Projects at all so I am not sure whether my solution is setup correctly and having misleading instructions doesn't help the situation.

Is there a clearer set of step by step instructions about how to setup a Xamarin.Forms solution with Uno?

**Comment by pauldiston** [comment]
I have now reviewed the LinkerConfig.xml and removed references to the UWP project and I am now able to run up the sample I have been working on.

**Comment by jeromelaban** [comment]
@pauldiston Thanks for the update.

If you can, could you provide us with a solution similar to the one you got to work so we can update the steps ? Thanks !
