### ISSUE TITLE
Classes implementing ComboBox do not render

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2404]
## Current behavior

In Android and Wasm any custom class implementing ComboBox is not rendered.

## Expected behavior

ComboBox should render as on UWP.

## How to reproduce it (as minimally and precisely as possible)

Start the attached solution in UWP and observe the red combobox.  Launch in Android and Wasm and observe that the combobox is not drawn.
[ComboboxAndroid.zip](https://github.com/unoplatform/uno/files/4005585/ComboboxAndroid.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.1.0-dev.481
Affected platform(s):

- [?] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This is issue is related to https://github.com/unoplatform/uno/pull/1766, where the `DefaultStyleKey` is not taken into account.

For an inherited control to work, you need to define either an implicit style or a named style for your new control  type.

**Comment by DierkDroth** [comment]
@jeromelaban any chance to get the PR referenced merged?

**Comment by peternary** [comment]
I've tried creating a named style and assigning it but that doesn't appear to be working.  Sample attached

[ComboboxAndroid_with_style.zip](https://github.com/unoplatform/uno/files/4005887/ComboboxAndroid_with_style.zip)

**Comment by jeromelaban** [comment]
@DierkDroth this PR is still in the works, with lots of validation left to do. Most of the issues fixed by this PR can be worked around with some additional styling that is compatible with the normal behavior of WinUI.

@peternary you need to redefine the style completely, not just parts of it. This is something that the mentioned PR will also address. For the `ComboBox`, take a [complete copy of the original style](https://github.com/unoplatform/uno/blob/89142db1823df3a9bbc8d04c561c6b929da6cdaa/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L478). Best is to place the style in a `ResourceDictionary` referenced from `App.xaml`.
