### ISSUE TITLE
RenderTransform not being applied on IOS and causing clipping on IOS 

### ISSUE THREAD

**Issue by harmanlamba** [unoplatform/uno#2486]
## Current behavior

Render transforms do not work on IOS at all. On Android, they do work, but the rotation transform clips the control that is being rotated. (Repro Project linked). The control, in this case, are Polylines and Paths. 

## Expected behavior

RenderTransforms working on IOS, and not clipping controls on Android. 

## How to reproduce it (as minimally and precisely as possible)

Simply run the UWP head first. This will show the way the transform is supposed to look like. Consequently, when running the Android Head, one will notice that the arrow as its rotated the top half gets clipped. On IOS, one will notice that the arrow does not translate, nor do the TextBlocks.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.716

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The link to the solution is:  
https://drive.google.com/file/d/1n2u_KeurnM-o8GUpTw1Irr22Y_uekHDS/view?usp=sharing

**Comment by carldebilly** [comment]
Could be related to https://github.com/unoplatform/uno/issues/2441

**Comment by dr1rrb** [comment]
This has been fixed with Uno 3.0

UWP:
![image](https://user-images.githubusercontent.com/8635919/91369422-c0fdcf00-e7d9-11ea-9f86-db41c50d4c55.png)

Android:
![image](https://user-images.githubusercontent.com/8635919/91369415-bb07ee00-e7d9-11ea-9d51-1d3cffc878b1.png)

iOS:
![image](https://user-images.githubusercontent.com/8635919/91369403-b17e8600-e7d9-11ea-887c-6403ec276105.png)
