### ISSUE TITLE
Support for assets provided by library

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#2502]
## Current behavior
1. I create project with template "Cross-Platform Library".
2. Add the image file to the Assets directory of this project.
3. Set the build action to Content.
4. xaml
`<Image Source="ms-appx:///Bs.Kehu/Assets/header.png" />`

The image is displayed in uwp and android. But in iOS:
```
2020-01-20 11:05:49.261049+0800 UnoApp[12385:168687] \^[[41m\^[[30mfail\^[[39m\^[[22m\^[[49m: Windows.UI.Xaml.Media.ImageSource[0]
      Unable to locate bundle resource [ms-appx:///Bs.Kehu/Assets/header.png]
```
Maybe it's not a bug. But I failed to get any help about this. I propose to add some help about this. 
Thanks!

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report! Indeed, this scenario is not yet supported.

**Comment by MartinZikmund** [comment]
@ajpinedam Are you planning to look into this?

**Comment by Juansero29** [comment]
This could be very useful for our use case, specially for fonts assets

**Comment by jeromelaban** [comment]
Until this issue is fixed, when working with a solution which contains a project with custom assets (assuming it is in a project named `MyLibrary` and the assets are located in a folder named `Assets`), a workaround can be to include the files as content from the consuming project (a project head, for instance), as such:

```xml
<ItemGroup>
    <Content Include="..\MyLibrary\Assets\**" Link="Assets\%(RecursiveDir)\%(FileName)%(Extension)" />
</ItemGroup>
```

This content could be located in a separate msbuild file (e.g. `ProjectAssets.props`), such as this one:
```xml
<Project>
   <ItemGroup>
      <Content Include="$(MSBuildThisFileDirectory)Assets\**" 
               Link="Assets\%(RecursiveDir)\%(FileName)%(Extension)" />
   </ItemGroup>
</Project>
```
And include it in the projects heads as follows:
```xml
<Import Project="..\MyLibrary\ProjectAssets.props" />
```

The path of the assets will local to the project head, though, with this workaround. WinUI prefixes assets with the library containing the assets (e.g. `ms-apps://MyLibrary/Assets/MyAsset.txt`), and this workaround will not include the library name.

The same workaround can be applied to nuget packages, and [the `contentfile` convention.](https://docs.microsoft.com/en-us/nuget/reference/nuspec#contentfiles)
