### ISSUE TITLE
[Wasm] Assembly load exception when adding reference to Entity Framework 3.x

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2518]
## Current behavior

Adding a reference to a project using Entity Framework Core 3.x produces an exception 
"Could not load file or assembly Microsoft.Bcl.AsyncInterfaces" **in the WebAsembly head**. This doesn't seem to affect other heads. For instance, the UWP doesn't expose this problem.

The exact message can be found in the browser console (using the integrated Dev Tools)

> System.Exception: Failed to load TestApp.MainPage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
mono.js:1   at (wrapper managed-to-native) System.Reflection.RuntimeConstructorInfo.InternalInvoke(System.Reflection.RuntimeConstructorInfo,object,object[],System.Exception&)
mono.js:1   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00005] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:936 
mono.js:1    --- End of inner exception stack trace ---
mono.js:1   at System.Reflection.RuntimeConstructorInfo.InternalInvoke (System.Object obj, System.Object[] parameters, System.Boolean wrapExceptions) [0x00018] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/corlib/System.Reflection/RuntimeMethodInfo.cs:944 
mono.js:1   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00095] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/corlib/ReferenceSources/RuntimeType.cs:185 
mono.js:1   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean wrapExceptions, System.Boolean skipCheckThis, System.Boolean fillCache) [0x00009] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/corlib/ReferenceSources/RuntimeType.cs:155 
mono.js:1   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Boolean wrapExceptions, System.Threading.StackCrawlMark& stackMark) [0x00027] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/mscorlib/system/rttype.cs:5729 
mono.js:1   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic, System.Boolean wrapExceptions) [0x00039] in /mnt/jenkins/workspace/test-mono-mainline-wasm/label/ubuntu-1804-amd64/mcs/class/referencesource/mscorlib/system/activator.cs:206 

## Expected behavior

The application should start properly.

## How to reproduce it (as minimally and precisely as possible)

Please, use the zipped solution below and run the WASM head.
[TestApp.zip](https://github.com/unoplatform/uno/files/4097463/TestApp.zip)

The solution has nothing remarkable except that:
- It uses `Entity Framework Core`
- The `WasmShellILLinkerEnabled` is set to `false` in the WASM head.

## Environment

Package Version(s):
2.1.0-dev.799

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment]
Interesting issue. It seems that the wasm packager is using the reference assembly of that assembly instead of the real one: 

```
Image for assembly 'Microsoft.Bcl.AsyncInterfaces' (Microsoft.Bcl.AsyncInterfaces.dll) has ReferenceAssemblyAttribute, skipping
```

We'll have to fix it for this to work properly.

**Comment by SuperJMN** [comment]
OK, I have spent like an hour to downgrade to EF Core 2.2.6 😅 and I have confirmed that it works perfectly. I guess the problem was introduced with EF Core 3.x.

Thanks for your help!

**Comment by SuperJMN** [comment]
Hi! Is there something I can do to help with this?

**Comment by jeromelaban** [comment]
This is an issue related to the way the Bootstrapper determines the location of the implementation assemblies, and maybe related to .NET Standard 2.1. Most likely this line, cause by some trick or feature used by the EF Core package:

https://github.com/unoplatform/Uno.Wasm.Bootstrap/blob/3fed238ceb97c6bddd8f2eeac068e0fa8bc09252/src/Uno.Wasm.Bootstrap/ShellTask.cs#L495

**Comment by nor0x** [comment]
i'm experiencing a issue - i'm not using anything related to Entity Framework, but wanted to use Autofac in a WebAssembly head. It fails with the following error:

`Error: System.TypeLoadException: Could not load type of field 'MyProjectWasm.App:<Container>k__BackingField' (0) due to: Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. at (wrapper delegate-invoke) <Module>.invoke_void_ApplicationInitializationCallbackParams(:60088/Windows.UI.Xaml.ApplicationInitializationCallbackParams) at Windows.UI.Xaml.Application.StartPartial (:60088/Windows.UI.Xaml.ApplicationInitializationCallback callback) [0x00034] in D:\a\1\s\src\Uno.UI\UI\Xaml\Application.wasm.cs:46 at Windows.UI.Xaml.Application.Start (:60088/Windows.UI.Xaml.ApplicationInitializationCallback callback) [0x00000] in D:\a\1\s\src\Uno.UI\UI\Xaml\Application.cs:66 at MyProjectWasm.Wasm.Program.Main (:60088/System.String[] args) [0x00001] in E:\MyProjectWasm\MyProjectWasm.Wasm\Program.cs:12 at Object.call_method (mono.js:1) at Object.call_static_method (mono.js:1) at Object.mainInit (uno-bootstrap.js:160) at checkDone (uno-bootstrap.js:371) at processDependency (uno-bootstrap.js:396) at Object.execCb (require.js:5) at e.check (require.js:5) at e.<anonymous> (require.js:5) at require.js:5 at require.js:5 mainInit @ uno-bootstrap.js:163`

I have also tried adding the assembly in the LinkerConfix.xml and disabling the linker completely.
