### ISSUE TITLE
ALL THE WPF!!!

### ISSUE THREAD

**Issue by Mike-E-angelo** [unoplatform/uno#2617]
(Adding this here as @jeromelaban [challenged me](https://twitter.com/jlaban/status/1225764121997606915). 😅)

## What would you like to be added:

ALL THE WPF!!! ALL THE WPF RIGHT NOW!!!

## Why is this needed:

WPF had the heart, soul, and power of MSFT developers while UWP... not so much.

Truly, here's one example:
https://github.com/microsoft/xaml-standard/issues/20

And, really, going through all the comments of that ([now defunct](https://github.com/microsoft/xaml-standard/issues/230)) repo you can read issue after issue for all the asks that are really based in WPF (and not UWP).

In fact, a simple search of "WPF" shows that half the issues found in that repository mention it:

https://github.com/Microsoft/xaml-standard/issues?utf8=%E2%9C%93&q=is%3Aissue+sort%3Aupdated-desc+wpf

The ideal is to have the power and expressiveness of WPF with the performance-mindedness of UWP/.NET Core.

Of course, the biggest nugget of power in WPF was its markup extensions.  Many imiators of WPF's Xaml have attempted to pull it off, but none have quite yet achieved it as designed.  It's almost becoming a whiteboard/developer IQ test at this point. 🙄

WPF's Markup Extensions had access to the application's `IServiceLocator` which provided access to all the document's services and components right there in the markup extension.  You had cool elements such as the [`IAmbientProvider`](https://docs.microsoft.com/en-us/dotnet/api/system.xaml.iambientprovider?view=netframework-4.8), [`NavigationService`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.navigation.navigationservice?view=netframework-4.8), or `AnyKindOfService` you would like. 😁

It's basically punching a hole right in the middle of XML and making it an extension of your codebase RIGHT THERE IN THE DOCUMENT.  

Very powerful concept, yet to be accurately duplicated -- [except by me](https://github.com/ExtendedXmlSerializer/home/wiki/Features#xaml-ness-markup-extensions), of course. 😏

MarkupExtensions are currently a captured issue in WinUI but based on the lack of activity on the issue, you can tell there is already a bit of a struggle to adequately and accurately implement this sucker.

https://github.com/microsoft/microsoft-ui-xaml/issues/741

Maybe Uno will be different? :)

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] WebSockets (😅)
- [x] macOS
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

I half-heartedly added WebSocket support above like Blazor has... that would be cool, too. 😁

**Comment by Mike-EEE** [comment]
I arrest my case. 😆

https://twitter.com/UnoPlatform/status/1225864756701081601

![](https://i.imgur.com/FXyxr9h.png)

**Comment by jeromelaban** [comment]
Thanks for opening this issue! Yes, markup extensions are indeed very much needed, this is going to add some weight to the discussion.

**Comment by robloo** [comment]
I thought markup extensions were already in? At least UWP's version of them. I saw a lot of commits about this a few months ago.
https://platform.uno/blog/dark-mode-and-markupextensions-now-available-in-uno-platform/

Anyway, UWP should have been based on WPF and we would be in a much better place. UWP did make some really good additions such as x:Bind and easier built-in transalation, etc. I'm not sure it makes any sense to adopt WPF support in Uno at this point. Don't get me wrong, I understand where you are coming from. Just WPF was designed for desktop not mobile and it shows in little areas all over the place.

**Comment by jeromelaban** [comment]
@robloo In most cases, UWP and WPF are very close, the differences are in some specific, such as more advanced markup extensions, triggers, relative sources or multi-bindings.

For markup extensions, the UWP feature set is still a bit behind, particularly with regards to [IProvideValueTarget](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.iprovidevaluetarget?view=netframework-4.8).

In the case of relative source, the implementation is pretty straightforward, and I'm pretty confident once WinUI is open source, that kind of additions will happen. We'll add those in Uno as those start to appear.

**Comment by robloo** [comment]
@jeromelaban Ok, thanks for the clarification! I realize now you are talking about making UWP/Uno markup extensions as powerful as WPF. (As opposed to just adding the UWP markup extensions to Uno which was already done a few months ago -- awesome!).

**Comment by Mike-EEE** [comment]
FWIW [OpenSilver](https://www.opensilver.net/announcements/introducing-opensilver.aspx) proving that it is possible to provide proper MarkupExtensions:

https://github.com/cshtml5/CSHTML5/blob/992e01f6077150f1b842cabe8bfbf100b5d8eaa3/src/CSHTML5.Runtime/System.Windows.Markup/MarkupExtension.cs

**Comment by SERWare** [comment]
> (Adding this here as @jeromelaban [challenged me](https://twitter.com/jlaban/status/1225764121997606915). 😅)
> 
> ## What would you like to be added:
> ALL THE WPF!!! ALL THE WPF RIGHT NOW!!!
> 

**ALL THE UWP!!! ALL THE UWP RIGHT NOW!!!** 

Because UWP is all WPF except in some excelent but minor details (like better Markup Extensions implementation in WPF).

And because WPF is not ALL UWP.

UWP is as powerful as WPF for traditional WIMP desktop applications, while WPF is not as powerful for applications with new features that customers are starting to ask: not only on mobile devices but also on desktop and office environments.

WPF's treatment of new mobile stuf is only a patch that does not harmonize with its essence, and becomes a real nightmare of frequent hangups when used in touch devices (google for WPF issues with touch devices, for example, you'll find many and some of mine).

As for new features in new devices, WPF's patch only simulates WIMP behavior on touch devices: if you want to take advantage of features like gestures, you have to program it yourself with great difficulty.

In addition, UWP has a long list of improvements like x:Bind that allow bindings to functions, x:Load, VisualState Setters, adaptive interfaces, etc., that have not yet been incorporated into WPF.

The problem with UWP is that it was too tied to the success of Windows Phone and the Windows Store at a time when it was much more profitable to program for Android or iOS. I understand how frightening it is because many people confuse this commercial failure with a technical failure and that is not the case: give UWP a chance, and you'll find that it takes little time to master the basics, because it's almost identical to WPF with many improvments and few absences.  At the same time you will be giving a chance to WinUI and the UNO Platform :)

**Regarding Markup Extensions on platform UNO**, I also miss having access to the root object as in WPF. But I believe UNO Platform should keep the UWP standard until we definitely know how WinUI will implement them.

PD. Sorry for my bad english.

**Comment by MartinZikmund** [comment]
I think this can be closed, as further XAML improvements will be done in WinUI first and then brought in to Uno, Similarly, missing WPF features should be brought to WinUI first, to keep in sync.

**Comment by Mike-E-angelo** [comment]
A late reply here, but FWIW I was able to build my [first rough draft of a markup extension](https://github.com/DragonSpark/Framework/blob/3285bbc11632852fbf5fc9dd5e2ff1568ecd1b0b/DragonSpark.Application.Mobile/Presentation/Markup/Localized.cs#L5) without any issue and works as expected. 🙏  I was even able to get general service location established too which is pretty awesome. 😀👍

Thank you for all your efforts out there!  I've had my nose in this for over a week now and it's a very promising platform, IMO.
