### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by touseefbsb** [unoplatform/uno#27]
how about a roadmap or milestones to show the future of the project?

**Comment by nickrandolph** [comment]
+1 Keen to support this project but it really needs to be pushed to the .NET Foundation, or a clear roadmap provided

**Comment by weitzhandler** [comment]
Crucial feature.

**Comment by ghuntley** [comment]
Howdy folks, we are actively working on providing clarity. A couple things have improved on this front over the last couple month. 

1) [since last month] Issues are now being proactively triaged and labelled. Additionally the process has been documented. See docs/contributing/guidelines/*

2) [now] Uno has moved to it its own GitHub repository and we have created a project board that aggregates issues from all of the repositories.

https://github.com/orgs/unoplatform/projects/1

At times there will be items on the board that the public won't be able to see for a multitude of reasons (ie confidentiality, private support and internal projects). Our intention is to be as transparent and open as possible with issues open to the public by default when possible.

3) [up next] move sprint refinement and planning rituals to use the organisation board. 

4) [up next] proactively supporting the community to contribute to Uno. I'm reserving time slots to pair with the community and doubling down on making sure that knowledge for contributing is well documented. Goal: when someone submits a PR with a bug fix the contribution is reviewed, merged and available on NuGet within 24hrs.

**Comment by touseefbsb** [comment]
good news, always good including robots in the work flow, nothing scary there :D

**Comment by ghuntley** [comment]
Closing this issue out as https://github.com/orgs/unoplatform/projects/1 has been implemented and serves as the projects north star. If folks have particular questions please open a new issue specifically for that question. Thanks :)
