### ISSUE TITLE
[WASM] When adding SkCanvas elements to Gridview only the first one renders

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#2748]
## Current behavior

If you periodically add SkCanvas elements to a GridView then only the first one renders in WASM, subsequent canvases fail.

## Expected behavior

All canvases should render, as on UWP.  Also appears to work in Droid, not tested in iOS.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in UWP and observe that canvases are added regularly, and continue updating as more are added.

Launch the project in WASM and observe that only one canvas is drawn, and ceases updating when a new canvas would be rendered.

[CanvasTest.zip](https://github.com/unoplatform/uno/files/4293168/CanvasTest.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
2.2.0-dev.38
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
This issue is actually two different issues:
- The first one is `ItemsWrapGrid` is not supported (https://github.com/unoplatform/uno/issues/468). A workaround can be to use a `WrapPanel` instead (found in the Windows Community Toolkit). 
- The second one is related to a memory issue in the `SKXamlCanvas` that will be fixed by  https://github.com/unoplatform/Uno.SkiaSharp/pull/17

**Comment by peternary** [comment]
Workaround + update have test project functioning

**Comment by jeromelaban** [comment]
Thanks @peternary !
