### ISSUE TITLE
[iOS][Android] Incorrect layout

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2760]
## Current behavior

Incorrect layout 

## Expected behavior

https://dev.azure.com/nventive/Umbrella/_workitems/edit/176427

## How to reproduce it (as minimally and precisely as possible)

TBD

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Found the problem.  It's the same as https://github.com/unoplatform/uno/issues/2430#issuecomment-594622038

Workaround would be to add a `MinWidth` to `0` in the `<Style>` like this:
`<Setter Property="MinWidth" Value="0" />`

**EXPLANATION**
That's because the `MinWidth` will always get priority over `Width`, even on Windows. And the style is inheriting the values of the _implicit_ style. It's a limitation in Uno where there's no difference between the _default style_ and the _implicit style_ for a control.  Should be fixed by PR #1766.

**Comment by davidjohnoliver** [comment]
#1766 is merged (well and truly) and default/implicit styles are handled correctly in the same way as UWP, so this should be fixed.
