### ISSUE TITLE
[Android] Invalid Ad Control layout

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#2761]
## Current behavior

A Google Ad control does not layout properly.

## How to reproduce it (as minimally and precisely as possible)

TBD
https://dev.azure.com/nventive/Umbrella/_workitems/edit/176391

## Environment

Nuget Package: 

Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carlh98** [comment]
I've created a branch for the issue origin/dev/cama/ad-banner-cropped
Just launch the project to see the control, the xaml is in the WhatsOnPage.xaml

The issue comes from line 102 of Layouter.cs where ".AtLeast(minSize)" was removed
https://github.com/unoplatform/uno/commit/f47195254ac671d4e7a74e3a47178dbf4eb4178a#diff-1ccb3af58d327b57ec29a1d227d9cf2a
