### ISSUE TITLE
Refactor shapes to remove legacy `ArbritaryShapeBase` on WASM

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#2983]
> ⬇️ ⬇️ **FOR MORE INFO, SCROLL TO COMMENTS BELOW** ⬇️ ⬇️

## Current behavior

In the example when an ellipse is resized by a visual state change trigger the parent stackpanel does not resize.

## Expected behavior

WASM should beave the same as the UWP and Android builds.

## How to reproduce it (as minimally and precisely as possible)

Reproduced in a sample project here:
https://github.com/BrianDT/UnoGeometryIssues

## Environment
Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.445

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
No idea for this one... To fix this one I would think that the easiest solution should be to multi-target what I did for iOS (and MacOS): https://github.com/unoplatform/uno/pull/2911

**Comment by carldebilly** [comment]
## Investigations

- I confirm the problem is present on WASM on both Uno v`2.4.0` and v`3.1.0-dev.389` (latest _prerelease_ version)
- I confirm the problem is **not** present on Android, both Uno v`2.4.0` and v`3.1.0-dev.389` (latest _prerelease_ version)
- I added a SKIA head to the sample app and the problem is **NOT** present on Skia using v`3.1.0-dev.389` (latest _prerelease_ version)

So I confirm it's a WASM-only bug and still present in latest version of Uno.

**Comment by carldebilly** [comment]
Shapes on WASM are using a legacy `ArbritraryShapeBase` which should soon be refactored to use the new approach introduced by the PR #2997 on iOS and refactored for Skia in PR #3652.

I'll change the title of this issue to better reprensent the action item to resolved this issue, which is a refactoring.

**Comment by BrianDT** [comment]
Confirmed as resolved in Uno.UI 4.5.9
The sample has been updated to validate this.
The issue can now be closed
