### ISSUE TITLE
Does the team have a plan to fit net5?

### ISSUE THREAD

**Issue by HaoLife** [unoplatform/uno#3211]
Does the team have a plan to fit net5?

**Comment by jeromelaban** [comment]
There is a plan for .NET 5 yes, though there are still unknowns with regards to the way Xamarin will integrate with it. Build announcements will definitely make the path clearer.

**Comment by jabak** [comment]
Scott Hunter revealed that there are no plans to bring .Net 5 to UWP in the session 'The Journey to One .NET'.  But WinUI 3 supports .Net 5. So where this leaves UWP is unknow. 

He clearly stated that UWP app developers should stay where they're at until WinUI 3 is ready and then move their apps to WinUI 3 and get .NET 5 support that way. But as WinUI 3 + .NET 5 is  Winforms/WPF only he actually told us that if you want UWP you won't get .NET 5 - else move to WPF.

**Comment by HaoLife** [comment]
My understanding is that Winui 3.0 unites Winform/WPF into the api of the uwp control. The goal makes windows all use the same api to implement, similar to uno. Uno complements the unification of non-windows systems.

**Comment by jabak** [comment]
I had a chat with some people on Discord/WinUI last night. The new templates for VS 2019 16.7.0 preview comes in two flavours. According to the guys at discord the template 'WinUI In Desktop' creates what they call a WinUI 3 Win32 app. So not an UWP app, not a WPF app and not a Winforms App just a Win32 app with .NET 5 support. The other template "WinUI in UWP" creates a WinUI 3 Uwp app with the usual  .NET native / C# 7.3 support.

So the WIn32 app is to be viewed upon as a path for Win32 developers to somewhat make the transition to UWP apps as smooth as possible if they wish to go in that direction. Bottom line is: go with UWP if the sandbox limitations isn't an issue, Win32 if your app will not work in the sandbox. 

WPF and Winforms developers can either make use of WinUI 3 and .NET 5 in their app or transition to Win32 .NEt 5 apps at their pace.

UWP and .NET 5? Still unclear if that is going to happen. Some people say it will others don't. But as pointed out to me the WinRT projection has been lifted out of .NET 5 so that could be the first preparations to make that happen.

**Comment by ysmoradi** [comment]
‌Blazor/Wasm now support net5
What about Uno/wasm?

**Comment by francoistanguay** [comment]
Blazor/WASM doesn't support AOT in .net 5. So we dont think it's a viable approach.
