### ISSUE TITLE
[WASM] AOT Build fails to start entirely, gets stuck on logo

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3294]
## Current behavior

In WASM AOT build some systems do not load the page past the logo.  The same project works on affected systems when using Interpreter build.  This has occurred consistently after multiple AOT rebuilds.

The console contains the following information:

dotnet.js:2187 fail: Uno.Foundation.Interop.TSInteropMarshaller[0]
dotnet.js:2187       Failed InvokeJS for RegisterEventOnView/Uno.UI.Xaml.WindowManagerInterop+WindowManagerRegisterEventOnViewParams: System.Exception: undefined
dotnet.js:2187       undefined
dotnet.js:2187 fail: Windows.UI.Xaml.FrameworkElement[0]
dotnet.js:2187       ManagedOnLoaded failed in FrameworkElement
dotnet.js:2187 System.Exception: undefined
dotnet.js:2187 undefined
dotnet.js:2187 
dotnet.js:2187 fail: Uno.Foundation.Interop.TSInteropMarshaller[0]
dotnet.js:2187       Failed InvokeJS for RegisterEventOnView/Uno.UI.Xaml.WindowManagerInterop+WindowManagerRegisterEventOnViewParams: System.Exception: undefined
dotnet.js:2187       undefined
dotnet.js:2187 fail: Windows.UI.Core.CoreDispatcher[0]
dotnet.js:2187       Dispatcher unhandled exception
dotnet.js:2187 System.Exception: Failed to load Page NinjaTrader.Gui.LogonPage
dotnet.js:2187

## Expected behavior

Page should load normally

## How to reproduce it (as minimally and precisely as possible)

Difficult to reproduce, so far has only affected a single project and not all testing systems are impacted.

## Environment

Nuget Package:

Uno.Wasm.BootStrap

Package Version(s):

1.3.0-dev.18

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks Peter. Does this system have a specific locale?

**Comment by peternary** [comment]
The system is set to German.  I set my system to German as well but did not experience a similar issue.

**Comment by DierkDroth** [comment]
To be specific: It happens on my machine which is an English Windows 10 which I have set to "Region = Germany" and "Regional format = German (Germany)"

**Comment by jeromelaban** [comment]
Thank you. In order to debug this, there's a method called `registerEventOnViewInternal` in the file `Uno.UI.js`. Place a javascript breakpoint there, then once it hits, click on the pause on exception button:
![image](https://user-images.githubusercontent.com/5839577/83644508-5bee6080-a57f-11ea-90d9-baccc8966b74.png)
And try to find out if there's an exception happening inside of that method. It should be an `undefined` member access, or something similar.

**Comment by DierkDroth** [comment]
@jeromelaban I just got it broke at UNO.UI.js line 1098 in getEventExtractor. Not sure if that helps though...

**Comment by jeromelaban** [comment]
This error generally means that the Uno.UI version that is used is too old for the bootstrapper used. There was change in mono that makes the javascript differently because the runtime thinks it's running outside of the browser.

You're probably seeing this message: 

https://github.com/unoplatform/uno/blob/c20279c75f2e97453db24779310353f015971fa8/src/Uno.UI.Wasm/ts/CoreDispatcher.ts#L57

Make sure to upgrade to a more recent Uno.UI build.

**Comment by DierkDroth** [comment]
Hmm ... that was a funny one. I don't recall how many times I pressed CTRL-F5 to make sure the latest build would not be loaded from browser cache. Turns out it still was.
Only after I disabled caching the Chrome Dev Tools I was able to load the latest build.

This leaves me worried about potential issues when deploying a WASM solution where updates would not be propagated/downloaded as expected. Concerning...

**Comment by peternary** [comment]
Appears to be working at the moment, closing this

**Comment by jeromelaban** [comment]
@DierkDroth caching is indeed a concern that is being addressed in recent builds of the bootstrapper. You'll notice the dist folder now has changed in structure to avoid those issues.

**Comment by DierkDroth** [comment]
Thanks @jeromelaban. Sounds promising...
