### ISSUE TITLE
Is TextBlock Run not implemented in wasm yet ?

### ISSUE THREAD

**Issue by MuziburRahman** [unoplatform/uno#3312]
This simple Xaml renders nothing in Microsoft Edge chromium :
```
<Page
    x:Class="UnoHi.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    d:DesignWidth="400"
    mc:Ignorable="d"
    RequestedTheme="Dark">

    <Grid>

        <TextBlock><Run>Where</Run> <Italic>did</Italic> <Run>my text go?</Run></TextBlock>

    </Grid>

</Page>

```

Nuget Package:
Uno.UI : 2.4.4
Uno.Wasm.Bootstrap : 1.2.0
Uno.Wasm.BootstrapDevserver : 1.2.0

Affected platform(s):
- [ ] WebAssembly

Visual Studio:
- [ ] 2019 (version: 16.6.1)

**Comment by jeromelaban** [comment]
Thanks for the feedback! 

It's actually rendering something, most likely black on black. You'll need to specify a background color on the first grid, as you'll find in the default template: 

https://github.com/unoplatform/uno/blob/a2e08f0edbcc747a01b9dbc2237d4b5a959396a3/src/SolutionTemplate/UnoSolutionTemplate/Shared/MainPage.xaml#L10

This is fixed in the upcoming 3.0 update.
