### ISSUE TITLE
[WASM] Cannot reference ThemeResources in ResourceDictionary

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3350]
## Current behavior

In WASM attempting to use resources from the ThemeResource fails with a message similar to,

warn: Uno.UI.ResourceResolver[0]
dotnet.js:1       Couldn't statically resolve resource CalendarDatePickerBackgroundFocused

## Expected behavior

Resources should be loaded correctly, as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Load the attached project in WASM and observe that page is very to slow to render, with many warning messages about being unable to resolve resources in console.

[App50.zip](https://github.com/unoplatform/uno/files/4766973/App50.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.454
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment]
To clarify: that issue is not isolated to the CalendarDatePicker control but shows on virtually any control.

**Comment by DierkDroth** [comment]
@jeromelaban @davidjohnoliver is there any ETA yet for a fix? Unfortunately this issue is getting in our way as we're trying to apply custom styling in WASM (and UWP)

**Comment by davidjohnoliver** [comment]
@DierkDroth . Yes, it's in progress. There's an issue of some referenced resources being missing from Uno, that part will be fixed today.

**Comment by DierkDroth** [comment]
@davidjohnoliver @jeromelaban unfortunately this issue is far from being resolved: there are many, many more resources still missing from the generic UWP XAML.

@peternary already isolated these additional resources just in our current code (please see below). How, could that issue be resolved once and for all?

RadioButtonBackgroundDisabled
RadioButtonBackgroundPointerOver
RadioButtonBackgroundPressed
RadioButtonBorderBrush
RadioButtonBorderBrushDisabled
RadioButtonBorderBrushPointerOver
RadioButtonBorderBrushPressed
RadioButtonCheckGlyphFill
RadioButtonCheckGlyphFillDisabled
RadioButtonCheckGlyphFillPointerOver
RadioButtonCheckGlyphFillPressed
RadioButtonCheckGlyphStroke
RadioButtonCheckGlyphStrokeDisabled
RadioButtonCheckGlyphStrokePointerOver
RadioButtonCheckGlyphStrokePressed
RadioButtonForegroundDisabled
RadioButtonForegroundPointerOver
RadioButtonForegroundPressed
RadioButtonOuterEllipseCheckedFill
RadioButtonOuterEllipseCheckedFillDisabled
RadioButtonOuterEllipseCheckedFillPointerOver
RadioButtonOuterEllipseCheckedFillPressed
RadioButtonOuterEllipseCheckedStroke
RadioButtonOuterEllipseCheckedStrokeDisabled
RadioButtonOuterEllipseCheckedStrokePointerOver
RadioButtonOuterEllipseCheckedStrokePressed
RadioButtonOuterEllipseFill
RadioButtonOuterEllipseFillDisabled
RadioButtonOuterEllipseFillPointerOver
RadioButtonOuterEllipseFillPressed
RadioButtonOuterEllipseStroke
RadioButtonOuterEllipseStrokeDisabled
RadioButtonOuterEllipseStrokePointerOver
RadioButtonOuterEllipseStrokePressed

**Comment by jeromelaban** [comment]
@davidjohnoliver Missing resources were previously ignored as we integrated controls piece by piece, which is why this issue is surfacing. We can validate that theme/static resources referenced by styles defined inside of Uno are mandatory and must be self sufficient.

**Comment by DierkDroth** [comment]
@jeromelaban we can work with the resources keys your provided in the 'UNO version' of Generic.xaml. This issue could be closed. Thanks

**Comment by peternary** [comment]
Appears fixed in latest
