### ISSUE TITLE
[WASM] Implement automatic AssemblyVersion

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3375]
## What would you like to be added:

Automatic assembly versioning should be configurable, as in attached project:

[VersionTest.zip](https://github.com/unoplatform/uno/files/4782344/VersionTest.zip)

## Why is this needed:

Being able to pull the assembly version at runtime can be very useful in tracking down regressions or other debugging.

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment]
Thanks for the report. `GetExecutingAssembly` may not work in all scenarios, particularly for AOT until WebAssembly provides natively such a feature and mono implements it.

You'll have to use an assembly from an explicitly type, [like this](https://github.com/unoplatform/Uno.UI.Sample.Banner/blob/dec4907d57fbb8ddc30246fca5241f73b114e5ff/src/Uno.UI.Sample.Banner/BannerControl.cs#L50).

**Comment by roonius** [comment]
Hello,
The issue is not getting the assembly. The issue is generated AssemblyInfo.cs file

Even we have this under UWP (and working correctly):
[assembly: AssemblyVersion("1.0.*")]

under WASM generated file AssemblyInfo.cs  contains the following:
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("Product")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
**[assembly: System.Reflection.AssemblyFileVersionAttribute("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("1.0.0")]**
[assembly: System.Reflection.AssemblyProductAttribute("Product.Wasm")]
[assembly: System.Reflection.AssemblyTitleAttribute("Product.Wasm")]
**[assembly: System.Reflection.AssemblyVersionAttribute("1.0.0.0")]**

**Comment by jeromelaban** [comment]
I understand, I did not get this reading the issue description.

The wildcard feature is not supported as part of sdk style projects. Versioning is done through the `AssemblyVersion` msbuild property. You find the [documentation here](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#assemblyinfo-properties).

The way we're handling this is through [GitVersion](https://gitversion.net/docs/) or [Nerdbank](https://github.com/dotnet/Nerdbank.GitVersioning).
