### ISSUE TITLE
Implement WebAuthenticationBroker

### ISSUE THREAD

**Issue by xperiandri** [unoplatform/uno#3433]
## What would you like to be added:
`WebAuthenticationBroker`

## Why is this needed:
It is critical for implementing OAuth2 and OpenID Connect authentication which is spread everywhere

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?
I guess this requires modifications similar to what `Uno.UI.MSAL` does.
By the way, @carldebilly, where to find your MSAL sources?

**Comment by xperiandri** [comment]
Basically `WebAuthenticationBroker` just opens a special secure Web View and waits for a specified scheme to appear on redirect

**Comment by xperiandri** [comment]
For me, it is the most critical point to bootstrap using Uno for any project that uses interactive authentication

**Comment by jeromelaban** [comment]
Thanks for the report!

The implementation for `WebAuthenticationBroker` can be significantly different depending on the platform. It also looks like it would be more interesting to add support for #3393.

**Comment by xperiandri** [comment]
But this includes that

**Comment by xperiandri** [comment]
There is an official sample in IdentityModel.OidcClient repo for all the platforms

**Comment by xperiandri** [comment]
Having AuthenticationBrocker implemented will only need adding special activity on Android and (maybe) some stuff on WASM

**Comment by xperiandri** [comment]
@carldebilly, could you point to your MSAL implementation?

**Comment by carldebilly** [comment]
@xperiandri That's the official Uno doc for MSAL:
https://platform.uno/docs/articles/interop/MSAL.html

**Comment by xperiandri** [comment]
I'm about sources

**Comment by carldebilly** [comment]
The sources are there: https://github.com/unoplatform/uno/tree/master/src/AddIns/Uno.UI.MSAL

It's pretty straightforward: it's basically just implementing `ICustomWebUi` and `IMsalHttpClientFactory` for wasm.

The logic for the _webview_ is there:
* C#: https://github.com/unoplatform/uno/blob/master/src/AddIns/Uno.UI.MSAL/WasmWebUi.wasm.cs
* TS: https://github.com/unoplatform/uno/blob/master/src/AddIns/Uno.UI.MSAL/ts/MSAL.WebUI.ts

**Comment by xperiandri** [comment]
Thanks, hence we need to look into MSAL implementation for WebUI invoke.
So currently on return from URL Uno activates app by protocol
https://github.com/unoplatform/uno/blob/a97622505cea5180d9943965e73b099ca028264d/src/Uno.UI/UI/Xaml/Application.iOS.cs#L87
But I haven't found how it works on Android.

However, what does Windows is that it launches separate special UWP app with WebView where all the redirects happen and activation happens inside of it.

If we implement WebAithenticationBroker then we need to integrate it with the `Application` class somehow. Like when we open it we register a Broker implementation with a callback scheme in Application class and when the redirect happens and scheme matches then to return a result from Broker instead of doing app protocol activation.

@jeromelaban what do you think?

**Comment by jeromelaban** [comment]
If the authentication broker is implemented using an external browser, then yes, it would need to be integrated in the Application class, somehow.

**Comment by christoph68** [comment]
I also am interested (still) in such authentication. Basically the first step here would be the availability of a MSAL alike library that targets any OpenID provider. But currently oidc-client.js can't serve this. An interesting vote is here: https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/1555

**Comment by xperiandri** [comment]
@christoph68, MSAL is a special case. We need a generic solution

**Comment by christoph68** [comment]
> @christoph68, MSAL is a special case. We need a generic solution

What is the difference between a MSAL alike library (means same functionality) that works with any OpenID provider and a generic solution as you describe?

**Comment by JohnGalt1717** [comment]
@xperiandri  This should also support windows and all other supported platforms and would have a different implementation on each.  Using the standard client we already get at least ios, android, windows. It needs to be extended to support web assembly etc.  For web assembly Blazor already has a library that does this which presumably would work in this case too so it would just need to wrap all of them.

@christoph68 According to MS documentation it's for Microsoft authentication only: "Microsoft Authentication Library (MSAL) enables developers to acquire tokens from the Microsoft identity platform endpoint in order to access secured web APIs. "

It isn't intended to be used generically.

**Comment by xperiandri** [comment]
Looks like it is universal. It just implements OpenID Connect protocol

**Comment by JohnGalt1717** [comment]
@xperiandri I've used it in the past. It's very micrsoft Azure AD centric. You might get away with it on C# desktop platforms but I wouldn't trust it. Use the Identity.OidcClient, it's better suited and supports the same platforms. Then using Blazor's oidc support you have the web too.

**Comment by xperiandri** [comment]
I usually did that as you described. That is why I think that `WebAuthenticationBroker` is important

**Comment by xperiandri** [comment]
@jeromelaban which project should I put `WebAuthenticationBroker` implementation?
`Uno/Security/Authentication/Web/WebAuthenticationBroker.cs`?

**Comment by jeromelaban** [comment]
@xperiandri it should be a version of https://github.com/unoplatform/uno/blob/fe8f8a762bb95072bd186f6c61926f908131887a/src/Uno.UWP/Generated/3.0.0.0/Windows.Security.Authentication.Web/WebAuthenticationBroker.cs, placed in "https://github.com/unoplatform/uno/blob/fe8f8a762bb95072bd186f6c61926f908131887a/src/Uno.UWP" in a folder named `Security.Authentication.Web`.

**Comment by xperiandri** [comment]
Why Uno.UWP?

**Comment by jeromelaban** [comment]
Because it's the current location of the file that defines that contract.

**Comment by dansiegel** [comment]
+1 on getting this feature prioritized... I could really use it for authenticating with GitHub

**Comment by JohnGalt1717** [comment]
This is the major blocker for us using UNO versus Flutter as it stands right now.

**Comment by francoistanguay** [comment]
Hi John,

Couple of points. 

First, you can almost always fallback onto platform native services and tricks as an Uno app is native on all platforms. It is the exact purpose of Uno's architecture. If something is not YET available in Uno through the UWP/WinUI abstractions, you can always fallback to platform specific and not be blocked. Agree it might not give you 100% code reuse, but 99% aint bad. And it's the same with a WASM target, you can still use javascript.

 Second, have you tried to investigate how you could work it out in Uno? Asked questions and didnt get answers? We'd love to help and the community is super active

Third, we try to find a balance between everything we want to do and priorities we get from our paid customers. This is one way enterprises are committing to Uno, by paying for Enterprise Support licenses, it guarantess the viability of the product and in exchange we do prioritize what they need.

Thanks

**Comment by JohnGalt1717** [comment]
So while I'm sure, yes I could go and hack it together and hack video playback together on all platforms like we have done in the past with Xamarin Forms, the entire point is to not have to. We want to build software, not hack together platform stuff. That's why we would take the risk and invest in Uno and even contribute.

And in the case of OpenIdConnect, essentially all enterprise customers will require this functionality.  It's the defacto standard for authentication. Using MSDAL means you exclude everyone using google etc. to say nothing of the people with their own OpenIdConnect services.

This is baseline functionality for any app, especially enterprise at this point.  You literally can't get anywhere without authentication and OpenIDConnect is basically THE way that authentication occurs short of legacy systems which I would agree need to support themselves because you can't support every home brew mess.

Hence why this request is so important: Anyone evaluating technology will start with "Can I get my users logged in?" and go from there. Right now the answer to that question except in incredibly limited cases is "no".  Which stops all of the rest of the evaluation process.
