### ISSUE TITLE
WasmHttpHandler - RuntimeError: memory access out of bounds when downloading 1 mb file.

### ISSUE THREAD

**Issue by mertkokusen** [unoplatform/uno#3525]
## Current behavior

Wasm app throws "RuntimeError: memory access out of bounds" when I try to download a sample pdf file of 1 mb size. Same code with 500 kb sample file runs fine.

## Expected behavior

File should be downloaded without any exceptions.

## How to reproduce it (as minimally and precisely as possible)

Minimal repro project can be found here. 

https://github.com/mertkokusen/WasmHttpHandlerMemoryErrorRepro

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by arivera12** [comment]
I don't now very well how this integrates with blazor side but take note that blazor have some limitations when downloading file from blazor WASM. 

We all know to download a file from the browser we need to interop with javascript. 

I made this library https://github.com/arivera12/BlazorDownloadFile which seems to manage huge files and its very well documented.

I haven't yet played with Uno platform but seems promising I have been developing blazor apps since 2 years ago and still on it. and a little bit with xamarin. 

Just giving some feedback and head notes for this issue.

**Comment by arivera12** [comment]
For native platforms we may don't may have issues cause our memory backing store is the local disk but when working with Blazor wasm and JS interop the memory backing store is the ram of the device, and this have limitations.

Every time when it's possible if the file is coming from the server we should recommend users to first try to use Content-Disposition attachment response header as it has more cross-browser compatibility.

At some point in the near future browsers will have the option to write to the native file system.

https://web.dev/native-file-system/

**Comment by JanKleprlik** [comment]
Are there any updates on this?

**Comment by jeromelaban** [comment]
The Uno `WasmHttpHandler` is no longer needed as the `HttpHandler` coming from .NET 5 BCL is providing enough features, including fixing this issue.
