### ISSUE TITLE
[WASM] Performance with runtime-created ItemTemplate is poor

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3536]
## Current behavior

If you create an ItemTemplate at runtime using XamlReader.Load then performance is significantly worse than it would be in UWP.

## Expected behavior

Performance should more closely track UWP

## How to reproduce it (as minimally and precisely as possible)

Start the attached project in UWP and click the button - notice that the list populates instantly.  Start the attached project in WASM and click the button - notice that it takes several seconds to populate the list.  This delay becomes greater as more complex DataTemplates are being generated.

[RuntimeSetStyles.zip](https://github.com/unoplatform/uno/files/4919290/RuntimeSetStyles.zip)

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the issue Peter.

While Uno is not performant for this scenario and probably won't be for a while since it's based on reflection, it's generally not a good idea to use the `XamlReader` to parse large content, even if UWP is faster.

Creating the DataTemplate using the XAML Reader, then use an actual control is generally more performant, easier to create and troubleshoot.

For instance: 
 
```csharp
var dataTemplate = XamlReader.Load($@"<DataTemplate xmlns:local=""using:MyNamespace""><local:MyCustomControl Parameter=""1234"" /></DataTemplate>");
```

Then create the `MyNamespace.MyCustomControl` class and create the content from there.
