### ISSUE TITLE
[WASM] ScrollViewer Scrollbar visibility is not working correctly 

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#3783]
## Current behavior

On wasm, it seems that only the vertical scrollbar is visible by default. Also, if we set both Horizontal and vertical scrollbar visibility to auto, it seems to hide them both.

![wasmscrollbar](https://user-images.githubusercontent.com/17461593/89947589-b1379580-dbf2-11ea-9de8-301d3ef48a38.jpg)

## Expected behavior

**UWP**
![uwpscrollbar](https://user-images.githubusercontent.com/17461593/89947601-b4cb1c80-dbf2-11ea-9756-a3cd1fedf15f.jpg)

## How to reproduce it (as minimally and precisely as possible)

Open this [sample.zip](https://github.com/unoplatform/uno/files/5059411/ScrollbarVisibilitySample.zip)
Deploy on wasm

## Environment

Nuget Package: Uno.ui

Package Version(s): 3.0.0-dev.1540

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.2)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

At the moment, there seems to be a regression with the scrollviewer, because it simply does show any (in the version 3.0.0-dev.1551). The version I mentioned is the latest one with the bug.

**Comment by takla21** [comment]
So, I just retry with the latest version of Uno.Ui and the issue stills remains. But at least we can see the scrollviewer (the regression mention at the end is not a problem anymore)

**Actual result**
![errro](https://user-images.githubusercontent.com/17461593/91497931-d4b63d80-e88c-11ea-9f56-0f5a5374ebda.jpg)

**Updated Sample**: [HorizontalscrollSample.zip](https://github.com/unoplatform/uno/files/5138926/HorizontalscrollSample.zip)

**Environment**
Uno.UI: 3.1.0-dev.121

**Comment by dr1rrb** [comment]
We recently worked to [add support of WinUI `ScrollBar` in the `ScrollViewer`](https://github.com/unoplatform/uno/pull/3681) (instead of relying on the native scrollbars of the browser which lacks of styling support!), which also fixes this issue.

But it surfaced a memory leak with the `ScrollBar`, so for now the default template of the `ScrollViewer` still uses the "native" scroll bar. The leak seems problematic only if you create/remove a lot of `ScrollViewer`/`ScrollBar` (like in UI tests), so as a workaround for this bug you can change the style of your `ScrollViewer` to use the default WinUI one (eg. https://github.com/unoplatform/uno/blob/master/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/ScrollViewerTests/ScrollViewer_ScrollBars.xaml#L15)
