### ISSUE TITLE
The "CompileXaml" task returned false but did not log an error

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#3819]
Hi everyone. I'm trying to build my Uno Platform port of my Unofficial Instagram client app "Winsta" but I get the following error and 49 others
The "CompileXaml" task returned false but did not log an error
I don't know exactly why this happens but I think it is related to x:FeildModifier property. Is Feild Modifier implemented to Uno Platform yet? 
Otherwise, How can I find why this error happens because even It doesn't mention any file that throws into this issue. 

other Nuget Package:
Fody
PropertyChanged.Fody
Uno.Microsoft.toolkit
Uno.Microsoft.Toolkit.UWP.UI.Controls

Package Version(s):
Uno.Core V2.0
Uno.UI V3.0.5
Uno.UI.Lottie V3.0.5

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.7.0)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by NGame1** [comment]
Problem solved.

**Comment by thomasclaudiushuber** [comment]
Hey @NGame1, it would be fantastic to post the solution. Else this issue is useless for others who might come across the same problem. What was causing this issue on your side? And what is the solution?

**Comment by jeromelaban** [comment]
@thomasclaudiushuber are you having a similar issue with latest uno builds ?

**Comment by NGame1** [comment]
@thomasclaudiushuber I was using Uno.Material. it needs UWP project with Target 2004 and MinTarget at least 1903 if I remember correctly. 
Uno platform is completely like Xamarin Forms in Errors. Both of them show much garbage errors. You should find the real error between them sometimes it doesn't show the real error. 
You can see the Build output to find `a probably true error` in that log.

**Comment by thomasclaudiushuber** [comment]
Thanks @NGame1 , thanks @jeromelaban ,

I got the same error yesterday on another machine, but as @NGame1 mentioned, beside several other errors. When I saw that this "CompileXaml" task is from the .targets file of the WIndows SDK, I knew it has nothing to do with Uno directly. But I wondered if I might have the same problem as @NGame1.

But as I know now after @NGame1 answer, it's something different. What happened in my case was that somehow the NuGet package restore didn't work for a new Uno solution. I was able to create and run any other project in Visual Studio, but running the UWP project of the Uno solution failed, and the WASM project didn't even find the NuGet packages. 
In the logs I saw that the package source "D:\_packages" was not found. Ok, that package source was configured in my Visual Studio installation a while ago, but the local folder didn't exist anymore. I deleted the package source in the Visual Studio options, restarted Visual Studio, tried again, and everything worked.

So, everything's fine, it was caused by a NuGet misconfiguration on my side.

**Comment by jeromelaban** [comment]
Thanks for the update. Could you create a `msbuild.binlog` file by using `msbuild /r /bl` on the CLI for the project that fails, and post it here ?

**Comment by thomasclaudiushuber** [comment]
Ok, I've created a new Uno solution and configured Visual Studio and NuGet as mentioned in the repro steps above.

The binlog shows clearly what the problem is:
![image](https://user-images.githubusercontent.com/7116546/92329625-e788f900-f068-11ea-8d78-8831d444c42d.png)

Here's the log file (You need to change the extension again to .binlog)
[msbuild.bin.log](https://github.com/unoplatform/uno/files/5179896/msbuild.bin.log)

But when building the UWP project in Visual Studio, it looks like this:
![image](https://user-images.githubusercontent.com/7116546/92329638-fec7e680-f068-11ea-90a8-44e38cba1bb0.png)

When building the solution I get these errors there:
![image](https://user-images.githubusercontent.com/7116546/92329668-35056600-f069-11ea-8fef-b5828f1b4a33.png)

Now I remove that wrong package source here:
![image](https://user-images.githubusercontent.com/7116546/92329675-464e7280-f069-11ea-8cf4-c04770953ffc.png)

And after that, a Build is enough to build the whole solution successfully.

**Comment by jeromelaban** [comment]
Thanks. This looks like a local configuration issue. If this folder does not exist, none of the package restore will work.

Did you add this package source explicitly ? Or did it happen after you installed an uno template ?

**Comment by thomasclaudiushuber** [comment]
Yes, this is/was a local configuration issue. I mentioned this above, it's **not** related to Uno! 

I think in the past I created that package source explicitly, and at some point I removed the folder but not the source configuration in Visual Studio. Interestingly I didn't notice it for a while, as I worked mostly in customer VMs due to the pandemic and I worked on local projects with a desktop PC. This error happened on my notebook that I didn't frequently use in the past

Thank you for your help!
