### ISSUE TITLE
WASM sees "Blue" as different from "blue"

### ISSUE THREAD

**Issue by jerocis** [unoplatform/uno#3834]
Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

If needed, please contact me, and I will send a .zip file containing my code.

**Comment by robloo** [comment]
I think some context is needed here. It's hard to understand what you are referring to.

**Comment by jerocis** [comment]
When running an app that accepts the height, width, and color as input, and returns a rectangle drawn to those specifications on Windows, or Android, I can enter the name of a color either capitalized, or not, and it works. When running the .wasm version, only when the color is capitalized (Red, Blue, Green, etc.) does it work. Entering the color in lower case (red, blue, green, etc.) it fails.


________________________________

**Comment by robloo** [comment]
The color is input in a TextBox? How are you parsing the text into a Color?

**Comment by jerocis** [comment]
See the attached files.

**Comment by jerocis** [comment]
MainPage and RectangleProperties from the app.

________________________________

**Comment by jerocis** [comment]
See attached.

**Comment by agneszitte-nventive** [comment]
@jerocis Is it possible to see your related XAML content, please? (MainPage.xaml)

**Comment by jerocis** [comment]
[MainPage.xaml.pdf](https://github.com/unoplatform/uno/files/5088192/MainPage.xaml.pdf)
[MainPage.xaml.cs.pdf](https://github.com/unoplatform/uno/files/5088193/MainPage.xaml.cs.pdf)
[RectangleProperties.cs.pdf](https://github.com/unoplatform/uno/files/5088194/RectangleProperties.cs.pdf)

**Comment by robloo** [comment]
You closed this which means you might have found something. 

Just a recommendation: I wouldn't suggest using a string type Color in RectangleProperties. I might be better to use an actual Color struct. I would also suggest adding a using at the top so the backing type of color can be changed (specifically, the namespace as things progress to WinUI 3). Something like `using Color = Windows.UI.Color;` at the top of the file. Perhaps you are using a string to avoid all this though.

Then you can use converters to control the conversion between String <-> Color. XAML already contains type converters for this the defaults of which you are using implicitly. It's also not necessary to use TwoWay binding on the ellipse, OneWay is just fine.

Since you are using the default XAML type converter `(Color)XamlBindingHelper.ConvertValue(typeof(Color), "blue");` I still don't see how this would behave differently on WASM.

**Comment by jerocis** [comment]
Actually, I'm not sure how the issue got closed. Errant keystroke, perhaps. 

The fact is I found the problelm while doing an assignment for a Udemy course. The course instructor told me that I should open an issue here, so I did. I have no interest in passing colors into apps. I was just following an assignment. 

If you'd like to understand why the .wasm is different, the instructor's notes are here. Write the app as described and see for your self.

[SCN_0001.pdf](https://github.com/unoplatform/uno/files/5091540/SCN_0001.pdf)
[SCN_0002.pdf](https://github.com/unoplatform/uno/files/5091541/SCN_0002.pdf)
