### ISSUE TITLE
Please add Windows.UI.Xaml.Application.Current.Exit for iOS

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#3898]
## What would you like to be added:
Windows.UI.Xaml.Application.Current.Exit

## Why is this needed:
Because I'm using this method in some of my apps

## For which Platform:

- [X] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

For iOS, it is probably simple
System.Threading.Thread.CurrentThread.Abort();
but as I have no iOS device, I cannot test it.

**Comment by jeromelaban** [comment]
This is a feature that cannot be added to iOS as the app store will refuse an application uses such a behavior.

**Comment by robloo** [comment]
Just curious, wouldn't this be removed from the AOT compiled code on iOS as long as it is never used by the App? If so, actually, I think it makes sense to add it. Yes, developers shouldn't use it if they want apps in the store; however, even Apple gives the functionality but tells developers not to use it. Since this also is part of the UWP spec; it seems best to enable the feature but leave the same warning that Apple provides -- don't use it if you want the app in the store.
