### ISSUE TITLE
"Folder In Use" after closing Visual Studio 2019 once .Droid build was run

### ISSUE THREAD

**Issue by SetTrend** [unoplatform/uno#3915]
I'm not sure if this is the right tree to bark up, but after I close Visual Studio 2019 once having run an Uno build, some `adb.exe` and `Uno.SourceGeneration.Host.exe` processes keep running and holding a lock on the `*.Droid` folder:

![Folder In Use](https://user-images.githubusercontent.com/9283914/91719402-90c97e00-eb95-11ea-88df-1036e71c3c97.png)

![Process Explorer](https://user-images.githubusercontent.com/9283914/91719566-d5edb000-eb95-11ea-9e03-7ef3e49ed5a8.png)

![Process Explorer](https://user-images.githubusercontent.com/9283914/91720589-ae97e280-eb97-11ea-9b2e-466409f30a87.png)

The only remedy is to either kill all the processes or to sign out of Windows.

**Comment by jeromelaban** [comment]
At this point, fixing this issue is a balance build between performance and file locking, and build performance takes the lead for now. We'll eventually [migrate to C# 9.0 source generators](https://github.com/unoplatform/uno/issues/3948), which will remove this kind of issues.

Note that `Uno.SourceGeneration.Host.exe` auto exits after 10 to 15 minutes, with something similar for `adb.exe`. With regards to `adb.exe`, this is android tooling so there's nothing we can do on the Uno side to fix this.

**Comment by SetTrend** [comment]
Thanks so much for clarifying, @jeromelaban!

If I planned to report this issue to the corresponding Alphabet group, did you by chance know where to report this issue to?

I'm not familiar with how the tooling is utilized. What would be a good trigger to kill `adb.exe`? Would the end of the build process be a good place to try to kill `adb.exe`, for example?

From your perspective, is Uno missing some `RequestShutdown()` API function in `adb.exe` that would otherwise allow to gracefully kill the process? Would it help if the corresponding Alphabet team added something similar to a reference counter to `adb.exe` (i.e. `Initialize()` ... build ... `RequestShutdown()`)?

**Comment by jeromelaban** [comment]
With regards to the tooling, Uno does not interact directly with adb.exe but relies on visual studio's Xamarin.Android tooling to do so. It could be that Xamarin can do something about this, or maybe they already have such an issue opened on their github repo.

**Comment by SetTrend** [comment]
Thanks so much again, Jérôme, for sharing your knowledge!
