### ISSUE TITLE
Use new csproj format

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#4172]
## What would you like to be added:

Have the VSIX/cli template generate new csproj-format projects. It should use [MSBuildSdkExtras](https://github.com/novotnyllc/MSBuildSdkExtras) for the unsupported ones.

## Why is this needed:
The old csproj is irritating and inconvenient.

## For which Platform:

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X] Windows
- [ ] Build tasks
- [X] Solution Templates

Related: #4173

**Comment by jeromelaban** [comment]
Thanks, Which projects are you referring to ?

**Comment by weitzhandler** [comment]
Everything under [`SolutionTemplate`](https://github.com/unoplatform/uno/tree/master/src/SolutionTemplate).
The generated Uno solution/projects should be all in new csproj format.

**Comment by jeromelaban** [comment]
Unfortunately no... UWP, and all Xamarin projects cannot use the SDK-style format, as Visual Studio does not support it yet.

**Comment by weitzhandler** [comment]
Would you consider using [MSBuildSdkExtras](https://github.com/novotnyllc/MSBuildSdkExtras)?

**Comment by jeromelaban** [comment]
It's not a matter of msbuild extras, those only work for libraries, not head projects. You can vote on [this issue](https://developercommunity.visualstudio.com/idea/547199/sdk-style-projects-for-ios-and-android-heads.html).

**Comment by weitzhandler** [comment]
For the Xamarin I'm not sure indeed, but for the UWP it's possible.

**Comment by weitzhandler** [comment]
I think I understand now. Let me close this issue then.

**Comment by weitzhandler** [comment]
Related:

- https://github.com/dotnet/project-system/issues/2498
- https://github.com/dotnet/project-system/issues/4704

**Comment by weitzhandler** [comment]
> It's not a matter of msbuild extras, those only work for libraries, not head projects.

Would you be curious in having the shared project of the template as a multi-targetting external assembly, which then uses the new SDK style (See [How to Move Uno Platform Pages to a Multi-Targeting Library](https://christianfindlay.com/2020/08/25/uno-multitargeting) by @MelbourneDeveloper), which we can then easily transport to .NET Core, and once there, upgrade the logging system and use [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1) and service registration altogether?

**Comment by weitzhandler** [comment]
Well apparently there still issues with it (i.e. hot reload), so I guess it's not yet ready.

**Comment by MelbourneDeveloper** [comment]
@weitzhandler apparently, @nickrandolph was able to fix this, and he has instructions in his [article](https://nicksnettravels.builttoroam.com/uno-crossplatform-template/). Unfortunately, I haven't gotten around to checking it out yet.

**Comment by weitzhandler** [comment]
> upgrade the logging system and use [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-3.1) and service registration altogether?

I'm referring to [this](https://bit.ly/3il9D8A).

**Comment by nickrandolph** [comment]
The biggest issue with moving to multi-targeted solution is that the support in Visual Studio for multi-targeted apps is really bad at the moment. Unless you hack the project files (eg https://nicksnettravels.builttoroam.com/multi-targeted-productivity/) then visual studio will build for every platform, every time, which is really painful in a large project.
I think it makes sense for reusuable libraries (eg mvvmcross) to use multi-targeting because at the end of the day you want to generate a single nuget package with all the targets in it. However, for cross platform apps I think the VS experience is better with shared projects and since you can't avoid having separate head projects, there's no real downside to having a shared project.
This may all change with the fall out from .net5 and with Maui which will be a single multi-target project. Both of these are going to require VS to handle multi-targeted projects better

**Comment by MelbourneDeveloper** [comment]
@nickrandolph actually, I'd say the Visual Studio experience with shared projects is almost as bad. Most of the refactoring tools are broken in shared projects. In solutions where I use shared projects, I'm constantly battling issues. 

Yes, Visual Studio support for multi-targeting has issues, but personally, I'd rather deal with those than the issues with shared projects.

**Comment by weitzhandler** [comment]
Regardless of the tooling, from a project management and file locations perspective, I think dealing with shared projects is also more complicated. For example if you're looking at a GitHub or DevOps repo's code with shared projects, it's less straight forward than inline files.

**Comment by MelbourneDeveloper** [comment]
@weitzhandler the tooling is a big part of the issue. One problem I am facing is that the XAML designer doesn't work in the multi-targeted common library. Not sure why and it might be possible to fix it.

Ultimately, someone needs to get this feedback to the Visual Studio team because they've been ignoring these problems for years. I've tried to report things in the past but it just gets lost. They need to at least fix the experience for one of the options. I have a feeling that they don't want to maintain shared projects anymore and might drop them in the next version of Visual Studio. It would be nice if they'd tell us what there plans are. If they're planning on pushing on over the other, we should know about it.

**Comment by weitzhandler** [comment]
Indeed! They're sometimes locking the issues for good not even allowing a discussion. Do you guys think it makes sense to open a new issue with an outline of the various aspects of both shared and multi-targeted projects put together and let them decide on the feasibility and priorities?

Interestingly, Xamarin.Forms core project only has to be .NET Standard, how is it compared to Uno in this aspect?
BTW, this is what a XF app core csproj look like:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xamarin.Forms" Version="4.6.0.1141" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
  </ItemGroup>
</Project>
```

**Comment by MelbourneDeveloper** [comment]
@weitzhandler I remember that a lot of old XF samples used to use shared projects, but gradually they started getting rid of those. I can't say what the best choice for Uno would be, but I can't tell you that I'd definitely prefer to work with a single .NET 5 / .NET 6 project in the long run. That would make life a lot easier, but nobody knows when that will happen.

**Comment by nickrandolph** [comment]
A couple of comments on XF v Uno and the use of shared projects
- Firstly, the main issue with multi-targeted projects is just that when you build them, they'll build for **every** target you have specified in the project file, **every** time. Currently VS doesn't support a mechanism where you can tell it to only build the target that are used by the selected startup project (this is the most obvious fix that the VS team could do to literally save hours of compile time)
- The reason that an XF project can just target .net standard is that by default there's no platform specific code in it. As soon as you start to build custom renderers or effects, you'll either need to put them in the head projects (not recommended), a shared project or a multi-targeted project
- When it comes to XF you can still use shared project but the preference seems to be to move to multi-targeted projects
- With Uno, my preference is still to move any non-ui related code (eg viewmodels, services, models etc) into a separate .net standard project. I leave only UI related code in the multi-targeted or shared project.
- The thing to remember about Uno is that there are a bunch of code generators that kick in when you do a build in order to make the uno magic work. This is all platform specific code and this process is quite expensive if you're doing it every build, for every platform.

**Comment by MelbourneDeveloper** [comment]
All good points @nickrandolph 

Still, shared projects need a lot of work in Visual Studio. I wish the Visual Studio team would give us some options. 

I've actually found that my multi-targeting libraries have the opposite behavior. they don't rebuild every time. I have to manually rebuild in many cases. 

I don't think any of this is a reflection on Uno. The point is that we're talking about huge swathes of functionality in Visual Studio that are simply unfinished.

**Comment by weitzhandler** [comment]
> * I leave only UI related code in the multi-targeted

Yes that's the intention - rather than shared. Shared code feels much more vulnerable for some reason, and it's also harder to maintain.

**Comment by weitzhandler** [comment]
I opened https://github.com/microsoft/microsoft-ui-xaml/issues/3372.
