### ISSUE TITLE
Win UI 3 TabView rearanging (Drag&Drop) tabitems not working on WASM

### ISSUE THREAD

**Issue by roonius** [unoplatform/uno#4274]
## Current behavior
Cannot arrange TabItems by drag & drop in WASM

## Expected behavior
TabItem would change position after Drag&Drop

## How to reproduce it (as minimally and precisely as possible)

Create a project with Microsoft.Toolkit.Uwp.UI.Controls.TabView and add few TabItems
Try to rearrange them on UWP => no issue
Try to rearrange them on WASM => does not work

## Workaround

N/A

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

## Anything else we need to know?

Currently TabView from WinUI 3 has similar issues on UWP as well. Will need that functionality as well on Win UI 3 when Microsoft fixes on it's end.

**Comment by DierkDroth** [comment]
@jeromelaban @dr1rrb  change of plan: Apparently getting drag&drop support will take more time than expected (no pun intended). This made @roonius and myself reconsider the situation:
- @roonius will upgrade our implementation to WinUI 3 TabViews (he already amended the subject of that GitHub accordingly, pls let me know if you needed an amended sample project as well - I believe it's clear what we needed, but please let me know if not)
- We understand that WinUI 3 does not yet support drag&drop for TabViews (on UWP). We intentionally take that pain and rather focused on proper styling the final WinUI3 based (TabView) layout
- We feel it makes for the UNO team more sense to focus on WinUI 3 TabView drag&drop right away instead of investing in WCT TabView which would be legacy/temporary anyway.

Please let me know if you had any questions. Thanks

**Comment by jeromelaban** [comment]
@DierkDroth this makes sense. Adjusting the Uno behavior for both control is most likely the same set of changes in Uno, we'll investigate what needs to be done.

**Comment by dr1rrb** [comment]
This has been fixed by https://github.com/unoplatform/uno/pull/4386

**Comment by DierkDroth** [comment]
Excellent! Thanks @dr1rrb @jeromelaban 

Does this imply it would work for WinUI 2.X TabViews as well?

**Comment by jeromelaban** [comment]
@DierkDroth there's only one TabView in Uno which is coming from WinUI (2 or 3), so yes, it is compatible with WinUI 2.x.

**Comment by DierkDroth** [comment]
Thanks for clarification, @jeromelaban

**Comment by peternary** [comment]
Not working for me on latest builds, do I have to do anything special to enable drag/drop tabs?

Sample project attached with tab drag/drop working on Uwp but not Wasm.

[App70.zip](https://github.com/unoplatform/uno/files/5679838/App70.zip)

**Comment by jeromelaban** [comment]
Thanks for the repro @peternary we'll take a look.

**Comment by dr1rrb** [comment]
@peternary Tabs reordering is disabled by default, you have to enable it by setting both flags `CanDragTabs="True"` and `CanReorderTabs="True"` 

However it's still not working properly (you can reorder tabs but when you drop it, they are not in the right order) ... I'll investigate that.

**Comment by DierkDroth** [comment]
Thanks @dr1rrb. Would be great if you could look into with priority...

**Comment by dr1rrb** [comment]
@DierkDroth this is going to be fixed by https://github.com/unoplatform/uno/pull/4726 ... Actually I've just forgotten to include a commit in my reorder PR 😨

**Comment by DierkDroth** [comment]
Thanks @dr1rrb . @peternary will re-test asap.

**Comment by peternary** [comment]
Appears working in latest
