### ISSUE TITLE
Some controls have hand pointer on hover in WASM

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4523]
## Current behavior

Both `CheckBox` and `RadioButton` switch the mouse cursor to "hand" on hover, whereas for example `ToggleSwitch` or `Slider` does not.

## Expected behavior

For consistency, none of the controls should have a hand cursor, same as in UWP.

## How to reproduce it (as minimally and precisely as possible)

Use `CheckBox` in an WASM app.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.2

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
## More about this...
The "hand" pointer on buttons is a patch that has been done in the first Wasm version of Uno.

It has been [hard-coded in the CSS](https://github.com/unoplatform/uno/blob/82daac9592483d243e9c48a9bbe9dd36fb81043e/src/Uno.UI/WasmCSS/Uno.UI.css#L113_L115) for `<ButtonBase>` controls.

In a web browser, this visual cue is important even if no such point exists on other platforms.

Maybe this should be more tweakable by the app using a configuration or a property instead of being hard-coded on a control like that.
