### ISSUE TITLE
MacOS binding problem caused by ContentControl

### ISSUE THREAD

**Issue by brookslindseyjr** [unoplatform/uno#4626]
## Current behavior

When calling a DataTemplate from a ContentControl, the bindings are not coming through. Works on UWP and WASM, not MacOS.

## Expected behavior

The bindings should use the correct DataContext.

## How to reproduce it (as minimally and precisely as possible)

1. Use the following on MainPage.xaml, with DataContext = ViewModel defined in the code behind.

```
    <UserControl.Resources>
        <DataTemplate x:Key="SignInTemplate">
                <SimpleView DataContext="{Binding SignIn}" />
        </DataTemplate>
    </UserControl.Resources>

    <Grid x:Name="LayoutRoot">
        <ContentControl Content="{Binding}"
                        ContentTemplate="{StaticResource SignInTemplate}">
        </ContentControl>
    </Grid>
```

2. Make the SimpleView.xaml page with this:

`<TextBlock Text="{Binding UserName}" />`

3. Make the ViewModel class with "public SignInViewModel SignIn" property
4. Make the SignInViewModel class with "public string UserName" property
5. Run project

Result:
fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
      The [UserName] property getter does not exist on type [ViewModel]

## Workaround

Surround the view inside the DataTemplate with a border:

```
<DataTemplate x:Key="SignInTemplate">
    <Border>
        <SimpleView DataContext="{Binding SignIn}" />
    </Border>
</DataTemplate>
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [x] Visual Studio for Mac (version: 8.8.2 build 41)
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by kazo0** [comment]
FWIW this also seems to be broken on iOS as well.

**Comment by kazo0** [comment]
This seems to be a bug stemming from the order of operations that are happening during Page initialization.

On Android/WASM/Skia/etc., this is working since the propagation of the Parent `DataContext` is happening **AFTER** `OnContentChanged()` is called. Therefore, the `Text` property of the `TextBlock` is properly having its `DataContext` set to `SignInViewModel` as a result of the logic from the `OnContentChanged()` call.

The problem is that, on iOS/macOS, the propagation of the Parent `DataContext` is happening **BEFORE** `OnContentChanged()` is ever called. So, by the time `OnContentChanged()` _is_ called, the binding for the `TextBlock` is already properly set but since `OnContentChanged()` leads to a call to `SyncDataContext()` [here](https://github.com/unoplatform/uno/blob/59c7ebd63d2d41b1be40f6d7dac1f208a7eb6b79/src/Uno.UI/UI/Xaml/Controls/ContentControl/ContentControl.cs#L416-L441), that binding is being reset to the `Content`'s `DataContext`, which is `ViewModel` instead of `SignInViewModel`. 

The reason wrapping everything inside the `DataTemplate` with a `Border` works is because the `Border` will already contain a `DataContext` of `ViewModel` by the time all of this happens, so it will not cause `OnDataContextChanged()` to be invoked on any of its children since the value didn't change. However, without the `Border`, the value of the `DataContext` is changing on `SimpleView` from `SignInViewModel` to `ViewModel` so the change is raised to the children.
