### ISSUE TITLE
Geolocator.RequestAccessAsync() Hangs on IOS 14.x

### ISSUE THREAD

**Issue by MCAleckson** [unoplatform/uno#4853]
## Current behavior

Geolocator.RequestAccessAsync() never returns if the location permission is denied - in iOS 14 and later only.

## Expected behavior

The function should return null or throw an exception.

## How to reproduce it (as minimally and precisely as possible)

Run this:

                var accessStatus = await Geolocator.RequestAccessAsync();

                if (accessStatus == GeolocationAccessStatus.Allowed)
                   {
                    Geolocator geoLocator = new Geolocator();
                    Geoposition pos = await geoLocator.GetGeopositionAsync();
                   }

## Workaround

I don't have one, other than directing thousands of users to manually grant location permissions to my app.

## Environment

Nuget Package Version(s):

[x] Uno.Core v2.1.0
[x] Uno.Microsoft.Toolkit.Uwp v6.1.0-build.205.g2e0e348372
[x] Uno.UI v3.5.0-dev.57
[x] Uno.UI.RemoteControl v3.5.0-dev.57
[x] Uno.UniversalImageLoader v1.9.33

Affected platform(s):

[ X] iOS

IDE:

- [X] Visual Studio 2019 (version: )

Relevant plugins:

None.

## Anything else we need to know?

No.

**Comment by jeromelaban** [comment]
Thanks for the report!

## Note for contributors

This could be an issue related to the filtering of authorizations here:
https://github.com/unoplatform/uno/blob/ef5961fd9bf1fb6c617de6842ff4cc3643fdf47b/src/Uno.UWP/Devices/Geolocation/Geolocator.iOSmacOS.cs#L128-L135

**Comment by pkar70** [comment]
But as far as I know, geoLocator.ReportInterval is unsupported.
desiredAccuracy is ignored at least for Android (I don't know if this is true also for other platforms).
Also, timeouts are not present on Android implementation (it is ignored), so it can really hang.

There is #2536, which adds timeouts and reportInterval, but only for Android. Waiting since Jan 25.

**Comment by MCAleckson** [comment]
Again, of course, my issue is with the Request

**Comment by Xiaoy312** [comment]
I have ran into this problem before with one of the project I worked on. The issue was with `CLLocationManager::AuthorizationChanged` never fired, however I never make the association with ios14.
I used this hack to get around it: // this was written in march 2018
```cs
// hack: since the event won't fire, we'll monitor the status live
var result = await Observable.Interval(TimeSpan.FromSeconds(1))
    .Select(_ => CLLocationManager.Status)
    .Where(x => x != CLAuthorizationStatus.NotDetermined)
    .Select(x => (bool?)x.IsOneOf(CLAuthorizationStatus.AuthorizedAlways, CLAuthorizationStatus.AuthorizedWhenInUse))
    .FirstAsync(ct);
```
\---
A bit of googling revealed that indeed there is an issue with it: https://github.com/xamarin/Essentials/issues/1390
The same thread also mentioned that `CLLocationManagerDelegate.AuthorizationChanged` could be used instead,
which seem like a better approach, and I can confirm that it is working.
