### ISSUE TITLE
[Gallery] Debug log review

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5108]
## Current behavior

Review the debug log of the different heads.

**Comment by kazo0** [comment]
# WASM:
## Not Implemented
1. `The member CommandBarFlyout.CommandBarFlyout() is not implemented in Uno.`
2. `The member TextCommandBarFlyout.TextCommandBarFlyout() is not implemented in Uno.`
3. `The member RatingItemFontInfo.RatingItemFontInfo() is not implemented in Uno.`
4. `warn: Uno.UI.ResourceResolver[0]: Couldn't statically resolve resource EllipsisButton`
5. `The member AddDeleteThemeTransition.AddDeleteThemeTransition() is not implemented in Uno.`
6. `The member ContentThemeTransition.ContentThemeTransition() is not implemented in Uno.`
7. `The member ReorderThemeTransition.ReorderThemeTransition() is not implemented in Uno.`
8. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.LayoutMetricsChanged is not implemented in Uno.`
9. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.IsVisibleChanged is not implemented in Uno.`
10. `The member event TypedEventHandler<UIElement, GettingFocusEventArgs> UIElement.GettingFocus is not implemented in Uno.`
11. `The member event TypedEventHandler<UIElement, AccessKeyInvokedEventArgs> UIElement.AccessKeyInvoked is not implemented in Uno.`
12. `The member bool CoreApplicationViewTitleBar.IsVisible is not implemented in Uno.`
13. `The member Duration VisualTransition.GeneratedDuration is not implemented in Uno.`

## Binding Issues

1. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.NavigationViewList]`
2. `The [Uno.Material.Extensions:ControlExtensions.Icon] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`
3. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`
 
## DP

1. `The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.Image`
2. `The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.FontIcon`
3. `The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.Viewbox`
4. `The BorderThicknessProperty dependency property does not exist on Windows.UI.Xaml.Controls.ItemsPresenter`

## Resources

1. `Couldn't statically resolve resource TopNavigationViewItemForegroundLow`

**Comment by kazo0** [comment]
# Android

## Not Implemented

1. `The member CommandBarFlyout.CommandBarFlyout() is not implemented in Uno.`
2. `The member TextCommandBarFlyout.TextCommandBarFlyout() is not implemented in Uno.`
3. `The member RatingItemInfo.RatingItemInfo() is not implemented in Uno.`
4. `The member RatingItemFontInfo.RatingItemFontInfo() is not implemented in Uno.`
5. `The member AddDeleteThemeTransition.AddDeleteThemeTransition() is not implemented in Uno.`
6. `The member ContentThemeTransition.ContentThemeTransition() is not implemented in Uno.`
7. `The member ReorderThemeTransition.ReorderThemeTransition() is not implemented in Uno.`
8. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.LayoutMetricsChanged is not implemented in Uno.`
9. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.IsVisibleChanged is not implemented in Uno.`
10. `The member event TypedEventHandler<UIElement, GettingFocusEventArgs> UIElement.GettingFocus is not implemented in Uno.`
11. `The member event TypedEventHandler<UIElement, AccessKeyInvokedEventArgs> UIElement.AccessKeyInvoked is not implemented in Uno.`
12. `The member bool CoreApplicationViewTitleBar.IsVisible is not implemented in Uno.`
13. `The member event TypedEventHandler<FrameworkElement, object> FrameworkElement.ActualThemeChanged is not implemented in Uno.`

## Binding Issues

1. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.NavigationViewList]`
2. `The [Uno.Material.Extensions:ControlExtensions.Icon] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`
3. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`

## Resources

1. `Couldn't statically resolve resource TopNavigationViewItemForegroundLow`
2. `Couldn't statically resolve resource EllipsisButton`

**Comment by kazo0** [comment]
# macOS

## Native Warnings

1. `*** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. `

## Not Implemented

1. `The member Duration VisualTransition.GeneratedDuration is not implemented in Uno.`
2. `IsTextPredictionEnabled isn't supported on macOS.`
3. `The member bool CoreApplicationViewTitleBar.Height is not implemented in Uno.`
4. `The member bool CoreApplicationViewTitleBar.ExtendViewIntoTitleBar is not implemented in Uno.`
5. `The member event TypedEventHandler<UIElement, AccessKeyInvokedEventArgs> UIElement.AccessKeyInvoked is not implemented in Uno.`
6. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.IsVisibleChanged is not implemented in Uno.`
7. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.LayoutMetricsChanged is not implemented in Uno.`
8. `The member event TypedEventHandler<UIElement, GettingFocusEventArgs> UIElement.GettingFocus is not implemented in Uno.`
9. `The member event EventHandler<ScrollViewerViewChangingEventArgs> ScrollViewer.ViewChanging is not implemented in Uno.`
10. `The member RatingItemFontInfo.RatingItemFontInfo() is not implemented in Uno.`
11. `The member RatingItemInfo.RatingItemInfo() is not implemented in Uno.`
12. `The member TextCommandBarFlyout.TextCommandBarFlyout() is not implemented in Uno.`
13. `The member CommandBarFlyout.CommandBarFlyout() is not implemented in Uno.`

## Binding Issues

1. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`
2. `The Bindable attribute is missing and the type [Uno.Gallery.Sample] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`
3. `The Bindable attribute is missing and the type [Uno.Material.Extensions.ControlExtensions] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`
4. `The [AutomationProperties] property getter does not exist on type [Microsoft.UI.Xaml.Controls.NavigationView]`
5. `The Bindable attribute is missing and the type [Windows.UI.Xaml.Automation.AutomationProperties] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`

## Resources

1. `Couldn't statically resolve resource EllipsisButton`

## Fonts

1. `Failed to apply Font Segoe UI`
2. `Failed to apply Font Segoe UI-Medium`
3. `Failed to apply Font Segoe UI`
4. `Failed to apply Font XamlAutoFontFamily-Medium`
5. `Failed to apply Font Segoe UI`
6. `Failed to apply Font Roboto`
7. `Failed to apply Font XamlAutoFontFamily`
8. `Failed to apply Font XamlAutoFontFamily-DemiBold`
9. `Failed to apply Font Segoe UI`
10. `Failed to apply Font Segoe UI`
11. `Failed to apply Font Roboto`
12. `Failed to apply Font XamlAutoFontFamily`

**Comment by kazo0** [comment]
# iOS

## Not Implemented

1. `IsTextPredictionEnabled isn't supported on iOS. Use IsSpellCheckeEnabled instead.`
2. `The member bool CoreApplicationViewTitleBar.Height is not implemented in Uno.`
3. `The member bool CoreApplicationViewTitleBar.ExtendViewIntoTitleBar is not implemented in Uno.`
4. `The member event TypedEventHandler<UIElement, AccessKeyInvokedEventArgs> UIElement.AccessKeyInvoked is not implemented in Uno.`
5. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.IsVisibleChanged is not implemented in Uno.`
6. `The member event TypedEventHandler<CoreApplicationViewTitleBar, object> CoreApplicationViewTitleBar.LayoutMetricsChanged is not implemented in Uno.`
7. `The member event TypedEventHandler<UIElement, GettingFocusEventArgs> UIElement.GettingFocus is not implemented in Uno.`
8. `The member event EventHandler<ScrollViewerViewChangingEventArgs> ScrollViewer.ViewChanging is not implemented in Uno.`
9. `The member RatingItemFontInfo.RatingItemFontInfo() is not implemented in Uno.`
10. `The member RatingItemInfo.RatingItemInfo() is not implemented in Uno.`
11. `The member TextCommandBarFlyout.TextCommandBarFlyout() is not implemented in Uno.`
12. `The member CommandBarFlyout.CommandBarFlyout() is not implemented in Uno.`

## Binding Issues

1. `The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]`
2. `The Bindable attribute is missing and the type [Uno.Material.Extensions.ControlExtensions] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`
3. `The Bindable attribute is missing and the type [Uno.Gallery.Sample] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`
4. `The [AutomationProperties] property getter does not exist on type [Microsoft.UI.Xaml.Controls.NavigationView]`
5. `The Bindable attribute is missing and the type [Windows.UI.Xaml.Automation.AutomationProperties] is not known by the MetadataProvider. Reflection was used instead of the binding engine and generated static metadata. Add the Bindable attribute to prevent this message and performance issues.`

## Resources

1. `Couldn't statically resolve resource EllipsisButton`

## Fonts

1. `Failed to apply Font XamlAutoFontFamily`
2. `Failed to apply Font Segoe UI`
3. `Failed to apply Font Segoe UI-Medium`
4. `Failed to apply Font Segoe UI`
5. `Failed to apply Font XamlAutoFontFamily-Medium`
6. `Failed to apply Font Segoe UI`
7. `Failed to apply Font Roboto`
8. `Failed to apply Font XamlAutoFontFamily-DemiBold`
9. `Failed to apply Font Roboto`
10. `Failed to apply Font Segoe UI`
11. `Failed to apply Font Segoe UI`
