### ISSUE TITLE
[Gallery][Android/iOS)] CommandBar - For Android back button is not displaying correctly and for iOS overlapping on burger menu.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5337]
## Current behavior
![Back button issue](https://user-images.githubusercontent.com/74563602/109357507-4da04d00-7850-11eb-9d1d-5bc1e57284e6.png)
![Back button issue 2](https://user-images.githubusercontent.com/74563602/109357513-5133d400-7850-11eb-8f8f-0338cf8b6b3d.png)

## Expected behavior
The Back button should display correctly.

## How to reproduce it 

1. Open Uno Gallery APP for canary.
2. Click Burger Menu on the left top right.
3. Click "Commandbar" from the Burger Menu list
4. Click on the "Show Sample" option.
5. Observe the back button located on the left side of the commandbar is not displaying correctly and overlapping on Burger menu .

Version(s):
Version 1.4.3 (400726)
Feb 23, 2021 at 22:16

Device:
Samsung S8 - 8.0
Motorola g(7) – 9
iPhone 12 - 14.1

Affected platform(s):
Android
iOS

**Comment by jeromelaban** [comment]
May be related to https://github.com/unoplatform/uno/pull/5336

**Comment by Xiaoy312** [comment]
The issue here is the NavigationView display on top of the nested page* when it should not.
What we see here isnt no a broken `Path`, but `三` menu of NavView (of the app) on top of `<` back button for CommandBar (of the sample).

nested page: These are special pages in uno.gallery show-casing features/controls conflict/interfere with the nav-view, as seen this issue...

**Comment by Xiaoy312** [comment]
On a closer look, the `<` back button icon does _appears smaller than what it _should_ be.
