### ISSUE TITLE
Binding Source on an Image to BitmapImage does not work in Wasm

### ISSUE THREAD

**Issue by bjorndaniel** [unoplatform/uno#5387]
## Current behavior

Setting the Source on an Image to a BitmapImage shows nothing when running Uno.Wasm

## Expected behavior

The image should be displayed

## How to reproduce it (as minimally and precisely as possible)

A small working sample is here:

https://github.com/bjorndaniel/UnoWasmImageBug

The app shows an image on the mainpage that gets bound in the OnAppearing-method

## Environment

Nuget Package:

- [ X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ X] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.6.0-dev.275
Uno.UI.WebAssembly 3.6.0-dev.275
Affected platform(s):

- [ ] iOS
- [ ] Android
- [ X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X ] Visual Studio 2019 (version: ) 16.10.0 preview 1
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Thanks for the report.

The issue here is not a binding error, [but rather a CORS error](https://platform.uno/docs/articles/get-started-wizard.html#webassembly-access-to-fetch-at-httpsxxxx-from-origin-httpxxxx-has-been-blocked-by-cors-policy). The image you're referring to is not CORS-enable, and makes the download fail as you will see in the browser's debugger logs.

If you change the URL to one that is CORS enabled (e.g. https://api.nuget.org/v3-flatcontainer/serilog/2.10.1-dev-01285/icon) you'll notice the image appearing.

**Comment by bjorndaniel** [comment]
@jeromelaban I totally missed that in the debugger logs, thanks for the quick reply and sorry for the hassle.
P.S On the web, it is always CORS :)

**Comment by jeromelaban** [comment]
No worries at all :) Yes, agreed that on the web, it's always CORS!
