### ISSUE TITLE
C# for Markup port

### ISSUE THREAD

**Issue by keozx** [unoplatform/uno#5410]
## What would you like to be added:

- A port of C# for Markup extensions from the Xamarin Community Toolkit https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/Markup

- Originally from @VincentH-Net here https://github.com/VincentH-Net/CSharpForMarkup

## Why is this needed:

- For a lot of folks, XAML is no longer the preferred UI definition language, C# for Markup is gaining popularity as an alternate to create UI declaratively

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

- If anyone is doing an effort towards this, please let me know as I would like to help with that, otherwise I can start doing it
- Does anyone think this is better suited as a separate project or part of XCT?

**Comment by francoistanguay** [comment]
VincentH is already working on a CS4M port to WinUI/Uno. You should ping him.

**Comment by francoistanguay** [comment]
Uno also started as a C#-first library. We added XAML parsing support shortly after.

Challenge with Razor-like syntax lies in its limitations. No support for an Attached Property syntax being one of the main ones.

On the C#-first side, pretty sure we'll get there eventually and offer it as an option although we believe there's still a lot that can be done to make the MVVM pattern less miserable and more Reactive-Functional friendly.

Main problem with C#-first approach lies in lack of tooling for Code formatting, syntax highlighting (everything is a fluent-syntax method). 

And ideally, you'd still want to keep your C#-first "markup code" separate from your C# presentation/business logic code as otherwise it truly complicates C# Hot Reload scenarios.

So expect to see our investments most probably be:
1. Make Uno better and more complete
2. Possibly improve on some presentation patterns (A mix of RxUI and MVVM, but better) -> We've been using this internally at nventive and it rocks!
3. C# for Markup support once tooling gets there, knowing there will me some limitations on the WinUI heads as they dont support some C# first scenarios like DataTemplate instanciation
4. MobileBlazorBindings/Razor syntax would have to improve for us to consider

**Comment by robloo** [comment]
> Challenge with Razor-like syntax lies in its limitations. No support for an Attached Property syntax being one of the main ones.

While Blazor/Razor don't support this, using a similar syntax for XAML would require a different parser which could support it without much trouble. Oversimplifying, it's really just allowing fragments of XAML and C# in the same source file. Existing XAML syntax would be used in the vast majority of cases (including attached properties).

> Possibly improve on some presentation patterns (A mix of RxUI and MVVM, but better) -> We've been using this internally at nventive and it rocks!

Sounds very interesting!

> C# for Markup support once tooling gets there, knowing there will me some limitations on the WinUI heads as they dont support some C# first scenarios like DataTemplate instanciation

Personally, whenever UI's are better done in code I've seen vanilla C# used to get things done. I don't understand the push to make is so declarative (Apple does have powerful marketing though). Anyway, whatever people want to experiment with is great as long as it doesn't break XAML for the rest of us.

And good point on the DataTemplate instantiation limitations. Loosing this functionality in code-behind in WinUI has caused difficult problems to solve. The ugliest issues arise when you can't get a reference to a template generated UIElement because that simply isn't supported anymore [Find ControlTemplate-Generated Elements](https://docs.microsoft.com/en-us/dotnet/desktop/wpf/controls/how-to-find-controltemplate-generated-elements?view=netframeworkdesktop-4.8).

**Comment by keozx** [comment]
> VincentH is already working on a CS4M port to WinUI/Uno. You should ping him.

Nice, I was expecting that would be the case but didn't find anything in the open, so I'll ping him :)

**Comment by saint4eva** [comment]
> ## What would you like to be added:
> * A port of C# for Markup extensions from the Xamarin Community Toolkit https://github.com/xamarin/XamarinCommunityToolkit/tree/main/src/Markup
> * Originally from @VincentH-Net here https://github.com/VincentH-Net/CSharpForMarkup
> 
> ## Why is this needed:
> * For a lot of folks, XAML is no longer the preferred UI definition language, C# for Markup is gaining popularity as an alternate to create UI declaratively
> 
> ## For which Platform:
> * [x]  iOS
> * [x]  Android
> * [x]  WebAssembly
> * [x]  WebAssembly renderers for Xamarin.Forms
> * [x]  macOS
> * [ ]  Skia
>   
>   * [ ]  WPF
>   * [ ]  GTK (Linux)
>   * [ ]  Tizen
> * [x]  Windows
> * [ ]  Build tasks
> * [ ]  Solution Templates
> 
> ## Anything else we need to know?
> * If anyone is doing an effort towards this, please let me know as I would like to help with that, otherwise I can start doing it
> * Does anyone think this is better suited as a separate project or part of XCT?

This is a welcome effort. Could you make it C# MVU than mvvm? Thank you.

**Comment by saint4eva** [comment]
> Uno also started as a C#-first library. We added XAML parsing support shortly after.
> 
> Challenge with Razor-like syntax lies in its limitations. No support for an Attached Property syntax being one of the main ones.
> 
> On the C#-first side, pretty sure we'll get there eventually and offer it as an option although we believe there's still a lot that can be done to make the MVVM pattern less miserable and more Reactive-Functional friendly.
> 
> Main problem with C#-first approach lies in lack of tooling for Code formatting, syntax highlighting (everything is a fluent-syntax method).
> 
> And ideally, you'd still want to keep your C#-first "markup code" separate from your C# presentation/business logic code as otherwise it truly complicates C# Hot Reload scenarios.
> 
> So expect to see our investments most probably be:
> 
> 1. Make Uno better and more complete
> 2. Possibly improve on some presentation patterns (A mix of RxUI and MVVM, but better) -> We've been using this internally at nventive and it rocks!
> 3. C# for Markup support once tooling gets there, knowing there will me some limitations on the WinUI heads as they dont support some C# first scenarios like DataTemplate instanciation
> 4. MobileBlazorBindings/Razor syntax would have to improve for us to consider

I think partial classes could solve the problem of separation. Maybe, you could take a look at how Comet does it (https://github.com/dotnet/Comet).

I believe C# should have better tooling than xaml in any IDE.

**Comment by saint4eva** [comment]
> On the C#-first side, pretty sure we'll get there eventually and offer it as an option although we believe there's still a lot that can be done to make the MVVM pattern less miserable and more Reactive-Functional friendly.
> 
> Main problem with C#-first approach lies in lack of tooling for Code formatting, syntax highlighting (everything is a fluent-syntax method).
> 
> And ideally, you'd still want to keep your C#-first "markup code" separate from your C# presentation/business logic code as otherwise it truly complicates C# Hot Reload scenarios.

> 3. C# for Markup support once tooling gets there, knowing there will me some limitations on the WinUI heads as they dont support some C# first scenarios like DataTemplate instanciation


I think partial classes could solve the problem of separation. Maybe, you could take a look at how Comet does it (https://github.com/dotnet/Comet).

I believe C# should have better tooling than xaml in any IDE.

**Comment by VincentH-Net** [comment]
>  I think partial classes could solve the problem of separation. Maybe, you could take a look at how Comet does it (https://github.com/dotnet/Comet).

That has indeed been the way in C# Markup from the start, see [here](https://docs.microsoft.com/en-us/xamarin/community-toolkit/markup):
> _Just as with XAML, C# Markup enables a clean separation between UI markup and UI logic. This can be achieved by separating UI markup and UI logic into distinct partial class files. For example, for a login page the UI markup would be in a file named LoginPage.cs, while the UI logic would be in a file named LoginPage.logic.cs._

**Comment by jeromelaban** [comment]
Uno Platform 5.0 introduces C# Markup, see [our announcement](https://aka.platform.uno/blog-5-0).
