### ISSUE TITLE
[VS 2019] Creating new project and selecting support only to Webassembly create a Skia.Tizen project 🤷‍♂️

### ISSUE THREAD

**Issue by microhobby** [unoplatform/uno#5447]
## Current behavior

When creating a new project the wizard shows some checkboxes to add support for multiple platforms. Choosing only webassembly results in a project only for the Skia.Tizen platform 🤷‍♂️

![8xQm4jIdnr](https://user-images.githubusercontent.com/2633321/110809346-8f26f400-8263-11eb-9bba-0d8e464dba93.gif)

## Expected behavior

Creating a new project and checking only the support to Webassembly should create a project with only webassembly support.

## How to reproduce it (as minimally and precisely as possible)

- Open VS 2019
- Create e new project
- Select uno cross platform template
- Uncheck all platforms on wizard
- Check support for Webassembly only

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.0 Preview 5.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )
- [ ] VS 2019 Extension (version: 3.5.1.7)

**Comment by ebariche** [comment]
There are two issues here:

1- That template includes its own sln file but VS is not using it. VS tries to generate a new one but fails. The WASM head is never included and neither is one of the WPF projects. Regardless of what option(s) you choose.

![image](https://user-images.githubusercontent.com/33458222/112690791-c516cb80-8e52-11eb-9980-bb1f69344fdf.png)

2- There is no option to include/exclude Tizen in the UI. Because the option is not specified, the default is to generate the head.

@microhobby, could you verify if there is two sln files on disk and that one of them has both Tizen + Wasm ?

In the meantime, use the VSIX or the CLI !

@jeromelaban, I think we need to talk to MS on this one, VS and vs4mac are affected.
