### ISSUE TITLE
[Gallery][Android] DatePicker is not working properly for Material and Fluent.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5471]
## Current behavior

https://user-images.githubusercontent.com/74563602/111212401-ee5b7000-85a5-11eb-9cad-98d60d942e4b.mp4

## Expected behavior
-The Date should get select when click right sign.
-When little scroll the page down of Date picker and then click "Set Date", the date calendar page should display correctly.

## How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "DatePicker" from the "Component" list.
4. Click on the "ser Date" in the Default section."
5. Choose the date from the calendar and then click right sign on the calendar.
6. Observe the date doesn't change for the "Set Date".
7. Again click on "set Date" and now again click on right sign on the calendar.
8. Observe now the date change for the "Set Date".
9. Now bit scrolldown the date Picker screen and click on "set Date".
10. Observe that the calendar is not displaying correctly.

Version(s):
Version 1.4.3 (400741)
Mar 01, 2021 at 11:21

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by carldebilly** [comment]
## Result of the bug investigation
The problem is occurring in the `LoopingSelector` used in the `DatePickerFlyoutPresenter`. It's waiting for a _non-intermediate_ `ScrollChanged` event from its the `ScrollViewer`, which is never coming (all events are `IsIntermediate=true`).

So the bug is definitely in the Uno implementation of `ScrollViewer`.

**Comment by sakshi173** [comment]
Issue is fixed, closing it.
