### ISSUE TITLE
`UIElementExtensions.Elevation` breaks VS designer

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#5513]
## Current behavior
When setting `UIElementExtensions.Elevation` attached property for an element, the Visual Studio designer shows an error, but it compiles fine and works fine in a running app.

![image](https://user-images.githubusercontent.com/16724889/111705258-17e7f600-8849-11eb-8c26-53b9c7b333e9.png)

## Expected behavior
The VS designer must show the rendered XAML.

## How to reproduce it (as minimally and precisely as possible)
[App4.zip](https://github.com/unoplatform/uno/files/6167527/App4.zip)

Set `Elevation`, build the UWP project, see the error in the VS designer.

## Workaround
Set `UIElementExtensions.Elevation` via code-behind or don't use it at all.

## Environment

Nuget Package:

- [x] Uno.UI
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.2), Version 16.10.0 Preview 1.0
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

To fix this, just remove `this` in `this UIElement element`. VS doesn't like these are extension methods.

https://github.com/unoplatform/uno/blob/a6bb7ecaceb1908172a896733c74871ca261a799/src/Uno.UI.Toolkit/UIElementExtensions.cs#L30

https://github.com/unoplatform/uno/blob/a6bb7ecaceb1908172a896733c74871ca261a799/src/Uno.UI.Toolkit/UIElementExtensions.cs#L35

**Comment by Youssef1313** [comment]
Instead of introducing a breaking change, why this is not considered a bug in VS designer?

**Comment by Youssef1313** [comment]
The designer isn't working at all for me in a plain new UWP project:

![image](https://user-images.githubusercontent.com/31348972/235876469-9acd744f-a4b5-4e32-bcd4-12a5041521f3.png)

Also it looks like WinUI doesn't even support a designer yet? https://github.com/microsoft/microsoft-ui-xaml/issues/5917

It's worth noting that the code doesn't give IntelliSense warnings:

![image](https://user-images.githubusercontent.com/31348972/235876848-0917087f-f96d-4bcb-933f-4fd5e3b52222.png)

In the issue, it used to have a squiggly warning, so something might have already been fixed in Visual Studio.

**Comment by MartinZikmund** [comment]
So maybe this can be closed now? The designer is not even planned for WinUI so far...
