### ISSUE TITLE
[WASM] CapturePointer use can prevent child controls from processing pointer events

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#5638]
## Current behavior

If a control captures a pointer then child controls may not properly process events like PointerPress

## Expected behavior

Child events should still function normally, as in UWP

## How to reproduce it (as minimally and precisely as possible)

Open the attached project in UWP and attempt to open the ComboBox - notice it behaves normally.  Open the same project in WASM and observe that the ComboBox cannot be opened.

[MouseFocus.zip](https://github.com/unoplatform/uno/files/6239193/MouseFocus.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.7.0-dev.92
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
Duplicates with https://github.com/unoplatform/uno/issues/3592

**Comment by dr1rrb** [comment]
This is actually not linked to #3592 (which seems to be fixed), but is instead a bug in the `ComboBox` which is does not handles the `PointerPressed` event, driving the parent element to capture it (fixed by https://github.com/unoplatform/uno/pull/6653).

In the repro, on UWP the `SomePointerEvent` is actually never invoked (registered only on pointer pressed on the `testGrid`). But if we register it also on pointer move, and then we press, move a bit while staying on the combo, and release, the combo will not open anymore.

**Comment by peternary** [comment]
Appears resolved in latest
