### ISSUE TITLE
[Skia.Gtk] ScrollViewer ScrollBar not shown

### ISSUE THREAD

**Issue by TrevorDArcyEvans** [unoplatform/uno#5666]
## Current behavior
XAML has:
`ScrollViewer.HorizontalScrollBarVisibility="Visible" `
`ScrollViewer.VerticalScrollBarVisibility="Visible" `

but no scrollbars are not shown on Skia.Gtk aka Linux

## Expected behavior
scrollbars should be shown

## How to reproduce it (as minimally and precisely as possible)
[Uno.ZoomPanControl.zip](https://github.com/unoplatform/uno/files/6252953/Uno.ZoomPanControl.zip)

## Workaround
none

## Environment
Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [x] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by mikebmcl** [comment]
@jeromelaban I ran into this issue using WSL2 and found what seems to be the problem and the solution to it. In [GtkHost.cs](https://github.com/unoplatform/uno/blob/master/src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs) there are the following lines:

`_window.Realized += (s, e) =>`
`{`
`	WUX.Window.Current.OnNativeSizeChanged(new Windows.Foundation.Size(_window.AllocatedWidth, _window.AllocatedHeight));`
`};`
` `
`_window.SizeAllocated += (s, e) =>`
`{`
`	WUX.Window.Current.OnNativeSizeChanged(new Windows.Foundation.Size(e.Allocation.Width, e.Allocation.Height));`
`};`

The invocation of `OnNativeSizeChanged` raises various events and, most importantly, sets the Window.Bounds to the value passed in, which is used for sizing for layout. On some systems the value of the Window's ActualWidth/Height is reported as being the same size as the client area. On WSL 2 (and probably other systems) it includes non-client area stuff such as the title bar and even a bit of padding around the window.

In the file linked above, Gtk defaults the window size to 1024x800 unless some other size is specified. On WSL on my computer (Windows 11 Pro Build 22000, WSL 2 kernel version 5.10.60.1 openSUSE-Leap-15.3, and [WSL's recent addition of GUI support](https://devblogs.microsoft.com/commandline/the-initial-preview-of-gui-app-support-is-now-available-for-the-windows-subsystem-for-linux-2/) via a Wayland implementation), the Page's ActualWidth/Height is reported as 1076x889 rather than 1024x800. Via a screenshot I confirmed that the actual client area is 1024x800 and that it's including the titlebar and some padding in the Page's Actual values. This leads to the scrollbar rendering offscreen. You don't even need a ScrollViewer, in fact. If you simply create a Grid with a Border (or anything else that will fill the page and has a border) the border will also go off screen on the right and the bottom.

The solution: in the file above, remove those lines mentioned above. Then, several lines after that are is the following line:

`_area = new UnoDrawingArea();`

After those lines add the following:

`_area.Realized += (s, e) =>`
`{`
`	WUX.Window.Current.OnNativeSizeChanged(new Windows.Foundation.Size(_area.AllocatedWidth, _area.AllocatedHeight));`
`};`
`_area.SizeAllocated += (s, e) =>`
`{`
`	WUX.Window.Current.OnNativeSizeChanged(new Windows.Foundation.Size(e.Allocation.Width, e.Allocation.Height));`
`};`

We change it so that the sizing uses the values for the `UnoDrawingArea` where all of the Uno drawing occurs rather than the Window itself. That UnoDrawingArea's ActualWidth/Height are 1024x800 both in WSL2 and when running the Skia.Gtk project in Windows itself via [SolutionName].Skia.Gtk rather than WSL. (Incidentally, [SolutionName].Skia.Gtk reports the correct Page sizes even without the modification above, presumably because of some implementation difference between Gtk on Windows versus Gtk on Linux).

This behavior is consistent with UWP in that UWP also reports the Page's ActualWidth/ActualHeight as the size of the client area (adjusted for scaling) not including the title bar or anything else.

ScrollViewer seems to have a separate issue with how it calculates its ExtentHeight in that it appears to disregard its own Padding and the Margin of its Content (just the ContentControl itself; everything within that appears to be sized and layed out correctly). This also occurred on Skia.Wpf and on Wasm but did not occur on Android or UWP. I'll search to see if I find an existing issue about it and if not I'll create one.

If you want to see that problem in the meantime, simply put a ScrollViewer in a page, put something like a Grid or a StackPanel in it, fill that with enough content that it will go past the bounds of the page, then either add a Padding of 12+ to the ScrollViewer or add a Margin value in the 12+ range to the ContentControl you put in the ScrollViewer (or do both) and the problem will appear on Skia.Wpf and WASM (and on Skia.Gtk with this fix applied). 12+ value is intended to be large enough that it will clearly be visible; the problem still exists even if it's less than that.

If you'd like me to submit a pull request for this issue, just let me know.

**Comment by mikebmcl** [comment]
@jeromelaban I created a pull request for a fix: [fix(Skia.Gtk): Incorrect window ActualWidth and ActualHeight values on WSL and Linux #7665](https://github.com/unoplatform/uno/pull/7665). Let me know if you need me to do anything else for it or if I made any mistake!
