### ISSUE TITLE
Documentation broken?!?

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5712]
I flipped through a couple of pages. Looks like the content is broken on some pages, no? There used to be complete lists of 'implemented' and 'not implemented' properties/methods...

https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-button.html
https://platform.uno/docs/articles/controls/Flyout.html

**Comment by davidjohnoliver** [comment]
For Button, it looks correct, bearing in mind it only covers properties on Button itself. From UWP's docs those are:
![image](https://user-images.githubusercontent.com/8270914/114211047-29935980-992e-11eb-868c-51396abbc572.png)

Note you can see more properties on the Uno page if you click through to the base types (`ButtonBase` etc) . I don't think there's a regression here.

For `Flyout` it's a different issue, there's no generated page since it's not actually a true control and the generated implemented/not-implemented coverage is only created for controls at the moment. (This issue is tracking extending the coverage to all types: https://github.com/unoplatform/uno/issues/2415)

**Comment by DierkDroth** [comment]
Thanks for clarification @davidjohnoliver
