### ISSUE TITLE
TextWrapping property is ignored on Skia

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#5735]
## Current behavior

Hi, I'm using some fixed size buttons with TextBlocks inside them but setting TextWrapping to Wrap or WrapWholeWords doesn't seem to have any effect on Skia Gtk and Wpf (text is shown in a single line and clipped), while it works on UWP and Android. I haven't tested other platforms yet.

![Screenshot (1589)](https://user-images.githubusercontent.com/45036600/114397164-a9bff600-9b9e-11eb-9e63-525572ae5151.png)

## Expected behavior

TextWrapping should be applied as in UWP and Android.

## Workaround

None, I've also tried entering `<NewLine/>` manually but it's rendered as "▯".

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.6.6

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment]
Will be partially addressed by https://github.com/unoplatform/uno/pull/5706

**Comment by manfromarce** [comment]
Ok, thank you

**Comment by MagnusAtMawik** [comment]
Any update on this issue?
TextWrapping in TextBlock's doesn't work on Gtk/Skia (running on a Linux Raspberry Pi). It does work on UWP (running on Windows) though.
The text is going outside the screen, getting cut off.
Running version 4.1.8 of Uno.

`<TextBlock FontSize="20" TextWrapping="Wrap">A very long text that should be breaking into a new line but it doesnt on GTK/SKIA.</TextBlock>`

Manually adding <LineBreak / > at suitable spots is not an option since the texts are dynamic (from user input etc...).

**Comment by bsvabic** [comment]
Any update about this?

**Comment by francoistanguay** [comment]
@MartinZikmund  Isnt this working now?

**Comment by MartinZikmund** [comment]
Yes, it should be working well
