### ISSUE TITLE
MenuFlyout dead on Skia

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#5882]
## Current behavior
`MenuFlyout` does not interact in any way on Skia targets.

## Expected behavior
`MenuFlyout` should work.

## How to reproduce it (as minimally and precisely as possible)
- Create a Hello World Uno project.
- Add a `RightTapped` event 
- Show a `MenuFlyout`.
- Try to click on an option. `MenuFlyout` does not hide, and no events are fired.
- Click outside the `MenuFlyout`. It hides normally.

Sample project:
[ContextMenuTest.zip](https://github.com/unoplatform/uno/files/6409644/ContextMenuTest.zip)

## Workaround
~Use a `Flyout` and dump some `Button`s on a `StackPanel`.~

Create a `StupidMenuFlyoutItem` that inherits from `MenuFlyoutItem` and override this method:

```C#
        protected override void OnPointerPressed(PointerRoutedEventArgs args)
        {
            System.Diagnostics.Debug.WriteLine("Pressed");
            CapturePointer(args.Pointer);
            base.OnPointerPressed(args);
        }
```

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): Tested on latest 3.7.3

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by trungnt2910** [comment]
Seems like the `MenuFlyout` have problems recognizing the `PointerReleased` event.
It detects `PointerEntered`, `PointerPressed`, and `PointerExited` properly.

**Comment by trungnt2910** [comment]
After more digging, the root of this problem seems to be the fact that `Flyout` does not handle `PointerReleased` event properly for any controls, including custom ones.

**Comment by trungnt2910** [comment]
Somehow on Skia targets you must `Capture` the pointer to make it raise a `PointerReleased` event.

**Comment by trungnt2910** [comment]
Oh, so Uno **does** [capture the pointer](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/UIElement.Pointers.cs#L740). But I wonder what's happening to that line.

**Comment by trungnt2910** [comment]
Reproduced this issue with _any_ control with `DefaultStyleKey = typeof(FlyoutPresenter)`, even for custom `Button`s.

**Comment by trungnt2910** [comment]
After messing up with [this](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Style/Generic/FlyoutPresenter.xaml) and removed elements, I found out that the root of this problem is the `ScrollViewer`.

**Comment by dr1rrb** [comment]
@trungnt2910  Basically a "capture" allows a control to track the pointer even when out of it bounds (and even when out of the bounds of the application, on supported platform ... but skia GTK is not). It's required for touch (and maybe pen) scrolling.

But actually we are not really capturing the pointer in the `ScrollContentPresenter`, we are relying on manipulations https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs#L119. **BUT** you're right: manipulations can actually capture the pointer to track it out of the bound of the window.

We are managing captures internally, and we have a concept of "implicit captures" (https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/UIElement.PointerCapture.cs#L28). They correspond to captures we are internally requesting to the system for events like manipulations, while "explicit captures" are the capture made by the application (or controls like `Button`), a.k.a. `UIElement.Capture`.

> 
> 
> Somehow on Skia targets you must `Capture` the pointer to make it raise a `PointerReleased` event for controls on `Flyout`s. Just don't know how to handle this properly.

This actually sounds like a dispatch issue: I'm wondering if the pointer release is actually not raised because the `Flyout` is being close a bit too early?

**Comment by trungnt2910** [comment]
> This actually sounds like a dispatch issue: I'm wondering if the pointer release is actually not raised because the `Flyout` is being close a bit too early?

Hmm, no. I've stepped through library code, until [here](https://github.com/unoplatform/uno/blob/73b37971a74d6fb0b5f9bbd7546ac187ed66b25b/src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs#L198).
And I got this:
![image](https://user-images.githubusercontent.com/57174311/116883870-46caf780-ac50-11eb-98d7-bed9d83688dd.png)
Seems to me that the `ScrollContentPresenter` has indeed captured the Pointer, while the `originalSource`, the `TextBlock`, is muted.

> we have a concept of "implicit captures"

I've dug through your code and found that. But it still confuses me when I don't see any calls to `Capture` from either `ScrollContentPresenter` or `ScrollViewer`

> But actually we are not really capturing the pointer in the ScrollContentPresenter, we are relying on manipulations.

That seems new. I will try to investigate that.

Anyway, another interesting thing that if you put the `ScrollContentPresenter` directly in a `Grid`, it works well, but if you use it with a `ScrollViewer`, it mutes its children.

**Comment by dr1rrb** [comment]
@trungnt2910 

> I've dug through your code and found that. But it still confuses me when I don't see any calls to Capture from either ScrollContentPresenter or ScrollViewer

Actually it's the line you have highlighted which causes the capture: As the `ScrollContentPresenter` has [enabled the manipulations](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/ScrollContentPresenter/ScrollContentPresenter.Managed.cs#L119), the `GestureRecognizer` kicked-in on [this line](https://github.com/unoplatform/uno/blob/73b37971a74d6fb0b5f9bbd7546ac187ed66b25b/src/Uno.UI/UI/Xaml/UIElement.Pointers.cs#L732), so on the line you have highlighted it does request an implicit capture to make sure to receive all events.

By "dispatch" I mean not only determining the `OriginalSource` but also effectively forwarding the even to all elements that should receive it. So it's not the `Flyout` the culprit, but the implicit captures made for the `GestureRecognizer`. But then the reason is simply that [as soon as we have a capture, we don't bother to send the event to the `OriginalSource`](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/UIElement.Pointers.Managed.cs#L198). And then I would agree that if we only have *implicit* captures, we should still make sure to send the events to the `OriginalSource`.

I've repro the bug in a sample app, and commenting out lines 198 to 205 does fix the issue. I'll take care to fix it as it involves some weird cases that I want to validate.

Thanks a lot for the investigation, it really helps a lot 👍👍👍!
