### ISSUE TITLE
Ensure that all uno controls defined dependency properties are using `FrameworkPropertyMetadata`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#5984]
Many of the controls defined inside of Uno need to have dependency properties are declared with `PropertyMetadata` instead of `FrameworkPropertyMetadata`. This generally causes issues like this https://github.com/unoplatform/uno/pull/5976.

## Note for implementers
- Changing this implies the creation of a runtime test or an analyzer that scans all dependency properties defined and checks if the metadata is of the right type
- Make changes to all properties metadata that are not of the right type

**Comment by Youssef1313** [comment]
> Changing this implies the creation of a runtime test or an analyzer that scans all dependency properties defined and checks if the metadata is of the right type

Banned API analyzer can be used for that if the usage of `PropertyMetadata` is *mostly* always incorrect.

**Comment by robloo** [comment]
@jeromelaban First time I noticed this. This once concerns me since `FrameworkPropertyMetadata` does NOT exist in UWP or WinUI. It was from the WPF only as far as I can tell. Therefore, this appears to be an uno-specific requirement.

Are there implications for custom 3rd party controls written in Uno? This could be an issue that causes downstream problems.

**Comment by jeromelaban** [comment]
This is only a concern for uno-internal controls, because of considerations related to logical child propagation. This is a behavior that WinUI also provides but that cannot be replicated in controls outside the framework, we implemented the same behavior.
