### ISSUE TITLE
FileSavePicker doesn't open in WASM for Firefox

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6075]
## Current behavior

Create a FileSavePicker and call PickSaveFileAsync.  Dialog does not open in WASM for Firefox 88.0.1 (64-bit).  Opens in Edge and Chrome.

## Expected behavior

FileSavePicker opens in Firefox.

## How to reproduce it (as minimally and precisely as possible)

Attaching a test project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6547540/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment]
The reason for this problem is that Firefox does not yet support the File System Access API that is available in Chromium (see https://caniuse.com/mdn-api_window_showsavefilepicker). As a partial workaround, you can fall back to the "download-based" save picker (as described [here in docs](https://platform.uno/docs/articles/features/windows-storage-pickers.html?q=file%20pick#downloadupload-pickers)). However it is currently not as convenient as could be due to the fact that the "better API" doesn't play nice with `CachedFileManager` yet (https://github.com/unoplatform/uno/issues/5920). I will make sure to improve documentation on this and make a "definitive" sample that works well between all browsers.
