### ISSUE TITLE
ContentProperty not working with MarkupExtension 

### ISSUE THREAD

**Issue by mknotzer** [unoplatform/uno#6112]
```
<TextBlock Style="{StaticResource FontAwesome}" Text="{local:FontAwesome Text=Trash}" /> // OK
<TextBlock Style="{StaticResource FontAwesome}" Text="{local:FontAwesome Trash}" /> // Error
```

```
using System;
using Windows.UI.Xaml.Markup;

namespace DemoProject
{
	[ContentProperty(Name = "Text")]
	[MarkupExtensionReturnType(ReturnType = typeof(string))]
	public class FontAwesomeExtension : MarkupExtension
	{
		public string Text { get; set; }

		protected override object ProvideValue()
		{
			var oFieldInfo = typeof(FontAwesome.FontAwesomeIcons).GetField(Text);

			if (oFieldInfo != null)
				return oFieldInfo.GetValue(null);
			else
				return FontAwesome.FontAwesomeIcons.ExclamationTriangle;
		}
	}
}
```

**Comment by MartinZikmund** [comment]
This feature is unfortunately not available in WinUI yet, so that would not work in a proper cross-platform manner. Please provide this feedback here https://github.com/microsoft/microsoft-ui-xaml/issues/741 or create a separate issue for this feature. Once WinUI supports such approach, we will be able to introduce it as well.

**Comment by jeromelaban** [comment]
The feature mentioned https://github.com/microsoft/microsoft-ui-xaml/issues/741 has been implemented in Uno, but the syntax you've requested is not part of the original specification. If it ever comes to WinUI, we'll implement it.
