### ISSUE TITLE
Remove dependency on System.Json for net6.0

### ISSUE THREAD

**Issue by akoeplinger** [unoplatform/uno#6273]
The System.Json nuget package is deprecated (note: this is a different package than System.*Text*.Json) and will cause issues when consumed from .NET6-based Xamarin apps.

The reason is that the package ships with `_._` entries for the legacy Xamarin TFMs which will be pulled in via NuGet compatibility fallbacks, however there is no System.Json assembly in the net6.0 shared framework (see https://github.com/dotnet/designs/pull/222 for some lengthy discussion).

To fix the issue you'll need to multi-targetting to net6.0 and remove the dependency on System.Json there.

/cc @jeromelaban

**Comment by carldebilly** [comment]
`System.Json` is used by the _Uno's Lottie_ Add-in to update the json document with custom resources (mostly colors). `System.Text.Json` can't be used because its [`JsonDocument` is read-only](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#jsondocument-is-read-only) and it seems there's no efficient way to update a json document with it.

On Android, there's a dependency to Newtonsoft's Json.NET because there's a [bug in LottieXamarin for Android](https://github.com/Baseflow/LottieXamarin/issues/303).

**Comment by jeromelaban** [comment]
Thanks for the update @akoeplinger!

We're still looking at integrating with .NET 6, and we hope that Preview 5 will help us move forward. The dependency on System.Json is the least of the problems (we could pull in the whole System.Json code as a workaround), as I'm not sure if the dependency on https://github.com/Baseflow/LottieXamarin will work on .NET 6 anyways.
