### ISSUE TITLE
[DualScreen] Update implementation to use Window Manager

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6507]
## What would you like to be added:

Support for the newer Dual Screen set of APIs, through https://www.nuget.org/packages/Xamarin.AndroidX.Window/

## For which Platform:

Android

## Anything else we need to know?

The current implementation for dual screen support is located here: 

https://github.com/unoplatform/uno/blob/d57d8ed572184968a801dda815ac30bba96122cc/src/Uno.UI.DualScreen/DuoApplicationViewSpanningRect.cs#L14

It is currently using https://www.nuget.org/packages/Xamarin.DuoSdk, and should be migrated.

**Comment by conceptdev** [comment]
Examples of how to use AndroidX.Window are available in this [samples PR](https://github.com/microsoft/surface-duo-sdk-xamarin-samples/pull/16), as a starting point.

**Comment by conceptdev** [comment]
Now that the underlying is API is in [beta](https://www.nuget.org/packages/Xamarin.AndroidX.Window), I've made a bit of progress on a working proof-of-concept:

https://github.com/conceptdev/uno-samples/tree/main/WindowManager

Seems to be surfacing all the right info into the Uno app and TwoPaneView control, and works on different foldable devices/emulators. The main problem still-to-be-solved is the reliance on setup in the main activity and hooking up a layout changed event for state changes.

Also, I propose rather than 'updating' `Uno.UI.DualScreen` (which is heavily Surface Duo focused, in terms of the API and even the classnames), we instead create a replacement `Uno.UI.Foldable` package which is backwards-compatible in terms of supporting the interfaces from the original package, but adds a new interface `INativeFoldableProvider` for additional data as well as supporting more devices under the original API shape.

**Comment by jeromelaban** [comment]
Very nice implementation!

I see the point of creating a new package, and it makes sense to go this route to avoid the too specific name.

w.r.t state changes, aside from the dependency on `ContextHelper.Current` is there something else that is missing in the sample? (e.g. a specific method override in the main activity ?)

**Comment by conceptdev** [comment]
The main thing missing in this implementation is a way for the Window Manager callback to trigger a layout change when the device is folded (eg from flat to 90 or vice versa). This causes the `IsSeparating` value to change on other foldables, and currently there's no way to force the layout to update in this case - we might want to update `TwoPaneView` to switch between single- and two-pane behavior based on this posture change (to support Samsung's _Flex Mode_ UX). I briefly looked at the layout lifecycle in Uno to see how this would need to be done, but I don't really know the best way to accomplish this yet.

The other hack here is using `bool` to model the [foldable properties](https://github.com/conceptdev/uno-samples/blob/main/WindowManager/WindowManager/WindowManager.Shared/INativeFoldableProvider.cs#L26-L40) versus creating enums for them. I _think_ the enums probably belong with `TwoPaneView` and not in this separate package, but this leads into a design/spec discussion for making changes to `TwoPaneView` to better support the broader foldable ecosystem (maybe that's a different 'issue'?).

For now I'll work on extracting the implementation into a separate project, so it'll be clearer what `Uno.UI.Foldable` would look like, and perhaps look at how to solve the callback>re-layout requirement.

**Comment by conceptdev** [comment]
Code and interfaces have been split out into separate projects/dependencies, and `EventHandler<NativeFold> LayoutChanged` has been added to listen for layout changes from Window Manager.

There is still tight coupling to the **MainActivity** - need to figure out the correct "Uno way" to package this... but I can't help thinking we'll have to put _something_ in `Windows.UI.Xaml.ApplicationActivity`, even though you want to avoid polluting that as much as possible.

Finally, the added API elements need some more thought/design-review, esp the enums.

![image](https://user-images.githubusercontent.com/199373/132418917-43186600-b110-4d6b-90ec-82642513c77b.png)

**Comment by conceptdev** [comment]
Basically, although the `ApplicationActivity` doesn't _have_ to implement `IConsumer` itself, it could be a separate class. I think the trick is wiring up the `WindowInfoRepositoryCallbackAdapter` and adding/removing the listener at the right place in the lifecycle... and only when needed (ie I guess when the Uno.UI.Foldable NuGet has been included).

The original DualScreen API was easier because it was 'on demand' versus this pattern that wires up a listener in a certain place in the activity lifecycle.

Thinking out loud... would it make sense to do `ApiExtension(typeof(IConsumer...` and provide an implementation in `Uno.UI.Foldable`, and the ApiExtensibility.CreateInsatnce<IConsumer>()` in the ApplicationActivity and only wire it up if not `null?` Would that be too much overhead for the bulk of the time it isn't needed? Or is there a pattern or thinking where you've solved this before?!

**Comment by jeromelaban** [comment]
Makes sense! I think there are two things needed here w.r.t initialization. First, the internal `Application` class should be initializing `HingeAngleSensor`, which in turn would try to do `ApiExtensibility.CreateInstance` if available. At that point, the extension could hook onto the `Create` event on `Uno.UI.BaseActivity` or something similar (like an extension method to avoid the direct dependency on `BaseActivity`) to invoke `WindowInfoRepositoryCallbackAdapter` at the right time.

Would that make sense ? Since the foldable package is optional, it would not incur an additional startup time if not needed, and even then, since it's only a small invocation during `Create`, it's likely to not impact much.

**Comment by conceptdev** [comment]
UPDATE 11/16: using betae02 of the [Xamarin.AndroidX.Window.WindowJava](https://www.nuget.org/packages/Xamarin.AndroidX.Window.WindowJava/) package supports the TwoPaneView control:

![uno-twopaneview](https://user-images.githubusercontent.com/199373/142044549-d0db879e-aaff-47cb-82c9-eec9926bf880.png)
