### ISSUE TITLE
[Android] Textbox - AutoFocus doesn't work when Textbox is inside ValidationView

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#6572]
## Current behavior

Entering a page with a TextBox with Autofocus set to true, doesn't give focus on android (unlike ios and uwp) 

## Expected behavior

When entering the page focus should be given to Textbox and Keyboard should open.

## How to reproduce it (as minimally and precisely as possible)

In TradeZero application
Select burger menu
Click create button
Notice Bug

## Workaround

None. Also could not reproduce the issue in a repro sample.

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

Uno.UI: 3.9.0-dev.307
Uno.SourceGenerationTasks 3.1.0
Uno.UI.RemoteControl: 3.9.0-dev.233

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (Version 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeanplevesque** [comment]
@MaximeDion-Work Can you create a repro sample?

**Comment by MaximeDion-Work** [comment]
I tried making a sample but it would not reproduce the issue, but I've tried a bunch of different version of Uno.UI and the bug is always there.

**Comment by jeromelaban** [comment]
If you're making a sample, keep it even if it does not work and post it here.

**Comment by MaximeDion-Work** [comment]
[ReproAndroidAutoFocus.zip](https://github.com/unoplatform/uno/files/6900249/ReproAndroidAutoFocus.zip)

**Comment by jeromelaban** [comment]
@MartinZikmund is this related to what you're currently looking at ?

**Comment by MartinZikmund** [comment]
> @MartinZikmund is this related to what you're currently looking at ?

It could be related, but my current changes don't fix it yet. I will look further into it

**Comment by jeromelaban** [comment]
We won't be able to troubleshoot this issue with a repro that's not out of the project.

Debugging the `ControlExtensions.IsAutoFocus` is likely to be the best course of action to determine what's being focused instead of the TextBox. You may need to find if another control is forcibly taking the focus by looking at the focus manager.

**Comment by jeromelaban** [comment]
You can also try by observing the `FocusManager` focus changed event to find which control steals the focus.

**Comment by vincentcastagna** [comment]
By looking at the behavior, focus is being done correctly on the `TextBox`. So nothing seems wrong in the `ControlExtensions.IsAutoFocus`. When removing the `DataValidationView `(which is a control) that wraps the `Textbox`, the keyboard appears and focus seems to be managed correctly. Note that `DataValidationView.TabStop` is being set to `false `to prevent this. 

Focus Manager logs WITH DataValidationView 

```
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Losing Focus ==== OLD ELEMENT => Windows.UI.Xaml.Controls.TextBox 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== NEW ELEMENT IS NULL 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== OLD ELEMENT => Windows.UI.Xaml.Controls.TextBox 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== NEW ELEMENT IS NULL 

```
Focus Manager logs WITHOUT DataValidationView 

```
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Losing Focus ==== OLD ELEMENT IS NULL 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== NEW ELEMENT => Windows.UI.Xaml.Controls.TextBox 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Losing Focus ==== OLD ELEMENT IS NULL 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== NEW ELEMENT => Windows.UI.Xaml.Controls.TextBox 
[TradeZeroApp.Views.Content.CreateOrEditWatchlistPage] On Getting Focus ==== NEW ELEMENT => Windows.UI.Xaml.Controls.TextBox 
```

**Comment by jeromelaban** [comment]
One thing to experiment with is to place (or remove) the IsTabStop somewhere in the parents of the TextBox. As it is the only textbox in the page, the behavior defined in https://github.com/unoplatform/uno/pull/6651.

@MartinZikmund would you have some more insights? Also, we should be added some additional documentation to describe this behavior.

**Comment by MartinZikmund** [comment]
@jeromelaban @vincentcastagna The problem is caused by how `ContentControl` interplays with focus on Android.

The sequence currently looks like this:

1. `IsAutoFocus` extension sets focus on `TextBoxView`
2. `ContentControl` gets initialized and temporarily removes `TextBox` from its children
3. `TextBox` gets notified by focus listener that native focus will be lost and plans to unfocus in managed code on dispatcher
4. `TextBox.Loaded` is called
5. `IsAutoFocus` extension focuses again during the loaded event handler, but as `TextBox` is still focused from managed standpoint it does nothing
6. The delayed callback from 3) is executed on `Dispatcher` and unfocuses the `TextBox`.

The solution is to adjust the code of `Nventive.Views.Extensions.ControlExtensions.IsAutoFocus` to set the focus on Android only after `Loaded` event, not before, e.g. in the `IsAutoFocusChanged` method (screenshot from ILSpy below) wrap `RequestFocus(val)` in `#if !__ANDROID__`:

![image](https://user-images.githubusercontent.com/1075116/152386689-25fbe476-6aeb-46b6-9d3c-cf42be7df2cf.png)

**Comment by jeanplevesque** [comment]
@MartinZikmund For reference, the code of the behavior is here https://github.com/nventive/Nventive.View/blob/master/src/View.Uno/Extensions/ControlAutoFocus/ControlExtensions.AutoFocus.cs
