### ISSUE TITLE
PointerPressed Event takes a second to be called on iOS

### ISSUE THREAD

**Issue by AugustinBo** [unoplatform/uno#6583]
## Current behavior

PointerPressed Event takes a second to be called on iOS. Thus, it is possible to manipulate an element without having its PointerPressed Event called. 

## Expected behavior

PointerPressed Event should be called instantly on touch or mouse down on iOS as it is with UWP and Android.

## How to reproduce it (as minimally and precisely as possible)

1. Press and hold on the green rectangle without moving, when the PointerPressed Event is registered the rectangle wil be red. It is possible to move the mouse without moving the scrollviewer. (It is the expected behavior) Release to reset the rectangle to green.
2. Press and hold on the green rectangle and immediately scroll up or down. You will notice the rectangle will not change color. PointerPressed isn't called and it is possible to scroll.  

[PointerPressedHandledDemo.zip](https://github.com/unoplatform/uno/files/6896090/PointerPressedHandledDemo.zip)

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment]
This is actually the expected behavior. On iOS, for performance consideration, the [`UIScrollView` defers the pointers until it has determined if “scrolling is the intent”](https://developer.apple.com/documentation/uikit/uiscrollview/1619398-delayscontenttouches).

Unfortunately we didn’t exposed that property on the `ScrollViewer` yet, but you can somehow configure it by setting a `ManipulationMode="None"` on the green `Rectangle` itself. This will however **prevent to initiate scrolling** starting from this rectangle.

FYI, the default manipulation mode `System` means that the `ScrollViewer` can do almost whatever it wants with pointers on UWP. Mainly, it signifies that it can raise `PointerCanceled` whenever it determines that it needs to scroll, and then pointers won’t even be sent to the UI tree. Setting `ManipulationMode` to something else than `System` is expected to avoid that “disruptive” behavior.

Is setting the `ManipualtionMode="None"` on the `Rectangle` and acceptable solution for you?

**Comment by jeanplevesque** [comment]
@AugustinBo Can you try David's proposition?

**Comment by AugustinBo** [comment]
It would have been a good solution but I need to be able to manipulate this Rectangle as I wish without affecting the scrollviewer. `ManipulationMode="None"` prevents any ManipulationDeltaEvents.

**Comment by AugustinBo** [comment]
A solution I found to prevent scrolls on the scrollviewer is to change its ManipulationMode as described in this page https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.scrollviewer?view=winrt-20348 in the Remark section. However this solution only works on UWP and does not work with android and iOS.
