### ISSUE TITLE
[templates] Add support for net5.0+ in the Skia.WPF project

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6592]
## What would you like to be added:

The ability to use `net5.0` or later in the `*.Skia.WPF` project from the templates.

## Why is this needed:

Use the latest C# features.

## Workaround

As of Uno 3.9, because of the current structure of WinUI support in Uno, `netX.0-windows` is not including any of the source generators, which prevents the `*.Skia.WPF` project to be upgraded from its current `netstandard2.0`.

To enable this, change the following line:
https://github.com/unoplatform/uno/blob/c87f211b5aa167b79026e6bf3359c22bc290b0b0/src/SolutionTemplate/UnoSolutionTemplate/Skia.WPF/UnoQuickStart.Skia.WPF.csproj#L10

To
```xml
<PackageReference Include="Uno.UI" Version="3.9.1" />
```

And add the following to the end of the first `PropertyGroup` node:
```xml
<IsUnoHead>true</IsUnoHead>
```

This will avoid any transitive references to WPF to be detected and force the change the target framework to be `net5.0-windows`, with the following message:
```
error NETSDK1136: The target platform must be set to Windows (usually by including '-windows' in 
the TargetFramework property) when using Windows Forms or WPF, or referencing projects or packages that do so.
```

**Comment by brinko99** [comment]
With the workaround applied to the Skia.WPF project directly, I'm continuing to see error CS1061: 'App' does not contain a definition for 'InitializeComponent' and related build errors (not just Intellisense). I understand that this suggests that the source generators aren't running properly.

The workaround mentions, adding a reference to the Uno.UI package instead of the Uno.UI.Skia.Wpf package. I believe this should be Uno.WinUI instead, though I've tried both.

I've tried the NET6 template as well with similar results for the WPF head.
