### ISSUE TITLE
Load time bound `StaticResources` are not resolved when using `x:Load` in a `DataTemplate`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6700]
## Current behavior

```xaml
<DataTemplate x:Key="MyContainerTemplate" x:DataType="local:When_xLoad_DataTemplate_In_ResDict_Model">
	<StackPanel>
		<TextBlock x:Name="tb01"
				Text="Please fill in the empty form fields."
				x:Load="{x:Bind Visible, Mode=OneWay}"
				Margin="15"
				Foreground="{StaticResource MyBrush}" />
		<TextBlock x:Name="tb02"
				Text="Please fill in the empty form fields."
				Margin="15"
				Foreground="{StaticResource MyBrush}" />
	</StackPanel>
</DataTemplate>
```

The following code will not update the foreground for the `x:Load` marked control and its children.

## Workaround

Use file defined static resources, or place the content being marked `x:Load` in a `UserControl`.

## Works on UWP/WinUI
Yes 

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.7

**Comment by hawkerm** [comment]
Hmm, wondering if this bug is what I'm seeing in my UserControl [from comment here](https://github.com/unoplatform/uno/issues/4502#issuecomment-1034440865) on `4.2.0-dev.13`. I think it's at least related.

I was getting a `warn: Uno.UI.ResourceResolver[0] Couldn't statically resolve resource AlignmentConverter` message until I moved the converter out of the UserControl and into my App.xaml. But it's also working now if I remove the x:Load, so that does seem to be the culprit.

It seems like the x:Load is causing it to not look in the local UserControl resource dictionary as it walks up the path compared to when its loaded normally, as in either case it's finding it when it's in the App.xaml instead...

It's interesting though as this seems the opposite of your suggested workaround @jeromelaban. So not sure if this is the bug or just another similar case? Updated my structure in the comment I linked to above.

Let me know if you want more info on my setup that I'm seeing.
