### ISSUE TITLE
[iOS] The commandbar doesn't handle the notch when navigating back from a page displayed in landscape.

### ISSUE THREAD

**Issue by PhilippeAudet-Stratejia** [unoplatform/uno#6717]
## Current behavior
On iOS, When navigating from a page displayed in landscape mode to a page that is displayed in portrait mode, the commandbar doesn't handle the notch on the phone anymore. This bug only happens when using the back button from the commandbar. Navigating from a button in the page will not cause this issue.

## Expected behavior
When navigating from a page displayed in landscape mode to a page that is displayed in portrait mode, the commandbar should handle the notch on the phone.

## How to reproduce it (as minimally and precisely as possible)
- Open the app
- Click on the "Navigate to landscape page" button
- Click on the "Rotate screen" button
- Navigate back to the previous page using the back button of the commandbar.

Notice how the command bar is located under the notch and is no longer usable.

**Note** I have also added a button in the page to navigate back. You can see the issue is not present when using this button.

[CommandbarNavigationSample.zip](https://github.com/unoplatform/uno/files/6963277/CommandbarNavigationSample.zip)

## Screenshots and Video
Upon launching the app : 
![image](https://user-images.githubusercontent.com/83981176/129114904-83cdabb6-a44e-4fd3-be6f-1a4d5cc04799.png)

after navigating back (Notice the cog icon is below the battery)
![image](https://user-images.githubusercontent.com/83981176/129115017-7d9ad15d-4150-4df2-9813-72db968e275b.png)

Video

https://user-images.githubusercontent.com/83981176/129115208-7032c3ef-fe79-413d-bb9a-5295688b09aa.mp4

## Workaround

Override the `NavigationCommand` like this:

```
<ios:CommandBarExtensions.NavigationCommand>
	<AppBarButton Command="{Binding NavigateBack}">
		<AppBarButton.Icon>
			<BitmapIcon UriSource="{StaticResource BackIcon}" />
		</AppBarButton.Icon>
	</AppBarButton>
</ios:CommandBarExtensions.NavigationCommand>
```

## Works on UWP/WinUI

This issue isn't relevant on UWP.
## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [x] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.Core: 2.4.0
Uno.UI: 3.9.7
Uno.UI.RemoteControl: 3.9.7

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.10.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper

**Comment by jeromelaban** [comment]
I don't know if this is something that the native appbar is able to do. Do you have examples of other applications that do the same thing? Also can you past a screenshot of the issue?

**Comment by PhilippeAudet-Stratejia** [comment]
Absolutely, I have updated the issue with screenshots and a video. You can see that navigating back with a button on the page (using `Frame.GoBack` doesn't cause the issue.

**Comment by ajpinedam** [comment]
@PhilippeAudet-Stratejia 

This issue is related to the order of events:

When using `Frame.GoBack()` navigation we call the Page related callbacks first (NavigatingFrom, NavigatedFrom, etc) and then we initialize the navigation transition.

On the other hand, when the navigation is triggered from the Navigation Back Button, the navigation transition is executed immediately and then the Page events are triggered.

This difference in events is affecting the CommandBar calculation. For the case of Back Button navigation the CommandBar for the "previous page" is recalculated based on the state/size of the "current page". But this state/size is changed right in the middle (when the Page events are happening) and this is causing the NavigationBar to have a wrong configuration.

We were looking for a way to "fix" this but unfortunately, this would require changing the way the Nav Bar Back Button navigation is handled, and with this change, we could be breaking one or two things.

Is for that we believe the best solution here is finding a workaround or a different way to accomplish the requirement you have. One possible way could be instead of navigating using pushing you could use a Modal view, this would prevent the NavigationBar reuse.

cc: @jeromelaban
