### ISSUE TITLE
Uno Platform doesn't follow accent colour on macOS

### ISSUE THREAD

**Issue by Jaiganeshkumaran** [unoplatform/uno#6767]
## Current behavior
On macOS, SystemAccentColor is set to the hard-coded value - blue instead of using the user's accent colour selected in System Preferences.

## Expected behavior
SystemAccentColor should be set to the user's accent colour by default.

<img width="1741" alt="Screenshot 2021-08-14 at 12 48 12" src="https://user-images.githubusercontent.com/45227503/129438530-bed717dd-d231-47d0-bf58-06690a245c27.png">

Here's an example using NavigationView which doesn't apply the user's accent colour for the selection indicator.

Related to https://github.com/unoplatform/uno/issues/3555

**Comment by iury-kc** [comment]
I tried to reproduce the issue using the same xaml on a UWP in Windows 10 Dark:


![image](https://user-images.githubusercontent.com/100223422/160918585-af6859ad-5e0a-418d-b776-11e4d3d84487.png)

And a macOS app on a  Mac Dark 

![image](https://user-images.githubusercontent.com/100223422/160920307-fc939e2f-8a61-4fc5-a478-863b604529e4.png)

Except by the TextBlock ForeColor, the patterns seems the same. 

Test 1: 
Changing from Dark to Light on Windows (claro = Light in portuguese) : 
![image](https://user-images.githubusercontent.com/100223422/160919542-2d4cd008-427e-49ce-aff9-73ae42b5b2e0.png)

When changing the macOS accent to Light, there's no immediatly response by the UNO app.

![image](https://user-images.githubusercontent.com/100223422/160920549-e1089691-3d4f-493a-aeab-531430762d3b.png)

However, if we close and reopen the app, only WindowColor was different:

![image](https://user-images.githubusercontent.com/100223422/160919968-d832faec-cd91-48e4-9717-1ec8958ed9aa.png)

So there's two behavior diferences here: 

- Screen doesn't change colors immediately when SO colors change.
- Not all the colors are exactly the same for both SOs. Maybe this could be some environment customization that has passed. I'll investigate. 

-------------------------
Test 2: 
Accent color doesn't change even after restarting the app:

![image](https://user-images.githubusercontent.com/100223422/160921780-34cd5279-11e5-46a0-be7c-bcd2d0b6f60f.png)

**Comment by iury-kc** [comment]
At microsoft documentation, a found that uiSettings.getColorValue( ) can get the system colors.

However, taking a look at:
https://github.com/unoplatform/uno/blob/f2d7335b7c37c99533de81d72f6d9bcfbd14010b/src/Uno.UWP/UI/ViewManagement/UISettings.cs#L51

I saw that the colors have their value fixed (as the issue supposes) inside the method as well as on SystemResources.xaml 

And found the following comment: 
```

// The accent color values match SystemResources.xaml in Uno.UI
// as we can't access Application resources from here directly.
```

After researching a while, i saw some discussions about Xamarim not been able to do that as well, since Big Sur.

If it's really not possible to get the current system color's values, it will be not possible to solve this issue.

**Comment by jeromelaban** [comment]
Can you link to the discussions you found?

**Comment by iury-kc** [comment]
Right! 
Here the discussion is long and about setting (and other stuff) not reading, but the same subject:

[](https://github.com/xamarin/xamarin-macios/issues/10275#issuecomment-855436269)

If we take a look at Apple Dev Docs, 
[](https://developer.apple.com/documentation/appkit/nscolor/ui_element_colors)

We have the properties linked to the system colors, like 

`class var controlAccentColor: [NSColor](https://developer.apple.com/documentation/appkit/nscolor) { get }`

What I expected was a way to subscribe the app to some kind of notification from the API.

** More related material:
[](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color/)

**Comment by jeromelaban** [comment]
Following the accent color would be a good start, then we can figure out how to refresh when the color changes.

**Comment by iury-kc** [comment]
I found this [tip](https://stackoverflow.com/questions/51695755/how-can-i-determine-the-macos-10-14-accent-color)

Using the terminal, it answer well. Maybe we can use this approach to discover the color and update that information inside the uno application.

**Comment by iury-kc** [comment]
With AppKit.NSColor.ControlAccent we can see the exactly color from macOS:

` 

            var accentColor = (AppKit.NSColor.ControlAccent);

            rectColor.Background = new SolidColorBrush(accentColor);
`

Using the sample at
 [https://platform.uno/docs/articles/guides/status-bar-theme-color.html?q=color](https://platform.uno/docs/articles/guides/status-bar-theme-color.html?q=color) 

I could see that UISettings.ColorValuesChanged is not been called when we change any color on macOS settings.
The event is raised only when we change the color scheme (dark / light / auto). 

On this [thread](https://stackoverflow.com/questions/51695755/how-can-i-determine-the-macos-10-14-accent-color)
I found we must listen to: AppleColorPreferencesChangedNotification to follow AccentColor changes.

**Comment by iury-kc** [comment]
So, there's a way to ask the colors values, using NSColor. Besides the namespace is probably deprecated and doesn't match all the available colors like:

[https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors](https://developer.apple.com/design/human-interface-guidelines/macos/visual-design/color#system-colors)

The problem here is that doesn't seem to have a way to ask colors for specific schemas (dark, light..). Instead of that, is possible to ask the actual color. as NSColor.ControlAccent or NSColor.ControlBackground. 

@jeromelaban what would be the best approach in this case? 

My first thought was that the app doesn't need to know the colors themselves (light, dark...), just need to use the active colors at that time. And it's not compatible with cases where users want the app having a different scheme from the OS. 

Of course, in this scenario, maybe would be better to use an app default scheme (as we are really using right now), even it is not compatible with the OS colors.

**Comment by jeromelaban** [comment]
We can make this a feature flag if needed. Let's try reading the color when there's a notification and see which color we do get. (Let's try in a sample app first to see what happens)

**Comment by iury-kc** [comment]
If i understood correctly, uno are using Xamarin.mac.dll right?
Or is there anywhere else that Uno is handling the system notifications?
The version we are using only follow the dark/light switch. And accordingly Apple Docs, we must follow systemColorsDidChangeNotification. 

I already did the sample, that was how i could see the color changes. I would like to understand more about how Uno "talks" to mac to ensure we are going to a good path. Is there any part of docs that has something about it? Thanks!!

**Comment by jeromelaban** [comment]
Good. If you see the colors changing properly with Xamarin.mac, particularly when the theme changes as well, this means we'll be able to integrate it into uno.

**Comment by iury-kc** [comment]
Related issue: [https://github.com/unoplatform/uno/issues/5926](https://github.com/unoplatform/uno/issues/5926)

**Comment by iury-kc** [comment]
Related issue #5926

**Comment by iury-kc** [comment]
Since the only possible way for now (Xamarin.mac.dll actual version) is to see the Dark / Light mode changing, not specific color changings, i think the closest way to satisfy this issue is overriding 
```
public Color GetColorValue(UIColorType desiredColor)
		{
			var systemTheme = SystemThemeHelper.SystemTheme;
			return desiredColor switch
			{
				UIColorType.Background =>
					systemTheme == SystemTheme.Light ? Colors.White : Colors.Black,
				UIColorType.Foreground =>
					systemTheme == SystemTheme.Light ? Colors.Black : Colors.White,
				// The accent color values match SystemResources.xaml in Uno.UI
				// as we can't access Application resources from here directly.
				UIColorType.Accent => Color.FromArgb(255, 51, 153, 255),
				UIColorType.AccentDark1 => Color.FromArgb(255, 0, 90, 158),
				UIColorType.AccentDark2 => Color.FromArgb(255, 0, 66, 117),
				UIColorType.AccentDark3 => Color.FromArgb(255, 0, 38, 66),
				UIColorType.AccentLight1 => Color.FromArgb(255, 66, 156, 227),
				UIColorType.AccentLight2 => Color.FromArgb(255, 118, 185, 237),
				UIColorType.AccentLight3 => Color.FromArgb(255, 166, 216, 255),
				_ => Colors.Transparent
			};
		}
```
And binding the following 3 options with the available actual system colors:
 
- UIColorType.Background  
- UIColorType.Foreground  
- UIColorType.Accent 
like:
 UIColorType.Accent =  new SolidColorBrush(AppKit.NSColor.ControlAccent);
 
And check the dictionaries to be sure this 3 colors are not hardcoded anywhere else.

**Comment by jeromelaban** [comment]
That's fine for now, I'd guess. `systemColorsDidChangeNotification` does not provide proper notifications?

**Comment by iury-kc** [comment]
Probably. However, it seams not accessible on the actual version of Xamarin.mac.dll. At least i couldn't access that on the Uno project.

**Comment by jeromelaban** [comment]
This is what is available in Xamarin.mac:
```csharp
// AppKit.NSColor
using Foundation;
using ObjCRuntime;

/// <summary>To be added.</summary>
/// <value>To be added.</value>
/// <remarks>To be added.</remarks>
[Field("NSSystemColorsDidChangeNotification", "AppKit")]
[Advice("Use NSColor.Notifications.ObserveSystemColorsChanged helper method instead.")]
public static NSString SystemColorsChanged
{
	get
	{
		if ((object)_SystemColorsChanged == null)
		{
			_SystemColorsChanged = Dlfcn.GetStringConstant(ObjCRuntime.Libraries.AppKit.Handle, "NSSystemColorsDidChangeNotification");
		}
		return _SystemColorsChanged;
	}
}
```

of `NSColor.Notifications.ObserveSystemColorsChanged`

Have you tried to use this directly to observe color changes ?

**Comment by iury-kc** [comment]
Hummmm ! 
Nice!
Adding the following to uiSettings.cs did the job. 

```
NSColor.Notifications.ObserveSystemColorsChanged((sender, eventArgs) =>
			{
				OnColorValuesChanged();
			});

```
