### ISSUE TITLE
[Wasm] The keyboard navigation buttons do not work in a TextBox

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#6933]
### Current behavior

The Home, End and arrow keyboard keys don't have an effect in a `TextBox`.

See https://playgroundcanary.z19.web.core.windows.net/#textbox in Uno 3.10-dev.

### Expected behavior

Home and End, or other navigation keys move the cursor,

### How to reproduce it (as minimally and precisely as possible)

Go to https://playgroundcanary.z19.web.core.windows.net/#textbox, enter some text then press the home button. Notice that the cursor stays at the end.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment]
It looks like the keydown event is registered with `HtmlEventDispatchResult.StopPropagation`. That's what prevents the browser from doing the navigation. I'll try to dig more.

**Comment by Youssef1313** [comment]
Maybe it's arround https://github.com/unoplatform/uno/blob/9efab96fd59e28c68fa1430f7cbc74353ebc22bf/src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs#L108 ?

**Comment by Youssef1313** [comment]
@dr1rrb So basically replacing this line:

https://github.com/unoplatform/uno/blob/9efab96fd59e28c68fa1430f7cbc74353ebc22bf/src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs#L155

with `HtmlEventDispatchResult.Ok`, will fix the mentioned issue. But it's very likely it will regress something else. Do you know what this may regress so that I've a better idea into why this is needed and try to adjust the logic?

**Comment by dr1rrb** [comment]
> 
> 
> @dr1rrb So basically replacing this line:
> 
> https://github.com/unoplatform/uno/blob/9efab96fd59e28c68fa1430f7cbc74353ebc22bf/src/Uno.UI/UI/Xaml/UIElement.EventRegistration.wasm.cs#L155
> 
> with `HtmlEventDispatchResult.Ok`, will fix the mentioned issue. But it's very likely it will regress something else. Do you know what this may regress so that I've a better idea into why this is needed and try to adjust the logic?

Well the issue is that if you do that here, it would mean that an event handler which flags the routed args as handled (like  [`KeyRoutedEventArgs.Handled`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.input.keyroutedeventargs.handled?view=winrt-20348) ) would not prevent the native bulling nor the native default behavior. For instance is would mean that is you subscribe to `KeyDown` and you handle the "Back" key press, the browser would still navigate back (maybe not a good example as this key already has some specific support).

The fix really needs to be done on the event handler which is handling the navigation keys and make sure that either is does not flags the args as handled when a `TextBox` is focus, either make that it returns a valid `HtmlEventDispatchResult` instead of a bool.
