### ISSUE TITLE
[Gallery][Android]Flyout(Material) For "Help" section when choose the Nested Flyout for "Settings" the gallery app gets freeze.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6934]
### Current behavior

https://user-images.githubusercontent.com/74563602/131730684-4f3f78f7-5da4-4ed9-ad41-9984fc7d76da.mp4

### Expected behavior

The Nested flyout for Settings should open properly and app should not get freeze.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP for canary.
2. Click "Flyout" option from Burger Menu.
3. Click “Help” Button in “Nested MenuFlyout ” section.
4. Click/Tap the "Send Feedback" section.
5. Click/Tap the "Settings" section.
6. Observe that the app freeze and tap/click is not working.

### Affected platforms

Android

### Anything else we need to know?

Canary Build
 1.5.0 (400825)
Aug 31, 2021

**Comment by Youssef1313** [comment]
Related to https://github.com/unoplatform/uno/issues/4795.

**Comment by Xiaoy312** [comment]
This happens because nested menu-flyout is unable to light-dismiss:
Given this setup:
```
           ┌────────┐
[Button]──►│T1 menu │
           ├────────┤
           │T1 item1│  ┌────────┐
           │T1 item2├─►│T2 menu │
           └────────┘  ├────────┤
                       │T2 item1│
                       │T2 item2│
                       └────────┘
```
when the T1 (tier 1) menu is open, you can still dismiss by clicking any empty space, or complete by pressing the menu items
however, when the nested T2 menu is open, you can no longer light-dismiss by clicking any empty space, or interact with previous menu, but it is still possible to complete by pressing the t2 menu items

the problem here is that, the T3 menu is opened offscreen, effectively locking the option to complete the flyout
you can use the device's native home button or (droid-only)back button to get out of this situation, as alt-tabbing will close any existing flyout

note: normally the flyout should be opened on the left, if the right side will make it offscreen

**Comment by jeromelaban** [comment]
We've made some recent changes, @sakshi173 could you revalidate?

**Comment by sakshi173** [comment]
@jeromelaban , I revalidated it, and found it the issue is happening in the below steps.
1.Launch app and go to 'Flyout' Section.
2. Now first time click on 'Settings' options.
3. Notice that the screen is getting hanged.
4. Now tap mobile's back button(2 times) 
5. Tap again the 'Settings' option.
6. Notice that now the flyout menu works fine. 
Below is the video for the same steps.

https://user-images.githubusercontent.com/74563602/157535220-2b9752f3-4585-47da-8c1b-82059eb48ea3.mp4

**Comment by sakshi173** [comment]
@jeromelaban, I verified this issue is still present.
Steps to reproduce the bug are below.
1.Launch app and go to 'Flyout' Section.
2. Now first time click on 'Settings' options.
3. Notice that the screen is getting hanged.
4. Now tap mobile's back button(2 times)
5. Tap again the 'Settings' option.
6. Notice that now the flyout menu works fine.

**Comment by FrozDark** [comment]
Possible related to the size of flyout
https://github.com/unoplatform/uno/issues/11597

**Comment by nguyeenvy** [comment]
This issue seems resolved in the latest Uno Gallery app.
