### ISSUE TITLE
[Skia][TextBox] The TextBox 2.6 FluentStyle is moving the text up on focus

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#7055]
### Current behavior

Typing text in a TextBox is moving the text up when focusing the TextBox.

![20210913-skia-textbox-shift](https://user-images.githubusercontent.com/5839577/133103889-db4fa783-06b2-4aa2-9c1c-7de721b848e9.gif)

### Expected behavior

The text does not move up when the TextBox is focused

### NuGet package version(s)

3.10-dev

**Comment by Youssef1313** [comment]
This is caused by the use of the `DisplayBlock` (ie, we swap between the TextBox and a TextBlock on focus changes):

https://github.com/unoplatform/uno/blob/daf761172bbc126d53919380a351454f03b153d0/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBoxView.skia.cs#L78-L90

Probably this was a workaround to caret being visible in Skia even if the TextBox is not focused?

**Comment by Youssef1313** [comment]
cc @MartinZikmund Do you remember these details when you implemented the control in https://github.com/unoplatform/uno/pull/5706?

**Comment by Youssef1313** [comment]
Note: After talking with @MartinZikmund, the `DisplayBlock` is currently needed. So the fix is to adjust its positioning so that both native control text and the DisplayBlock text are in exact same position.

**Comment by MartinZikmund** [comment]
I think this is now improved with the positioning changes
