### ISSUE TITLE
Switching between UWP/Fluent themes may cause issues

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#7202]
### Current behavior

When switching between UWP/Fluent themes and back, some styles don't get properly updated.

### Expected behavior

Should refresh properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open the Samples app and navigate to **Unit tests - Unit tests runner**

![image](https://user-images.githubusercontent.com/1075116/134688073-3cf51825-9cb6-4d29-ad5e-34f0c083db58.png)

2. Click the FL checkbox on top right

![image](https://user-images.githubusercontent.com/1075116/134688751-bcbc7f4f-7b9d-49e7-8964-ef59f225d8b1.png)

3. Notice the app switches into an interesting mix of UWP and Fluent styles:

![image](https://user-images.githubusercontent.com/1075116/134688809-12c524da-d77c-4733-bbea-6b7aa7e81c65.png)

4. Click the refresh button

![image](https://user-images.githubusercontent.com/1075116/134688835-3b30301f-0e9c-4729-b429-16a5af579d0c.png)

5. Notice now styles are properly applied

![image](https://user-images.githubusercontent.com/1075116/134688882-18f07522-0d69-4419-9a03-a6166690d3f3.png)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

iOS, Android, WebAssembly, WebAssembly renderers for Xamarin.Forms, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

**Comment by davidjohnoliver** [comment]
This crashes the SamplesApp entirely on UWP, so it's hard to validate what the 'correct' behaviour should be :D

**Comment by Xiaoy312** [comment]
I've replicated the "FL" checkbox implementation away in another sample app:
![20220304 uwp style refresh](https://user-images.githubusercontent.com/2359550/156793548-189db74f-9645-46e2-9efe-a054478e41a8.gif)
[StyleReloadTest7202.zip](https://github.com/unoplatform/uno/files/8186888/StyleReloadTest7202.zip)

The uwp app behaves in a similar way, when a res-dict is removed globally (from App.Current.Resources.MergedDictionaries).
For the loaded controls, the styles are not re-applied when the res-dict is added, but will be when the applied style is gone due to its containing dictionary being removed.

We also have some custom code there to re-apply the style, that there is no-equivalent counterpart for uwp:
https://github.com/unoplatform/uno/blob/67f224d778e90aa4542d8790695359c4a865fb9f/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UITests/Presentation/SampleChooserViewMode.Properties.cs#L415-L419
The interesting mix of styles mentioned in the step#3 should be a result of UpdateThemeBindings updating {ThemeResource} binding of the same name. But, resolving the appropriate style again and re-applying it.
