### ISSUE TITLE
[Gallery][macOS] `CalendarView` - default year and month on the header of the calendar is displaying January 1921, instead of current year and month.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7275]
### Current behavior

![macos calendarview](https://user-images.githubusercontent.com/74563602/135910461-aab49ad5-14a1-43ee-8b17-a2ee513e69bc.png)
![macos calendarview fluent](https://user-images.githubusercontent.com/74563602/135911256-00291437-7cd0-456c-934f-0b84e6d0eaf7.png)
![macos calendarview cupertino](https://user-images.githubusercontent.com/74563602/135911267-afc1ef3a-9ec8-48c3-a269-a7b4aee34609.png)

### Expected behavior

![macos calendarview correct](https://user-images.githubusercontent.com/74563602/135910613-fc6492f8-e320-46ad-81bf-00fa5366b7d1.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "CalendarView" from the "Component" list.
4. Observe that Default year and month on the header of the calendar is displaying January 1921, instead of current year and month.
5. 

### Affected platforms

MacOS

**Comment by nguyeenvy** [comment]
This issue is not present on MacOS anymore. @sakshi173 



![Image](https://github.com/unoplatform/uno/assets/54756963/754365bb-3013-4be4-ab7a-b7ed82f9a4ab)



![Image](https://github.com/unoplatform/uno/assets/54756963/74f00a2b-aaa2-4ea9-9b67-6676c56a6d03)



![Image](https://github.com/unoplatform/uno/assets/54756963/ce08c88c-aa5f-41d7-90f7-72761e13ff3d)


I think this can also be closed.

**Comment by agneszitte** [comment]
Testing is not possible at the moment, it will be fixed when we move to .NET 8
Will need to be brought back to QA Review when testing is possible again

**Comment by MartinZikmund** [comment]
This is no longer relevant as we have a new macOS backend 🚀
