### ISSUE TITLE
[Gallery][iOS/Android/Wasm/Skia.Gtk]Transforms-  Rotated box for 'Rotate Transform' option is displaying outside the outer box.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7540]
### Current behavior
**Wasm/Skia.Gtk Screenshot**
![Transform issue](https://github.com/unoplatform/uno/assets/74563602/0203bd28-61f1-4035-9719-7ee99b3b770a)

**iOS Screenshot**
![Transforms ios](https://user-images.githubusercontent.com/74563602/157924834-9e871489-5951-41ba-85d9-894b459f69d6.png)

**Android Screenshot**

![Transforms Android](https://user-images.githubusercontent.com/74563602/157925137-506a467c-da51-45e8-b1fb-25066bf6e046.png)

### Expected behavior

![Transforms Correct](https://user-images.githubusercontent.com/74563602/157926104-fa515e44-8b9b-4059-b0da-9a77ded0c546.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Transforms" from the "Features" list.
4. Go to Rotate Transforms section.
5. Observe that For 'Rotate Transform' option the Rotated box is displaying outside the outer box or truncating.

### Affected platforms

iOS, Android

**Comment by sakshi173** [comment]
I am able to repro this bug and this issue is still present. please look into this issue

**Comment by sakshi173** [comment]
I am able to repro this bug with the latest canary build and this issue is still present. please look into this issue

**Comment by silviuo** [comment]
Hi @MartinZikmund cc @jeromelaban 

Quick question, not urgent:

Are any of the following acceptable fixes?
![image](https://github.com/unoplatform/uno/assets/10283398/94a7ef99-9c43-444c-b38a-b0c1a45b5fad)
![image](https://github.com/unoplatform/uno/assets/10283398/cb9c2b5d-d138-4997-ab85-ca89f2d8d35e)
![image](https://github.com/unoplatform/uno/assets/10283398/3d29434b-1521-4971-b154-c5a452136ed0)

Or am I missing something? e.g. Is the Rotate function supposed to calculate the placement of the rotated shape so that it's always visible within its container? Thanks!

**Comment by jeromelaban** [comment]
@silviuo I'm not sure of the correct behavior. Could you validate this using the WinUI Windows build?

**Comment by sakshi173** [comment]
@silviuo and @MartinZikmund from Windows Gallery canary build it is displaying outside the box,(similar is displaying for Gallery 5x and 4x canary build), its matching   with windows, then I can close this defect, please let me know your views. Below is the screenshot from Gallery 5x build and Windows canary build.
![Transform correct](https://github.com/unoplatform/uno/assets/74563602/d16f508e-8684-4b23-b6e8-9e08fe45ca4e)

**Comment by agneszitte** [comment]
@jeromelaban, @kazo0, @silviuo  since it is on all platforms including Windows, I think a simple fix for this would be to put more space (margin) around the rotating square to avoid this.

**Comment by sakshi173** [comment]
@kazo0 , @MartinZikmund , @agneszitte This issue is still happening for Skia platform, please suggest your views 
![Rotate issue](https://github.com/unoplatform/uno/assets/74563602/e65a2e8d-9f8c-4139-b9fb-5638fdfbd8f2)

**Comment by agneszitte** [comment]
> @kazo0 , @MartinZikmund , @agneszitte This issue is still happening for Skia platform, please suggest your views

@kazo0, @MartinZikmund maybe it is due to the size of the Window not sure.
But based on what I already shared previously: https://github.com/unoplatform/uno/issues/7540#issuecomment-1693598274
- If for the same Window size we have the same behavior on Windows then we can just adjust to something that makes sense to all the responsive aspect + all the platforms.
- If for the same Window size we have a different behavior only on Skia then it is maybe a specific Skia issue.

**Comment by agneszitte** [comment]
> Theoretically - if we made the rotate transform use `0.5,0.5` as its origin and made the container at least `sqrt(2)*a` high, it should never cause problems, right?

@MartinZikmund, is @morning4coffe-dev could maybe help give a quick look at this one? I think it could be a quick fix/verification no?

**Comment by Youssef1313** [comment]
![image](https://github.com/unoplatform/uno/assets/31348972/254d12c5-bff9-49c4-a342-5f5d015da182)

This is the behavior I'm seeing on WinUI and Gtk. @sakshi173 Can you verify if we can close this?

**Comment by agneszitte** [comment]
> This is the behavior I'm seeing on WinUI and Gtk. @sakshi173 Can you verify if we can close this?
@sakshi173 keep us updated with your latest test please

**Comment by sakshi173** [comment]
Verified, this issue is fixed for all platforms (WASM, Android, iOS, Skia.Gtk), due to that closing it.
