### ISSUE TITLE
[Test]  The method marked with TestCleanupAttribute is executed after each tested method

### ISSUE THREAD

**Issue by workgroupengineering** [unoplatform/uno#7899]
### Current behavior

The method marked with TestCleanupAttribute is executed after each tested method

### Expected behavior

According to the specifications of [TestCleanupAttribute](https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2008/ms245546(v=vs.90)), the method marked with this attribute must be executed after all tested methods have been executed.

### Workaround

Implement IDisposable

### Works on UWP/WinUI

No

### Environment

Other

### NuGet package version(s)

Current master 322bb9b286121b6c92dccbd8303653e25a8f5c98

### Affected platforms

Build tasks

### IDE

Visual Studio 2022

### IDE version

17.1.0 Preview 1.1

**Comment by workgroupengineering** [comment]
as i was writing a PR to correct this behavior i realized that the problem is much more extensive, also TestInitialize runs before each method as you can see here:

https://github.com/unoplatform/uno/blob/ae3fa084ad6d3a8a70d809e19c85a24fd595f2f0/src/SamplesApp/SamplesApp.UnitTests.Shared/Controls/UnitTest/UnitTestsControl.cs#L707-L724

I would like to understand if it is a deliberate behavior?

**Comment by jeromelaban** [comment]
This is a probably a mis-reading of the current behavior of the attribute's behavior. F

ixing is likely to break tests that rely on this behavior, but replacing all uses of this attribute with a custom attribute that keeps the current behavior, then add the original intended behavior for mstest attribute.

**Comment by workgroupengineering** [comment]
From a quick research of the use of [TestInitialize](https://github.com/unoplatform/uno/search?p=1&q=TestInitialize) same as MSTest specification. Consequently I do not replace all TestInitialize instances with the custom attribute, but only those whose tests fail after the behavior change.
What do you think?

**Comment by jeromelaban** [comment]
Let's try and see which ones fails, indeed! Thanks for looking into this!

**Comment by davidjohnoliver** [comment]
I was actually trying to figure out the behaviour of TestCleanup (and TestInitialize) just recently, and I found the documentation not very clear. I did find [a fairly unequivocal response](https://social.msdn.microsoft.com/Forums/en-US/323db883-d673-481b-bb30-206452dc0fbc/testinitialize-and-testcleanup-example?forum=vstest) from a Microsoft staff member however:

> Usually the TestInitialize and Cleanup attributes are used to Unit Test and Coded UI Test.
(1) [TestInitialize] is used to run code before running each test, usually it is used to prepare aspects of the environment in which your unit test will run and to establish a known state for running your test.
(2) [TestCleanup]is used to run code after each test has run, usually it is used to return the environment to a known state after a test has run; this might mean deleting files in folders, or returning a database to a known state.

So I get the impression that the 'bug' is actually expected behaviour. The usage of these attributes in Uno.UI.Tests (which is using the MS unit test framework directly) seems consistent with that expectation.

If you have a requirement for methods to run only once per class, I _believe_ that is what the ClassInitialize and ClassCleanup attributes are for.

Caveat: I didn't actually test any of this.

**Comment by workgroupengineering** [comment]
I did some tests in MSTest.
My interpretation is wrong.
This is the behavior of MSTest:

```bash
AssemblyInitialize   (once by assembly)
  Class1Initialize   (once by class)
    Class1.ctor      (before each test of the class)
      TestInitialize (before each test of the class)
        Test1
      TestCleanup    (after each test of the class)
    Class1.Dispose   (after each test of the class)

    Class1.ctor
      TestInitialize
        Test2
      TestCleanup
    Class1.Dispose
   Class1Cleanup   (once by class)
    ...
AssemblyCleanup      (once by assembly)
```

```csharp
[TestClass]
public class Initialize
{
    [AssemblyInitialize]
    public static void AssemblyInitialize(TestContext context)
    {
        Trace.WriteLine("AssemblyInitialize");
    }

    [AssemblyCleanup]
    public static void AssemblyCleanup()
    {
        Trace.WriteLine("AssemblyCleanup");
    }
}

[TestClass]
public class Class1 : IDisposable
{
      [ClassInitialize(InheritanceBehavior.BeforeEachDerivedClass)]
      public static void ClassInitialize(TestContext context)
      {
          Trace.WriteLine("Class1Initialize");
      }

      [ClassCleanup(InheritanceBehavior.None)]
      public static void ClassCleanup()
      {
          Trace.WriteLine("Class1Cleanup");
      }

    // 1. Called once before each test
    public TestClass1()
    {
        Trace.WriteLine("Class1.ctor");
    }

    //  2. Called once before each test after the constructor
    [TestInitialize]
    public void TestInitialize()
    {
        Trace.WriteLine("TestInitialize");
    }

    [TestMethod]
    public void Test1()
    {
        // 3.
    }

    [TestMethod]
    public void Test2()
    {
        // 3.
    }

    // 4. Called once after each test before the Dispose method
    [TestCleanup]
    public void TestCleanup()
    {
        Trace.WriteLine("TestCleanup");
    }

    // 5. Called once after each test
    public void Dispose()
    {
        Trace.WriteLine("Class1.Dispose");
    }
}
```
