### ISSUE TITLE
RelativePanel.AlignVerticalCenterWithPanel on multiple elements leads to infinite height

### ISSUE THREAD

**Issue by artemious7** [unoplatform/uno#797]
## I'm submitting a...

Bug report (I searched for similar issues and did not find one)
 

## Current behavior

In Android app when setting `RelativePanel.AlignVerticalCenterWithPanel="True"` on multiple elements in `ListView.ItemTemplate`, the ListView's height becomes (almost) infinite.
![image](https://user-images.githubusercontent.com/16724889/56499441-0ab41680-650f-11e9-81a8-0b23fc04c0a8.png)

## Expected behavior

The `ListView` should display 2 items: gray ellipse and overlapping text on top of it. 
Here's how it looks like in a UWP app:
![image](https://user-images.githubusercontent.com/16724889/56499211-0e936900-650e-11e9-8930-44b3d1e01119.png)

## Minimal reproduction of the problem with instructions

MINIMAL REPRO PROJECT:
[App3.zip](https://github.com/nventive/Uno/files/3103265/App3.zip)

Here's the XAML DataTemplate of ListView items

            <RelativePanel>
                <Ellipse x:Name="picture"
                         RelativePanel.AlignVerticalCenterWithPanel="True"
                         Fill="Gray"
                         Width="40"
                         Height="40" />
                <TextBlock RelativePanel.RightOf="picture"
                           RelativePanel.AlignVerticalCenterWithPanel="True"
                           Text="{Binding Name}" />
            </RelativePanel>

## Environment

```
Nuget Package: 
Uno.UI

Package Version(s): 
v1.44.0
v1.45.0-dev.1292

Affected platform(s):
- [ ] iOS
- [x] Android (tested on v8.0 and v9.0)
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.9.9)
- [x] 2019 (version: 16.0.2)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by carldebilly** [comment]
# Investigations on this issue
Taking this XAML:
``` xml
<RelativePanel>
    <Ellipse x:Name="picture"
			RelativePanel.AlignVerticalCenterWithPanel="True"
			Fill="Gray"
			Width="40"
			Height="40" />
    <TextBlock RelativePanel.RightOf="picture"
            RelativePanel.AlignVerticalCenterWithPanel="True"
            Text="Name" />
</RelativePanel>
```

## Result with XAML Studio (reference result)
![image](https://user-images.githubusercontent.com/4174207/94179725-e9c1c480-fe6a-11ea-8a20-d06de9d8b670.png)

## Result using the Uno Playground:
URL: https://playground.platform.uno/#8ddad720
![image](https://user-images.githubusercontent.com/4174207/94179812-0fe76480-fe6b-11ea-8bf9-8168155586ff.png)

**Comment by carldebilly** [comment]
## Cause of this problem
I found the cause of this problem:
* [Those line of codes](https://github.com/unoplatform/uno/blob/e3fa7b94c58d7555936d16dd9aaf9b07aaf7f969/src/Uno.UI/UI/Xaml/Controls/RelativePanel/RelativePanel.Layout.SiblingGraph.cs#L583_L591) are calculating the vertical position of an element, based on its `Height` property.
* For the `<TextBlock>` element (in my previous comment), the `Height` value will be `NaN` because it's not defined in the XAML
* This calculation is done before calling the `.Measure()`, so the actual measured height is not used here.
* The result of the calculation for the vertical position of the element will be based on the `availableSize` instead of the measured size.

## Effective Workaround
The workaround in this case is to set the dimensions (`Width` & `Height`) of the `<TextBlock>` element instead of relying on the measured size.

## How to fix the problem
The code in `SiblingGraph.GetAvailableAreaForChild()` method should be run after measuring the element and should used the measured size in its logic.
