### ISSUE TITLE
[iOs] BitmapImage needs an escaped Uri to work

### ISSUE THREAD

**Issue by TopperDEL** [unoplatform/uno#8133]
### Current behavior

On iOs the current Bitmap would not be shown with something like this:

```cs
var myUri = new Uri("https://picsum.photos/seed/not working on ios/400/300");
this.DataContext = new BitmapImage(myUri);
```
```xaml
<Grid>
      <Image Source="{Binding}" Width="400" Height="300"/>
</Grid>
```

It works if the URL is escaped like this:
```cs
var myUri = new Uri(Uri.EscapeUriString("https://picsum.photos/seed/not working on ios/400/300"));
```

### Expected behavior

It should work the same on all platforms.

### How to reproduce it (as minimally and precisely as possible)

[UnoUnescapedBitmapImage.zip](https://github.com/unoplatform/uno/files/8097832/UnoUnescapedBitmapImage.zip)

### Workaround

Escape the URL with Uri.EscapeUriString() before.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.0.13

### Affected platforms

iOS

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment]
## Note for contributors

The location of the image loading on iOS is here:
https://github.com/unoplatform/uno/blob/8e4aa1ae615aaa7e01cca9e36521b99bdd3749e6/src/Uno.UI/UI/Xaml/Media/ImageSource.iOS.cs#L265

It is likely be that the use of `OriginalString` is the issue here, yet the use of OriginalString at that location is unclear. It is likely that re-escaping the `OriginalString` will provide the expected behavior.

**Comment by iury-kc** [comment]
It is similar to [https://github.com/unoplatform/uno/issues/8128](https://github.com/unoplatform/uno/issues/8128)

**Comment by iury-kc** [comment]
Hi! It seams the oposite that happens on #8128. 
Now we are working with URLs. So, we need an enconded address to download the file propperly.
So, when debugging we can see the using clause is entirely ignored. 

```
using (var url = new NSUrl(WebUri.OriginalString))
{ ... ... }
```

We need to encode the string again, to make sure var url will be created successfully.
Using using (var url = new NSUrl(WebUri.AbsoluteUri)) solved the problem here, since no matter the original uri is, AbsoluteUri will have an encoded string.
