### ISSUE TITLE
[Skia] Default title bar text

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8356]
## What would you like to be added:

For Skia apps the default title bar text first shows as "Uno Host", until changed manually - this should probably come from a JSON manifest or from Package.appxmanifest.

## Why is this needed:

Better UX.

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by iury-kc** [comment]
On a UWP project, it only shows the name of the EXE file.
Wouldn't be the case to make it work as UWP ?

**Comment by iury-kc** [comment]
We have two lines that define the Title at the construction of the screen:

https://github.com/unoplatform/uno/blob/02f3253efcf68c3e85f6425c246d64aa10f4add9/src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs#L100

and 

https://github.com/unoplatform/uno/blob/02f3253efcf68c3e85f6425c246d64aa10f4add9/src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs#L316


The last one is called at the ending of the same method of the first one. 

https://github.com/unoplatform/uno/blob/02f3253efcf68c3e85f6425c246d64aa10f4add9/src/Uno.UI.Runtime.Skia.Gtk/GtkHost.cs#L191

The "Uno Host" appears during the time between this two lines.
I tested creating the window with the value from the Manifest, like that:
			_window = new Gtk.Window(Windows.ApplicationModel.Package.Current.DisplayName);
On this very specific moment, the DisplayName is empty. That's ok, the window is still created and the program keeps running and the Title is updated for the second time. 
It appears to be cleaner than the old behavior. 

What do you think?

**Comment by jeromelaban** [comment]
@iury-kc I'm reopening this issue, because we also need to fix it for WPF. Could you take a look at it as well ?

**Comment by iury-kc** [comment]
For sure!

**Comment by iury-kc** [comment]
Hummm. Interesting. It is not working anymore.

Windows.ApplicationModel.Package.Current.DisplayName is returning nothing.
Following its code, we can see that the method  Package.Other.cs / TryParsePackageManifest() never have a manifest. 
There's no Package.appxmanifest.xml file in GTK, WPF or TIZEN. 

I`ll investigate what would be a good approach to that.

**Comment by iury-kc** [comment]
Haha. I was using an old Project Template.

**Comment by progmars** [comment]
@iury-kc 

Can you please tell me where / how do I get the new template or fix the problem manually?

Yesterday I installed Uno for Visual Studio 2022, created a blank Uno app selecting WPF and AppKit targets, and when I launched the WPF app, I had empty window title. It seems to be replaced by the code:

`WpfApplication.Current.MainWindow.Title = Windows.ApplicationModel.Package.Current.DisplayName;`

and `DisplayName` is empty in my case. I see you mentioned `Package.appxmanifest` file in the commit, but I don't see anything like it in my project.

**Comment by iury-kc** [comment]
Hi!!
How are you creating the solution? Using command line or Visual Studio New project UI?
Which version of Uno is the project using?
I got this issue when using an old one. Uno was updated a couple of times after that. Probably it is the same path. 
That time, the new template already had the manifest.

**Comment by progmars** [comment]
I have been using this Visual Studio extension:
https://marketplace.visualstudio.com/items?itemName=unoplatform.uno-platform-addin-2022
because that's what the Get Started guide suggested: https://platform.uno/docs/articles/get-started-vs-2022.html?tabs=windows

**Comment by progmars** [comment]
So, the version of Uno dependencies in my projects is displayed as 4.4.13 and the version of the templates I have used is 4.4.13.8.

**Comment by progmars** [comment]
The current behavior seems counterintuitive. One would assume that if the developer has explicitly specified the Title of the MainWindow, it should be applied to the window frame and override the app name in the package.
Only if MainWindow has no title given, then it makes sense to fall back to the app DisplayName from the package manifest.

I tried to add Package.appxmanifest, but it's new territory for me and I kept doing something wrong with version numbers, and my app failed to start. So instead of appxmanifest I added the following workaround:

        string title = string.Empty;

        public MainWindow()
        {
            InitializeComponent();

            // capture the title of the window before letting Uno run
            // Uno will overwrite it from Package.appxmanifest, which I don't want to add
            // (it's missing from the current VS templates)
            title = Title;

            root.Content = new global::Uno.UI.Skia.Platform.WpfHost(Dispatcher, () => new MidinterUno.App());
        }

        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);

            if (!string.IsNullOrWhiteSpace(title))
            {
                // restore the captured window title
                Title = title;
            }
        }

**Comment by iury-kc** [comment]
Actually, the Package.appxmanifest is in .Windows project and it is referenced by other projects like logo and other files:
```
  <ItemGroup Condition="exists('..\TestWinui.Windows')">
    <EmbeddedResource Include="..\TestWinui.Windows\Package.appxmanifest" LogicalName="Package.appxmanifest" />
    <Content Include="..\TestWinui.Windows\Images\StoreLogo.png" Link="Assets\StoreLogo.png" />
    <Content Include="Assets\Fonts\uno-fluentui-assets.ttf" />
  </ItemGroup>
```
Of course you will not find the file inside your Skia Project directory, but in the Windows Project directory. 
It's strange you are having this issue. I tested it some minutes ago and it worked nicely.

Your workaround will do the job as well.

**Comment by progmars** [comment]
Hm, then maybe something's wrong with my VS templates or maybe you are creating something related to UWP or WinUI for Windows and that makes the difference?

Here's how I do it:
1.
![image](https://user-images.githubusercontent.com/4199737/186144232-0c141728-c4f8-4e55-b2bb-3e57eba2c3bc.png)

2.
![image](https://user-images.githubusercontent.com/4199737/186144596-fe5d6e82-e2c7-4aad-bc6c-97e74684cc1a.png)

3.
![image](https://user-images.githubusercontent.com/4199737/186144675-c23c5f9d-0ddf-41d9-be7f-376c910e303b.png)

Important: I intentionally selected only WPF to have a minimal test case. However, my final goal will be WPF and AppKit. No pure WinUI (because I need my app to run on older Windowses).

Here's what it created for me:

![image](https://user-images.githubusercontent.com/4199737/186145007-c5a787d7-fc65-4191-a09a-192b7fcabb1a.png)

No Windows project, no appxmanifest.  

Then I add a fix for https://github.com/unoplatform/uno/discussions/9562#discussioncomment-3443097

and WPF app runs fine, but there's no title by default.
