### ISSUE TITLE
Update All Uno.Samples to Uno 4.1.9

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8404]
Update all the samples present in https://github.com/unoplatform/uno.samples. 

The branch https://github.com/unoplatform/Uno.Samples/tree/dev/jela/uno4 can be used as the base for the update (it updates the CI to VS 2022), and [this documentation](https://platform.uno/docs/articles/migrating-from-previous-releases.html#uno-40) can be used to update the projects for breaking changes when samples are yet updated to Uno 4.0.x or later.

Projects running Android 11 or earlier also need to be updated to Android 12.

**Comment by iury-kc** [comment]
After taking a look at the Samples, I could see they seams not sharing the same template. Would be interesting update the project's template as well?

**Comment by jeromelaban** [comment]
Projects are generally different, you may spend more time trying to adjust the templates to avoid missing app-specific configurations than do the upgrades individually.

**Comment by iury-kc** [comment]
Almost all projects were updated.
Some of them are not working very well on WASM. As recommended, after the upgrade I created an issue for each, on [Uno Samples Repository](https://github.com/unoplatform/Uno.Samples). 
Only WebRTC remains outdated. I couldn't find the reason it just freezes on 

`_signalingServer = new HubConnectionBuilder()
				.WithUrl("http://localhost:6173/webrtc")
				.WithAutomaticReconnect()
				.Build();`

Even using the last preview Uno version, it gets the same behavior there. Since the project freezes exactly on the construction of the HubConnectionBuilder, It appears to be something related to a conflict with any package used on UNO 4.1.9, not an UNO error itself.

**Comment by jeromelaban** [comment]
When you say freeze, does the browser report a freeze, or does the app fail with an exception? It may also be that the exception is not visible and caught by some piece of code.

**Comment by iury-kc** [comment]
No exception is raised on visual studio, nothing related on the browser console. It is like staying on that line forever and nothing after that is called. 
Signal R tries to reconnect 3 times, if i'm not wrong, the time is 30 seconds. 
But i did wait more than that and no errors were raised. 
I`ll try to find a way to reduce the timeout. Just to make sure.
