### ISSUE TITLE
[Wasm] Investigate potential perf improvement by using the CSS `contain`

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#8872]
Like defined there: https://www.smashingmagazine.com/2022/05/lesser-known-underused-css-features-2022/#render-performance-optimization

https://web.dev/content-visibility/#skipping-rendering-work-with-content-visibility may also be of interest in the same area.

**Comment by jeromelaban** [comment]
Investigation shows that due to the way Uno handles layouting (fixed sizes and absolute positioning) both features degrade the overall app performance. 

The only scenario that would applicable is for known hidden items, for which uno already does css visibility changes and off-screen positioning, therefore not bringing any meaningful value.
