### ISSUE TITLE
[Skia] `ApplicationData.Current.LocalFolder` redirects to %appdata%

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#8910]
### Current behavior

`ApplicationData.Current.LocalFolder` redirects to %appdata%, but should redirect to a more app-specific folder.

### Expected behavior

Writing to `ApplicationData.Current.LocalFolder` should be specific to the running app.

## Note for contributors

The behavior for this is currently undefined, as it is mapped to the UWP behavior. We should be mapping to the behavior that `ApplicationData.Current.LocalFolder` shows when running a unpackaged WinAppSDK app for the same API.

**Comment by MartinZikmund** [comment]
This will be a breaking change, but should probably be done soon.

**Comment by MartinZikmund** [comment]
@jeromelaban I think this is one of the breaking changes that are really needed for the next major release

**Comment by MartinZikmund** [comment]
Currently unpackaged WinAppSDK apps just crash when `ApplicationData.Current` is used. See https://github.com/microsoft/WindowsAppSDK/issues/2639, https://github.com/microsoft/WindowsAppSDK/issues/2621 .

Because we have the `Package.appxmanifest`, I think for the default behavior we can read the publisher and app id from there, and also provide a `FeatureConfiguration` to let the developer to override the path and store the app data/settings somewhere else as needed, does that sound like a good solution @jeromelaban ?

**Comment by jeromelaban** [comment]
altering the path using publisher and appid makes sense yes, as for feature configuration, I wonder if an helper class would be more appropriate?
