### ISSUE TITLE
[All] DisplayMemberPath not working on custom control template for ComboBox

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#900]
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

## Current behavior

If using a combobox with a style defined in App.xaml the DisplayMemberPath property is not used.  Works if no style is set.

## Expected behavior

DisplayMemberPath should work in Android as on UWP

## Minimal reproduction of the problem with instructions

[App9.zip](https://github.com/nventive/Uno/files/3212928/App9.zip)
Build attached project and test on Android to see issue.  Note that removing the style from the combox resolves the problem.

## Environment

```
Nuget Package:
Uno.UI
Package Version(s):
1.45.0-dev.1524
Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by carldebilly** [comment]
Initial investigations:
1. This problem still present in last version of `Uno.UI`: `1.45.0-dev.1860`.
2. This problem is not related to the style placed in `App.xaml`: same behavior when the `<style>`
    is placed in the `MainPage.xaml`.
3. This problem is not _Android-only_: same behavior observed on _Wasm_ and _iOS_.
4. **Work-around**: If you add the following lines in your style, it's working:
    ``` xml
    <ContentPresenter x:Name="ContentPresenter"
      [...]
    ContentTemplate="{TemplateBinding ItemTemplate}"
    ContentTemplateSelector="{TemplateBinding ItemTemplateSelector}"
      [...]
    </ContentPresenter>
    ```
    source: <https://github.com/nventive/Uno/blob/76d75099d93c6924313bdc35280584a42d322bb4/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L713-L714>

I will rename this issue to reflect the real problem.
