### ISSUE TITLE
[iOS] List items are missing on fast scroll

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#9416]
### Current behavior

Sometimes when the samples list in the iOS Samples app is scrolled fast, some of the items are blank. Only when scrolled away and back in slowly they appear. The empty space is not interactive, so it is no longer possible to tap on that item until it actually appears.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/1075116/182627182-b7b4e737-a0dd-4222-9c82-d3f8a2b887cd.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/1075116/182627178-37497971-03b2-4655-95f7-84611b1e7cdb.png)

This behavior has been present for a longer time, so not connected to recent changes.

### Expected behavior

Should appear on first try.

### Works on UWP/WinUI

Yes

### Affected platforms

iOS

**Comment by Xiaoy312** [comment]
If a mission critical menu item is missing, just kept scrolling up past it and scroll down.

**Comment by jeromelaban** [comment]
@ajpinedam This issue has been reported on Uno versions as far as 3.11, which may indicate that this is a change in iOS behavior. If this is the case, we may find other instances of `UICollectionView` issues in the wild showing the same thing.

**Comment by Xiaoy312** [comment]
The issue can also be seen on ListView as well on iOS.

taking this sample built for something else as example: [BehaviorTests.zip](https://github.com/unoplatform/uno/files/9418860/BehaviorTests.zip)
by clicking on the 2nd tab 'Page2' and start scrolling through the list,
you can see the issue manifesting immediately, at 100% (not sure) repro rate.

interestingly though if you change the landing page from `MainPage` to `Page2`,
the problem seems to be gone

**Comment by MaximeDion-Work** [comment]
Happens on tradeZero
https://dev.azure.com/nventive/TradeZero/_workitems/edit/256648/
Could not create repro sample so here is a branch to minimaly reproduce bug: https://dev.azure.com/nventive/TradeZero/_git/TradeZero.Mobile?version=GBuno-repro%2Femptyspaceslistview

Heppen on CAA too: 
https://dev.azure.com/nventive/CAA%20National/_workitems/edit/264281/
