### ISSUE TITLE
XAML generated code UNO0001 warnings cannot be ignored

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9627]
I added 'XamlGeneratorAnalyzerSuppressions' to the project file to no avail.

[Uno0001.zip](https://github.com/unoplatform/uno/files/9432884/Uno0001.zip)

_Originally posted by @DierkDroth in https://github.com/unoplatform/uno/discussions/9593#discussioncomment-3482928_

**Comment by Youssef1313** [comment]
@DierkDroth As a workaround, can you try `<XamlGeneratorAnalyzerSuppressions Include="Compatibility-Uno0001" />`?

**Comment by Youssef1313** [comment]
@jeromelaban The current behavior looks intentional. We try to split by `-` and only consider the suppression if the split produced two parts.

- If the first part is `csharp`, we add `#pragma warning disable <second-part>`
- If the first part is not `csharp`, we use `[SuppressMessage("<first-part>", "<second-part>", Justification="Generated code")]` where `<first-part>` is category and `<second-part>` is diagnostic id.

@jeromelaban Can you confirm if this design is intentional? Any improvement we can do? e.g, if no `-` exists, we just add `#pragma warning disable <value>`?

**Comment by DierkDroth** [comment]
> <XamlGeneratorAnalyzerSuppressions Include="Compatibility-Uno0001" />

@Youssef1313 unfortunately this is not working as I get this error
```
<XamlGeneratorAnalyzerSuppressions Include="Compatibility-Uno0001" />
```
... when adding this to my WASM project file
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <DefineConstants>$(DefineConstants)</DefineConstants>
    <NoWarn>NU1701</NoWarn>
    <EnableNETAnalyzers>False</EnableNETAnalyzers>
    <WasmShellIndexHtmlPath>index.html</WasmShellIndexHtmlPath>
    <XamlGeneratorAnalyzerSuppressions Include="Compatibility-Uno0001" />	  
  </PropertyGroup>
```

**Comment by Youssef1313** [comment]
@DierkDroth Keep it in `ItemGroup`, not `PropertyGroup` (just as you had it before)

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 . But it's still not working, I still get these warnings
```
3>C:\Users\dierk\Documents\Unusual\Unusual.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MaterialTheme_0633246ce0a72bf767186235048cb91f.cs(11724,14,11724,105): warning Uno0001: Microsoft.UI.Xaml.Media.Animation.SplitCloseThemeAnimation.OffsetFromCenterProperty is not implemented in Uno
```

I tried:
- adding line above to an existing ItemGroup
- adding a new ItemGroup with just this line

Nothing worked...

**Comment by Youssef1313** [comment]
With the original repro, I stopped getting Uno0001 by using `Compatibility-Uno0001`.

Can you upload a repro with `Compatibility-Uno0001` not working?

**Comment by DierkDroth** [comment]
@Youssef1313 I copied the original code from my app to the repo below (this is a variation of the UNO material theme)

Note: It won't compile (tons of errors) ... however, it will show the warnings which this report is about.  Hope this helps

[Uno0001.zip](https://github.com/unoplatform/uno/files/9460103/Uno0001.zip)

**Comment by Youssef1313** [comment]
Thanks for the repro, I see where the problem is now. We add `SuppressMessage` attribute on `GlobalStaticResources`, but in your case the warnings are in other generated classes.

Please try `csharp-Uno0001` instead of `Compatibility-Uno0001`. It works for me for the last repro.

The idea is that `csharp-Uno0001` is added as `#pragma warning disable Uno0001` at the top of generated files instead of as `SuppressMessage` attribute.

I see another bug that is not revealed by the last repro, `GlobalStaticResources` doesn't add `csharp-` suppressions. They should be added around https://github.com/unoplatform/uno/blob/6ef5f03ac4209db8c53e53c98e9406da65385d8e/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L673-L675

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 

I understand the fixes you're working on will address these issues ... I'll just wait until they are available in the DEV build ...

**Comment by Youssef1313** [comment]
@DierkDroth The issue I'm addressing in #9677 isn't really what you hit. For your last repro, using `csharp-Uno0001` should be sufficient and no warnings will happen.

If, in a larger application, you got warnings in `GlobalStaticResources.cs`, then this is what I'm fixing.

**Comment by DierkDroth** [comment]
Thanks again @Youssef1313

I confirm that this eliminated the warnings in my project

**Comment by jeromelaban** [comment]
The original issue really is a documentation issue that [I discovered during my stream yesterday](https://www.youtube.com/watch?v=1q3twf2Cc8s), where the `XamlGeneratorAnalyzerSuppressions` needs to be prefixed by `csharp` as @Youssef1313 discovered as well. We'll adjust the documentation.

**Comment by DierkDroth** [comment]
Sounds good. This definitely will avoid future confusion @jeromelaban

**Comment by DierkDroth** [comment]
Thanks @Youssef1313 @jeromelaban
