### ISSUE TITLE
Failure building a `net6` Wasm app with Azure Static Apps on GitHub Actions

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#9628]
It looks like there's a dependency on `System.Drawing.Common` for which the linker complains about, and it's definitely not supposed to happen.

_Originally posted by @jeromelaban in https://github.com/unoplatform/uno/discussions/9607#discussioncomment-3484449_

**Comment by jeromelaban** [comment]
Taking a look at the original build log, we're not able to reproduce your issue with current uno builds.

It may also be that you're missing a dependency, can you try adding `<PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />` to your project?

**Comment by Grzesik** [comment]
Hi Jerome, it works now with this additional dependency! The thing is strage, because in VS 2022 the Nuget Package Manager  shows me that the dependency exists, but in the project file it is not present. I added it to the project file and it works now.

The problem is only in Github Actions and Azure Pipeline. When I create a relese App localy it works without this dependency.  It is strange.

Thanks a lot!

**Comment by jeromelaban** [comment]
Thanks for the update! We're fixing parts of this issue in .NET 7, making this dependency a requirement.
