### ISSUE TITLE
[WASM] UIElement.Tapped called in wrong sequence

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9643]
### Current behavior

Please see attached and search MainPage.xaml.cs for '!!!' - I left a few comments.

[Tapped.zip](https://github.com/unoplatform/uno/files/9439404/Tapped.zip)

### Expected behavior

WASM should work as WindowsAppSDK

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by francoistanguay** [comment]
@DierkDroth  Team saying this one isnt an easy fix. Can you explain the context/goal of what you're trying to accomplish by trying to handle/capture pointers?

**Comment by DierkDroth** [comment]
@francoistanguay thanks for getting back to me.

The scenario is pretty simple:
- you have an icon on a grid or a panel or a button or ...
- both needed to have the .Tapped handlers:
-- .Tapped on icon triggers an action specific to the icon
-- .Tapped on grid triggers a more general action
- when triggering .Tapped on icon you wanted to make sure that the general action of the grid **was not triggered**. You're doing this by `e.Handled= true` in .Tapped of the icon, which **should** prevent .Tapped being called on the grid.

Hope this makes it clearer. I could show you actual use cases in my real app if needed.

**Comment by dr1rrb** [comment]
@DierkDroth Yes handling an event is working properly and prevents bubbling ... except in the specific case that you shown in your sample where the container element is a `Button` on WASM. 

The issue is that a `Button` **captures** the pointer on press which has some impact on native dispatch of next events, and on _gesture recognizer_ that will trigger the `Tapped` event.

If you could share with us you real use case, we could see how we could mitigate this issue.

**Comment by DierkDroth** [comment]
@dr1rrb thanks for looking into.

I see what you're saying. I will have to review my use cases and will migrate the Button.Tapped to Button.Clicked and see if there still are issues on other cases where no Button is involved. However, this might take a little while since I will touch WASM again after .NET 7 is out (mid November).

I then will get back to you with my findings (positive or negative). Thanks again.

**Comment by dr1rrb** [comment]
The issue is due to the fact that the `Button` is capturing and then handling the pointer up event. This forces use to bubble events in managed code, which drives the parents to get some event earlier than they should (Pointer up event is raised in the right order, but gesture and manipulations events are not).

So @DierkDroth I looked at your repro and I found 2 workaround for your issue:

# Option 1: Clear the handled flag on `PointerReleased`
Clearing the `Handled` flag on the `Button` itself will resume the native bubbling and will restore the right event sequence.
```csharp
button.AddHandler(PointerReleasedEvent, new PointerEventHandler((snd, e) => e.Handled = false), handledEventsToo: true)
```

The down side of this workaround is that if you have a `Button` embedded in another one, the parent `Button` will also raise the `Click` event while it should not.

# Option 2: Using reflection
Using reflection we will force the parent of your `Button` to abort any gesture recognition:

```csharp
private static readonly MethodInfo? _completeGesture = typeof(UIElement).GetMethod("CompleteGesture", BindingFlags.Instance | BindingFlags.NonPublic);
```

Then in your `Click` event handler:

```csharp
if (_completeGesture is not null && s is FrameworkElement { Parent: UIElement parent })
{
	_completeGesture.Invoke(parent, null);
}
```

**Comment by DierkDroth** [comment]
@dr1rrb thanks for looking into. 

I'll try those work arounds as I'll do my next round of WASM testing (likely as .NET7 + UNO WASM .NET 7 is released). I then will get back to you with my findings.

**Comment by DierkDroth** [comment]
@dr1rrb I went with option #2 which appears to work great.

One question though: do I need to apply this only to the WASM head or to iOS and Android as well?
