### ISSUE TITLE
[WASM] New warning on 'WasmHttpHandlerDeprecatedAnalyzer' right after latest updates

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#9708]
### Current behavior

I get warning below right after recent updates. Please see my config below.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS8032	An instance of analyzer Uno.Analyzers.WasmHttpHandlerDeprecatedAnalyzer cannot be created from C:\Users\dierk\.nuget\packages\uno.winui\4.5.0-dev.737\analyzers\Uno.Analyzers.dll: Could not load type 'Uno.Analyzers.WasmHttpHandlerDeprecatedAnalyzer' from assembly 'Uno.Analyzers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'..	Unusual.Wasm		1	Active
```

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26179242/188099561-4ccfc45b-fcb5-427f-a586-6616c37a51db.png">

**Comment by MartinZikmund** [comment]
@Youssef1313 Maybe you know what could be the cause here 🤔 ?

**Comment by Youssef1313** [comment]
@MartinZikmund This might be caused by the fact that Uno.Analyzers assembly is still 1.0.0.
I'll bump to 1.0.1 as a "temporary" quick fix to first make sure that this is indeed the problem. Then we need to think of a solution that doesn't require us to manually update the version (I think by matching the same versions we use for other Uno packages).

**Comment by jeromelaban** [comment]
@DierkDroth this issue might come in different flavors regularly as an artifact of the way visual studio works in between experimental versions of Uno.UI. Clearing your temp folder and/or restarting Visual Studio could help. In all cases, this is not a blocker.

**Comment by DierkDroth** [comment]
Thanks for clarification @jeromelaban
